import os
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--massRegion",help="",type=str,default="low",choices=["low","mid","high","training","all"])
parser.add_argument("--outputDir",help="",type=str)
args = parser.parse_args()

#channel_dir = '../Results/'+args.massRegion
input_dir = '../Results/'+args.massRegion+'/T_s2thh_NOMINAL/'
output_dir = '../Results/histograms/'+args.outputDir+'/'+args.massRegion+'/root/'
print("Merging ROOT files...")
print("Merging data samples...")
os.system('hadd -j 4 -f -v 2 '+output_dir+'/data.root '+input_dir+'data*.root')
print("Merging MC samples...")
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Signal_sherpa.root '+input_dir+'VBF_Ztautau_sherpa*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Signal_PoPy.root '+input_dir+'VBF_Ztautau_PoPy*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Ztautau_sherpa.root '+input_dir+'Ztautau_sherpa*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Ztautau_sh2214.root '+input_dir+'Ztautau_sh2214*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Ztautau_MG.root '+input_dir+'Ztautau_MG*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zjets.root '+input_dir+'VBF_Zee*.root '+input_dir+'VBF_Zmumu*.root '+input_dir+'Sh_2211_Znunu*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Higgs.root '+input_dir+'ggHtt*.root '+input_dir+'VBFH*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/VBF_Higgs.root '+input_dir+'VBFH*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Other_Higgs.root '+input_dir+'ggHtt*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/singletop.root '+input_dir+'st_schan*.root '+input_dir+'st_tchan*.root '+input_dir+'Wt_DR*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/ttbar.root '+input_dir+'ttbar_nonallhad_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/W_EWK.root '+input_dir+'W_EWK*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Wjets.root '+input_dir+'Sh_2211_Wenu*.root '+input_dir+'Sh_2211_Wmunu*.root '+input_dir+'Sh_2211_Wtaunu*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/VV_EWK.root '+input_dir+'VV_EWK*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/VV_QCD.root '+input_dir+'VV_QCD*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Signal_MG.root '+input_dir+'VJJ*.root')
print("Merging Z prime samples...")
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp200.root '+input_dir+'Zp200_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp250.root '+input_dir+'Zp250_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp300.root '+input_dir+'Zp300_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp350.root '+input_dir+'Zp350_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp400.root '+input_dir+'Zp400_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp450.root '+input_dir+'Zp450_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp500.root '+input_dir+'Zp500_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp550.root '+input_dir+'Zp550_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp600.root '+input_dir+'Zp600_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp650.root '+input_dir+'Zp650_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp700.root '+input_dir+'Zp700_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp750.root '+input_dir+'Zp750_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp800.root '+input_dir+'Zp800_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp850.root '+input_dir+'Zp850_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp900.root '+input_dir+'Zp900_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp950.root '+input_dir+'Zp950_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp1000.root '+input_dir+'Zp1000_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp1200.root '+input_dir+'Zp1200_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp1400.root '+input_dir+'Zp1400_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp1600.root '+input_dir+'Zp1600_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp1800.root '+input_dir+'Zp1800_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp2000.root '+input_dir+'Zp2000_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp2500.root '+input_dir+'Zp2500_*.root')
os.system('hadd -j 4 -f -v 0 '+output_dir+'/Zp3000.root '+input_dir+'Zp3000_*.root')
