// Class: ReadBDT-0.3_fold6
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold6
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.30/04       [400900]
Creator        : b78499db
Date           : Thu Mar 21 15:54:54 2024
Host           : Darwin Sonoma-arm64.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:43:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis
Training events: 35312
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.003479004,8696.23632812]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.00020766258,8.59782600403]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [1.25554126264e-18,0.149860098958]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [9.20502588997e-06,0.499961167574]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.39996659756]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000704350823071,129.481124878]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [84,1159527808]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold6Node

#ifndef BDT-0.3_fold6Node__def
#define BDT-0.3_fold6Node__def

class BDT-0.3_fold6Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold6Node ( BDT-0.3_fold6Node* left,BDT-0.3_fold6Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold6Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold6Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold6Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold6Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold6Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold6Node::~BDT-0.3_fold6Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold6Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold6Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold6 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold6( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold6" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold6() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold6Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold6::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold6Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold6Node*)current->GetRight();
         else current=(BDT-0.3_fold6Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold6::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50394,0.000788014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744185,0.0488369) , 
0, 1447.17, 1, 0, 0.597057,0.0970572) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377568,-0.0244863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163841,-0.0672317) , 
2, 0.0259608, 1, 0, 0.251886,-0.248114) , 
5, 12.9116, 1, 0, 0.499387,-0.000613464)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509516,0.00182445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.766122,0.0492693) , 
0, 1292.24, 1, 0, 0.626532,0.117078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201056,-0.0564128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416601,-0.0146425) , 
0, 1289.05, 1, 0, 0.291499,-0.194026) , 
5, 9.48977, 1, 0, 0.496876,-0.00331702)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653826,0.0281092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396823,-0.0213016) , 
2, 0.0480641, 1, 0, 0.584639,0.0737163) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.144275,-0.0620362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427969,-0.00899008) , 
0, 1729.45, 1, 0, 0.193941,-0.261102) , 
5, 15.8152, 1, 0, 0.50195,0.00285385)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665015,0.0275953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415873,-0.0220567) , 
3, 0.296285, 1, 0, 0.613027,0.0856269) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385092,-0.0159596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.162423,-0.0559017) , 
2, 0.0222015, 1, 0, 0.249988,-0.197299) , 
5, 10.8708, 1, 0, 0.485653,-0.0136387)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75768,0.0429973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541485,0.00181583) , 
3, 0.111116, 1, 0, 0.618596,0.0816252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202577,-0.0455436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462959,0.000396478) , 
0, 1417.06, 1, 0, 0.289118,-0.146923) , 
5, 10.0407, 1, 0, 0.494078,-0.00474896)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740443,0.0375326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403779,-0.022132) , 
3, 0.296264, 1, 0, 0.662718,0.116607) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294616,-0.0309999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56777,0.0145732) , 
1, 5.10242, 1, 0, 0.355379,-0.100849) , 
5, 6.32623, 1, 0, 0.492245,-0.0040103)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667172,0.02742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236983,-0.0366182) , 
5, 21.6679, 1, 0, 0.622305,0.101859) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465517,-0.00995567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116919,-0.0538319) , 
5, 15.4528, 1, 0, 0.374407,-0.101152) , 
2, 0.0259017, 1, 0, 0.503838,0.00484316)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33974,-0.0345091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.657531,0.0232059) , 
1, 3.3036, 1, 0, 0.612379,0.0730979) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31989,-0.0199573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125651,-0.0494659) , 
2, 0.0221838, 1, 0, 0.19819,-0.176047) , 
5, 14.3874, 1, 0, 0.50624,0.00925219)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686887,0.0284392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396329,-0.0177351) , 
3, 0.290071, 1, 0, 0.621169,0.0862919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453676,-0.00453736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230497,-0.0429858) , 
3, 0.216044, 1, 0, 0.361909,-0.0963698) , 
2, 0.0277478, 1, 0, 0.502292,0.00253683)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482645,-0.00592603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121758,-0.0469883) , 
5, 15.7977, 1, 0, 0.386587,-0.0759009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695514,0.0281784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219581,-0.0356475) , 
5, 23.7214, 1, 0, 0.649438,0.105512) , 
0, 1325.94, 1, 0, 0.502439,0.00405664)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452941,-0.0088407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707495,0.0305373) , 
0, 982.854, 1, 0, 0.643912,0.0982696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523501,-0.00116255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159829,-0.0392965) , 
5, 11.192, 1, 0, 0.379169,-0.0712286) , 
2, 0.0258979, 1, 0, 0.515254,0.0158978)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701508,0.0260847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402721,-0.0188113) , 
3, 0.296224, 1, 0, 0.638207,0.0774284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477029,-0.00624929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0973785,-0.0472967) , 
5, 17.5852, 1, 0, 0.39241,-0.0663076) , 
2, 0.0203514, 1, 0, 0.501941,-0.00225636)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508875,-0.00479067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188528,-0.0381991) , 
5, 7.9964, 1, 0, 0.342736,-0.0981725) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696137,0.023041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281629,-0.0197261) , 
5, 14.2341, 1, 0, 0.5951,0.060813) , 
0, 1060.46, 1, 0, 0.497462,-0.000697475)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541555,0.00699265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333356,-0.0245437) , 
3, 0.172832, 1, 0, 0.434409,-0.0427253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.81481,0.0406696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319408,-0.0165407) , 
5, 14.2348, 1, 0, 0.723083,0.137825) , 
1, 5.17702, 1, 0, 0.501889,-0.000519981)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656745,0.0222429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324989,-0.0267943) , 
2, 0.0831891, 1, 0, 0.618678,0.0766977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337601,-0.0206961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630589,0.0139571) , 
0, 1530.16, 1, 0, 0.419835,-0.0500965) , 
3, 0.154319, 1, 0, 0.509789,0.00726359)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675908,0.017985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369413,-0.0396663) , 
4, 1.04697, 1, 0, 0.637435,0.0496767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284121,-0.018574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12507,-0.0653355) , 
4, 0.590139, 1, 0, 0.270323,-0.0999601) , 
5, 9.59185, 1, 0, 0.492525,-0.00938913)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424679,-0.0206287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.705787,0.0189197) , 
1, 3.45422, 1, 0, 0.656521,0.0539899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381603,-0.00731612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219901,-0.0565383) , 
4, 0.629558, 1, 0, 0.357389,-0.0670104) , 
5, 6.39606, 1, 0, 0.492311,-0.0124339)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62734,0.0148038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189361,-0.0265805) , 
5, 20.5594, 1, 0, 0.575215,0.0472865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222945,-0.0347193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431463,-0.00884437) , 
1, 4.24584, 1, 0, 0.314319,-0.10517) , 
3, 0.296262, 1, 0, 0.516477,0.0129623)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773557,0.0282642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583527,0.00286601) , 
3, 0.104931, 1, 0, 0.649247,0.0524905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295343,-0.0118918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146487,-0.0540426) , 
4, 0.490399, 1, 0, 0.271512,-0.0811344) , 
5, 9.59185, 1, 0, 0.498765,-0.00074314)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664536,0.0147998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386143,-0.0360704) , 
4, 1.0248, 1, 0, 0.628083,0.0369513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293541,-0.0128642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0910997,-0.0456185) , 
5, 27.257, 1, 0, 0.24632,-0.0822058) , 
5, 11.1916, 1, 0, 0.495743,-0.00435505)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732772,0.0284046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505601,0.00363365) , 
3, 0.253066, 1, 0, 0.664663,0.0929122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341797,-0.0187355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606423,0.0105487) , 
0, 1447.25, 1, 0, 0.425864,-0.0414442) , 
2, 0.0147889, 1, 0, 0.503403,0.00218158)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443442,-0.00641876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.703718,0.0210713) , 
0, 1044.39, 1, 0, 0.617472,0.0521049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3759,-0.00426447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330693,-0.0333855) , 
4, 0.886296, 1, 0, 0.364925,-0.0515912) , 
2, 0.0277297, 1, 0, 0.498285,0.00316672)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8229,0.0377934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441408,-0.013878) , 
3, 0.277739, 1, 0, 0.7295,0.107872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44706,-0.00407198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244426,-0.0497123) , 
4, 0.886141, 1, 0, 0.428161,-0.0372777) , 
5, 2.82357, 1, 0, 0.488838,-0.00805063)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587756,0.00644272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140381,-0.0333915) , 
5, 20.7828, 1, 0, 0.526743,0.00776933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297815,-0.0206016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191871,-0.044316) , 
3, 0.413102, 1, 0, 0.224255,-0.161998) , 
3, 0.382694, 1, 0, 0.495596,-0.00971132)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641375,0.0132821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243032,-0.0360511) , 
3, 0.401178, 1, 0, 0.607295,0.0392676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358878,-0.0109847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267972,-0.0358159) , 
4, 1.04451, 1, 0, 0.346645,-0.0622436) , 
2, 0.029602, 1, 0, 0.493604,-0.00500964)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599288,0.0077754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.856405,0.0431915) , 
0, 2319.63, 1, 0, 0.640211,0.0572379) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.055906,-0.0514422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456189,-0.0021844) , 
4, 0.0769875, 1, 0, 0.3963,-0.0337695) , 
2, 0.0221982, 1, 0, 0.512127,0.00944751)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295146,-0.0237373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504496,0.000216072) , 
0, 1189.38, 1, 0, 0.342167,-0.0780502) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667001,0.0157192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185807,-0.0228793) , 
5, 17.3974, 1, 0, 0.579483,0.0411228) , 
1, 4.01869, 1, 0, 0.492717,-0.00244875)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296904,-0.012091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321678,-0.0322545) , 
4, 0.669394, 1, 0, 0.307372,-0.0915755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608276,0.0109786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283954,-0.0246561) , 
2, 0.0795554, 1, 0, 0.56372,0.0263472) , 
1, 3.55451, 1, 0, 0.50935,0.00133644)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510903,-0.00141771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201275,-0.024314) , 
5, 7.90028, 1, 0, 0.349002,-0.0520321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652274,0.0186233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367316,-0.0189783) , 
3, 0.339485, 1, 0, 0.613603,0.0565748) , 
0, 1044.35, 1, 0, 0.515625,0.0163592)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6218,0.00746253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184662,-0.021126) , 
5, 17.4691, 1, 0, 0.543845,0.0132527) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242905,-0.0155022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266121,-0.0365044) , 
4, 0.748071, 1, 0, 0.251795,-0.10256) , 
3, 0.339483, 1, 0, 0.498043,-0.00491022)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784909,0.023795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509444,-0.00026844) , 
5, 5.73784, 1, 0, 0.636599,0.0431191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489935,0.0037984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301225,-0.0197094) , 
3, 0.123579, 1, 0, 0.367276,-0.0471913) , 
2, 0.0240241, 1, 0, 0.503956,-0.00135921)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414061,-0.00613491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215252,-0.0432386) , 
4, 1.04451, 1, 0, 0.39411,-0.042323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753086,0.0218886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480331,-0.00110544) , 
2, 0.0369509, 1, 0, 0.67015,0.060132) , 
0, 1408.12, 1, 0, 0.503954,-0.00155332)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737123,0.0192331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417963,-0.00631315) , 
5, 5.48228, 1, 0, 0.54761,0.0171403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212313,-0.0205428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239645,-0.0369756) , 
4, 0.68864, 1, 0, 0.223718,-0.113857) , 
3, 0.339483, 1, 0, 0.498374,-0.00277293)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546801,0.00320147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277918,-0.017939) , 
5, 3.1995, 1, 0, 0.327918,-0.0554981) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609081,0.00972584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145276,-0.0265752) , 
5, 23.7223, 1, 0, 0.564406,0.0285406) , 
0, 946.207, 1, 0, 0.502908,0.00668652)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393443,-0.00837008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665802,0.0128408) , 
0, 1060.46, 1, 0, 0.570343,0.0216366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310505,-0.00994664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246852,-0.0379865) , 
4, 0.906132, 1, 0, 0.294327,-0.0712421) , 
2, 0.0518035, 1, 0, 0.499542,-0.00218771)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364719,-0.0130388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655014,0.0135628) , 
0, 905.238, 1, 0, 0.603579,0.03554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352896,-0.00507791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278661,-0.0324009) , 
4, 0.906068, 1, 0, 0.334282,-0.0503066) , 
2, 0.0425466, 1, 0, 0.516924,0.00791586)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269209,-0.0331057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222184,-0.00999483) , 
3, 0.320916, 1, 0, 0.255376,-0.110716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569393,0.00527661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271601,-0.0204331) , 
3, 0.327104, 1, 0, 0.52114,0.00450165) , 
1, 3.22272, 1, 0, 0.490299,-0.00886908)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770893,0.03008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664083,-0.000535841) , 
5, 1.16497, 1, 0, 0.735161,0.0825662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469804,0.000223984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459241,-0.0201413) , 
4, 0.847183, 1, 0, 0.467669,-0.0161196) , 
5, 1.59923, 1, 0, 0.497483,-0.00512018)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.849429,0.0380899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599117,0.00595196) , 
5, 1.43765, 1, 0, 0.628472,0.0388922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465186,0.00544533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304079,-0.0139644) , 
3, 0.0802484, 1, 0, 0.345489,-0.0356181) , 
2, 0.031427, 1, 0, 0.506852,0.00686921)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20035,-0.0157972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298074,-0.0271343) , 
4, 0.452492, 1, 0, 0.261957,-0.0953675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732516,0.0176509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423586,-0.00131287) , 
5, 5.37637, 1, 0, 0.543216,0.0242224) , 
1, 3.26286, 1, 0, 0.506588,0.00864824)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599259,0.00267626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227373,-0.0146216) , 
5, 11.1924, 1, 0, 0.467427,-0.0111733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.987987,0.0627388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.65053,0.00820729) , 
5, 4.32746, 1, 0, 0.778783,0.0969934) , 
1, 5.90999, 1, 0, 0.498129,-0.000507249)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291656,-0.026466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635167,0.00967477) , 
1, 3.30344, 1, 0, 0.596987,0.0212889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717232,0.0204787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360909,-0.0136393) , 
5, 1.59923, 1, 0, 0.394063,-0.0418137) , 
3, 0.16664, 1, 0, 0.494096,-0.0107066)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331365,-0.00229094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725167,0.0233676) , 
4, 0.195588, 1, 0, 0.655833,0.0753092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431346,-0.00552326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.81849,0.0314538) , 
0, 2630.38, 1, 0, 0.458247,-0.0122847) , 
3, 0.0740762, 1, 0, 0.506493,0.00910359)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675999,0.0155946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482784,0.00156513) , 
3, 0.104931, 1, 0, 0.548076,0.0250623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0233928,-0.051677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.161471,-0.0197156) , 
4, -0.00898997, 1, 0, 0.0978263,-0.0942381) , 
5, 26.885, 1, 0, 0.511714,0.0154278)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67884,0.0183095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271938,-0.00420161) , 
5, 11.4847, 1, 0, 0.461283,0.0281907) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659483,0.00254158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276998,-0.0440939) , 
5, 5.38674, 1, 0, 0.576938,-0.0314187) , 
4, 0.688894, 1, 0, 0.508584,0.00381134)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636369,0.0108978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19961,-0.0150676) , 
5, 14.366, 1, 0, 0.496563,0.0149786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639625,-0.004183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310657,-0.03808) , 
5, 2.58968, 1, 0, 0.514207,-0.0686584) , 
4, 0.865456, 1, 0, 0.500831,-0.0052505)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737282,0.0200614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602287,-0.00152563) , 
4, 0.772958, 1, 0, 0.658809,0.0303527) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322544,0.00373892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341161,-0.0207851) , 
4, 0.373047, 1, 0, 0.329692,-0.0245436) , 
5, 7.90761, 1, 0, 0.495746,0.00315408)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555207,0.00334493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29209,-0.0123849) , 
3, 0.308606, 1, 0, 0.499455,0.000166766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476212,-0.0241253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405338,0.0118684) , 
4, 1.20928, 1, 0, 0.459937,-0.0658937) , 
4, 0.945636, 1, 0, 0.492602,-0.0112892)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685331,0.0282419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587322,-0.00252304) , 
4, 0.474079, 1, 0, 0.60946,0.0191748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21258,-0.00519783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145824,-0.0331688) , 
4, 0.234585, 1, 0, 0.192816,-0.045982) , 
5, 14.3449, 1, 0, 0.508499,0.00338603)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40813,0.00267596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418036,-0.0163782) , 
1, 4.43685, 1, 0, 0.410925,-0.0110614) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736543,0.0148292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178463,-0.0259046) , 
5, 22.3852, 1, 0, 0.684693,0.0416142) , 
0, 1436.71, 1, 0, 0.512437,0.00847048)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605787,0.0101177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534657,-0.00787743) , 
4, 0.845996, 1, 0, 0.58339,0.018715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.154841,-0.0137332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.112519,-0.0343665) , 
4, 0.13577, 1, 0, 0.14023,-0.0634336) , 
5, 18.3508, 1, 0, 0.502439,0.00370907)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363817,-0.0128076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.659515,0.0128852) , 
0, 914.538, 1, 0, 0.596883,0.0285937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283847,-0.00605792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0685437,-0.0350024) , 
2, 0.0186967, 1, 0, 0.131329,-0.0694688) , 
5, 17.5852, 1, 0, 0.512156,0.0107472)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147016,-0.0256152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413685,0.0131459) , 
4, -0.0356686, 1, 0, 0.361302,0.0245261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432856,0.00343854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56664,-0.0149694) , 
1, 3.5478, 1, 0, 0.539551,-0.0439502) , 
4, 0.353368, 1, 0, 0.483575,-0.022446)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693002,0.00234745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752516,0.0266208) , 
5, 1.69795, 1, 0, 0.722261,0.0562877) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432635,0.0061329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474623,-0.0162822) , 
4, 0.590318, 1, 0, 0.447512,-0.00861369) , 
5, 3.19857, 1, 0, 0.509564,0.00604434)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.87799,0.0385354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62565,0.0037012) , 
2, 0.0166016, 1, 0, 0.744192,0.0715835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479348,-0.000767773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364917,-0.0263452) , 
4, 0.88638, 1, 0, 0.46245,-0.0178448) , 
5, 1.59923, 1, 0, 0.490861,-0.00882702)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291157,-0.00604277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346072,-0.0238902) , 
4, 0.728745, 1, 0, 0.309191,-0.048282) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662717,0.0121846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435232,-0.00598722) , 
3, 0.240739, 1, 0, 0.592232,0.0241238) , 
0, 982.863, 1, 0, 0.505178,0.00185435)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620098,0.00599135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172621,-0.012697) , 
5, 15.9922, 1, 0, 0.505889,0.00847514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440313,-0.0314975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356008,-0.00787261) , 
4, 1.13887, 1, 0, 0.404109,-0.0859587) , 
4, 0.985185, 1, 0, 0.492568,-0.00388463)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35401,-0.00724667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336383,-0.0285029) , 
1, 3.96139, 1, 0, 0.351248,-0.0410161) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548984,0.00986797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651457,-0.00730474) , 
1, 5.33536, 1, 0, 0.584371,0.0164145) , 
1, 4.11857, 1, 0, 0.493474,-0.0059782)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605656,0.00472827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.966296,0.0537947) , 
1, 6.28065, 1, 0, 0.627498,0.0266563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273549,-0.0147753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572114,0.0105763) , 
0, 1491.18, 1, 0, 0.349962,-0.0294096) , 
2, 0.0277297, 1, 0, 0.498193,0.000535094)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695261,0.00735297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418025,-0.00719598) , 
5, 4.79709, 1, 0, 0.516117,-0.00758127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253045,-0.0336321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157054,-0.0208321) , 
5, 7.11083, 1, 0, 0.203799,-0.107019) , 
3, 0.407379, 1, 0, 0.494144,-0.014577)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83822,0.0316882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.658511,0.0056841) , 
3, 0.0308064, 1, 0, 0.675725,0.0311676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405662,0.000507331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257472,-0.0349238) , 
4, 0.68877, 1, 0, 0.385813,-0.0161733) , 
5, 5.64644, 1, 0, 0.50264,0.00290393)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718033,0.0158016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576733,-0.00486924) , 
4, 0.808044, 1, 0, 0.64535,0.0204264) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299511,-0.00369468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327327,-0.0198754) , 
4, 0.372826, 1, 0, 0.309158,-0.0355606) , 
5, 8.38968, 1, 0, 0.492202,-0.00507779)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514606,-0.00506108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784668,0.0196345) , 
1, 4.11857, 1, 0, 0.693886,0.0395982) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412284,-0.00079104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267755,-0.0396881) , 
4, 0.728397, 1, 0, 0.392559,-0.0227933) , 
5, 4.79628, 1, 0, 0.495846,-0.0014071)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708998,0.00621795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405694,-0.0112004) , 
3, 0.296268, 1, 0, 0.64671,0.00852062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272708,-0.0115503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.7048,0.022557) , 
0, 2454.68, 1, 0, 0.302699,-0.0313646) , 
5, 8.6064, 1, 0, 0.496434,-0.00890264)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775556,0.0157719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468349,-0.00813378) , 
2, 0.0406532, 1, 0, 0.699721,0.0319783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418585,-0.000839876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467597,-0.0150582) , 
4, 0.689362, 1, 0, 0.432466,-0.018779) , 
5, 2.82439, 1, 0, 0.484388,-0.00891794)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2365,-0.00891539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315845,-0.0225118) , 
4, 0.491781, 1, 0, 0.280397,-0.0656247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471973,0.0264387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53814,0.000409976) , 
1, 3.57973, 1, 0, 0.53209,0.010298) , 
1, 3.26258, 1, 0, 0.501987,0.00121729)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653113,0.0389129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68739,0.0012374) , 
4, 0.359474, 1, 0, 0.676899,0.0510671) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623684,0.00350873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261991,-0.00964132) , 
5, 9.59263, 1, 0, 0.476376,-0.00526556) , 
2, 0.0074005, 1, 0, 0.507151,0.00338005)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617381,0.0166575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737647,-0.000191983) , 
0, 1166.85, 1, 0, 0.688251,0.0292335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412636,0.00288234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359499,-0.025305) , 
4, 0.649392, 1, 0, 0.401745,-0.0116516) , 
5, 4.74566, 1, 0, 0.496103,0.00181357)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196808,-0.0291821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623856,0.0135409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471895,0.000200592) , 
3, 0.0864271, 1, 0, 0.515455,0.0146893) , 
1, 2.48186, 1, 0, 0.504348,0.010402)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54813,-0.021098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652586,0.00849688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430337,-0.00551612) , 
2, 0.0127209, 1, 0, 0.484301,-0.00776737) , 
2, 0.0036997, 1, 0, 0.487994,-0.0118009)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342354,0.010128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512212,0.0420136) , 
1, 2.43056, 1, 0, 0.424596,0.0983785) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537751,0.00342464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0498388,-0.0453349) , 
5, 33.2103, 1, 0, 0.517234,0.00730972) , 
1, 2.72686, 1, 0, 0.511418,0.0130273)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503175,0.014673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149046,-0.00818011) , 
5, 23.0628, 1, 0, 0.389426,0.0313616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66339,0.00352549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381085,-0.0202587) , 
5, 5.88058, 1, 0, 0.55101,-0.0238174) , 
4, 0.372877, 1, 0, 0.498012,-0.00571912)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727076,0.0211835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304324,0.00608794) , 
5, 11.0802, 1, 0, 0.462132,0.0448542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645189,0.00340825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235375,-0.0342029) , 
5, 7.09185, 1, 0, 0.587809,-0.00545726) , 
4, 0.609868, 1, 0, 0.52236,0.0207438)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511762,-0.00213986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239221,-0.017988) , 
3, 0.327128, 1, 0, 0.460361,-0.0190708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.881459,0.0300273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528732,-0.0102254) , 
2, 0.0277132, 1, 0, 0.76469,0.044011) , 
0, 2313.04, 1, 0, 0.496327,-0.0116158)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741029,0.00370364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419998,-0.0106945) , 
5, 6.32879, 1, 0, 0.580228,-0.0148693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379692,0.0111103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322268,-0.0125461) , 
4, 0.906156, 1, 0, 0.366067,0.0182986) , 
2, 0.0351109, 1, 0, 0.497973,-0.00213013)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771288,0.0239992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625068,0.0018197) , 
4, 0.610948, 1, 0, 0.664197,0.0293929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319663,0.00449186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247493,-0.0240059) , 
4, 0.372201, 1, 0, 0.300165,-0.0127657) , 
5, 9.59185, 1, 0, 0.512727,0.0118511)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529694,0.00138108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42643,0.0158119) , 
3, 0.203749, 1, 0, 0.487755,0.0261899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662321,0.00104468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294625,-0.0272947) , 
5, 4.04023, 1, 0, 0.558563,-0.0258845) , 
4, 0.767867, 1, 0, 0.510685,0.00932615)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233008,-0.0345511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2583,0.00132382) , 
3, 0.277747, 1, 0, 0.243743,-0.0738311) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566987,0.00565764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263523,-0.013447) , 
2, 0.0795436, 1, 0, 0.524464,0.0115535) , 
1, 2.96913, 1, 0, 0.49976,0.00403953)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825313,0.0286418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464866,0.000722109) , 
5, 2.98471, 1, 0, 0.490509,0.00962382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547433,-0.0305042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474213,-0.00436491) , 
4, 0.958933, 1, 0, 0.50509,-0.0567168) , 
4, 0.866772, 1, 0, 0.49408,-0.00662352)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313872,-0.0256728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643266,0.00627071) , 
1, 3.30692, 1, 0, 0.608748,0.00844599) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520287,-0.015024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264631,-0.000178298) , 
5, 9.59263, 1, 0, 0.411889,-0.0349635) , 
3, 0.117269, 1, 0, 0.483273,-0.0192226)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649432,-0.0163498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649463,0.00587493) , 
2, 0.00369724, 1, 0, 0.649461,0.0170088) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285681,-0.00222723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260578,-0.0225836) , 
4, 0.35303, 1, 0, 0.277399,-0.0326535) , 
5, 9.48977, 1, 0, 0.50109,-0.00279552)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644071,0.0147353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221767,-0.000999436) , 
5, 14.4917, 1, 0, 0.387438,0.0215569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696845,0.00664886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475592,-0.00991681) , 
3, 0.123445, 1, 0, 0.564045,-0.0140859) , 
4, 0.432344, 1, 0, 0.498934,-0.000945186)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393063,0.0019391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481262,-0.0111514) , 
1, 4.44485, 1, 0, 0.424686,-0.0106042) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753792,-0.00172914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723825,0.0205865) , 
3, 0.0616382, 1, 0, 0.730117,0.0565019) , 
0, 1731.03, 1, 0, 0.50282,0.00656252)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591517,0.00319168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492997,-0.0239328) , 
3, 0.015071, 1, 0, 0.533724,-0.047395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610201,0.00627669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201615,-0.00519237) , 
5, 14.3882, 1, 0, 0.507383,0.0144379) , 
3, 0.0370427, 1, 0, 0.510526,0.00705976)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399106,0.0294175) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668232,0.00597661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31174,-0.005245) , 
5, 8.39046, 1, 0, 0.505806,0.00397259) , 
1, 2.6231, 1, 0, 0.501245,0.00823278)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2703,-0.0156571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520687,0.001694) , 
1, 3.2436, 1, 0, 0.488518,-0.00186246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861398,0.0376467) , 
0, 3000.83, 1, 0, 0.510097,0.00516237)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529112,-0.0239554) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676084,0.0122561) , 
2, 0.00255402, 1, 0, 0.661822,0.0312174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391758,-0.0022799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456499,-0.0147346) , 
4, 0.74804, 1, 0, 0.414236,-0.0248381) , 
2, 0.0147804, 1, 0, 0.498937,-0.00566106)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598009,0.00405967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361653,-0.00753029) , 
2, 0.036997, 1, 0, 0.514962,-0.000154535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422399,0.0253076) , 
4, 1.10373, 1, 0, 0.509524,0.00484296)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742158,0.0133038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490009,-0.00074483) , 
5, 1.59923, 1, 0, 0.513607,0.00196438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233048,-0.0259122) , 
2, 0.118408, 1, 0, 0.502056,-0.00173238)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460238,-0.00308729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468675,-0.018442) , 
4, 0.886428, 1, 0, 0.462077,-0.0235619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780699,0.0317742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802987,-0.00175666) , 
4, 0.602125, 1, 0, 0.792641,0.0471349) , 
1, 5.93106, 1, 0, 0.49321,-0.0169035)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343796,-0.00899166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611565,0.0069287) , 
0, 914.688, 1, 0, 0.553761,0.0121198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269134,-0.00492333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389038,-0.0376236) , 
1, 5.0601, 1, 0, 0.290413,-0.0418213) , 
3, 0.296277, 1, 0, 0.492502,-0.000427809)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700881,0.0334632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.783514,0.0090249) , 
0, 1079.07, 1, 0, 0.758489,0.0650814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470965,-0.00343902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335837,0.0357985) , 
3, 0.456757, 1, 0, 0.465844,-0.00793223) , 
5, 1.58292, 1, 0, 0.495686,-0.000486826)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697341,0.00202349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380982,-0.0114822) , 
5, 7.17473, 1, 0, 0.541442,-0.0178773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338775,0.0226058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377964,-0.00668079) , 
0, 1242.42, 1, 0, 0.353595,0.0350624) , 
2, 0.0573081, 1, 0, 0.499657,-0.00610136)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461877,0.00101825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651704,-0.0126166) , 
1, 5.33984, 1, 0, 0.501769,-0.00586158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217089,-0.02573) , 
2, 0.111007, 1, 0, 0.485699,-0.0105427)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685326,0.00884631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351714,-0.00443603) , 
5, 7.05912, 1, 0, 0.514455,0.00804443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209298,-0.0235598) , 
3, 0.425865, 1, 0, 0.49769,0.00302097)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650313,0.00984797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404863,-0.00507357) , 
2, 0.0110877, 1, 0, 0.464031,-0.00502858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767407,0.0068673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.830041,0.0527559) , 
3, 0.186353, 1, 0, 0.783995,0.064723) , 
1, 5.69038, 1, 0, 0.502886,0.00344172)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311472,-0.0157083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244371,0.0220983) , 
3, 0.388677, 1, 0, 0.301027,-0.0392112) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572034,0.00737803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523999,-0.0130952) , 
4, 0.926331, 1, 0, 0.56302,0.0129202) , 
0, 914.533, 1, 0, 0.504368,0.00124974)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217489,-0.0135002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611965,0.00850652) , 
4, 0.0962975, 1, 0, 0.556188,0.0212661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270823,0.0117243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223798,-0.0285029) , 
1, 3.69899, 1, 0, 0.240823,-0.0542413) , 
3, 0.364172, 1, 0, 0.513518,0.0110497)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383931,-0.00717287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357986,0.0368548) , 
2, 0.101757, 1, 0, 0.381359,-0.0134297) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664273,0.0122011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537145,-0.0189061) , 
4, 0.96553, 1, 0, 0.649497,0.0302958) , 
0, 1243.6, 1, 0, 0.508116,0.00724063)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542827,-0.00426672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375046,0.00856379) , 
2, 0.0609617, 1, 0, 0.507495,-0.00570002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403024,0.030721) , 
4, 1.16294, 1, 0, 0.502924,-0.00113292)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521686,-0.000238539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452335,0.0244959) , 
4, 1.12343, 1, 0, 0.517667,0.00402555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204694,-0.0277396) , 
2, 0.111007, 1, 0, 0.500709,-0.00115421)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546375,-0.00518456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42295,-0.0259584) , 
4, 0.985185, 1, 0, 0.531121,-0.0276246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193378,-0.0133224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392577,0.00988752) , 
0, 860.067, 1, 0, 0.357012,0.0222353) , 
3, 0.271588, 1, 0, 0.48564,-0.0146002)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671954,0.0362299) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581326,0.00317609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304868,-0.00869411) , 
2, 0.044323, 1, 0, 0.492062,-0.00201545) , 
3, 0.0185248, 1, 0, 0.502461,0.00457316)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242844,-0.0112527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0221464,-0.0478903) , 
5, 27.9382, 1, 0, 0.138982,-0.0613974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43652,0.00614789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553384,-0.00508979) , 
4, 0.357096, 1, 0, 0.52546,-0.00909822) , 
4, 0.0374101, 1, 0, 0.489458,-0.0139701)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711183,0.0313409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789761,0.00958527) , 
0, 1161.87, 1, 0, 0.76029,0.0693801) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471191,-0.00425351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351905,0.0226408) , 
2, 0.109157, 1, 0, 0.463064,-0.00944435) , 
5, 1.43602, 1, 0, 0.490869,-0.00207048)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472905,0.027863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610088,-0.00628963) , 
4, 0.0774875, 1, 0, 0.597673,-0.0117288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0702253,-0.0280718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439784,0.0113611) , 
4, 0.0172675, 1, 0, 0.389851,0.0296383) , 
2, 0.0333022, 1, 0, 0.51511,0.00470534)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508987,-0.00540656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.805494,0.0209489) , 
1, 4.18041, 1, 0, 0.688795,0.0324255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558832,0.0171459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328372,-0.00748756) , 
2, 0.00739204, 1, 0, 0.358367,-0.0137775) , 
5, 6.32623, 1, 0, 0.50133,0.00621268)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490808,0.0035094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67614,-0.0295279) , 
0, 2765.53, 1, 0, 0.497822,0.00890616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.899353,0.0410095) , 
1, 6.48007, 1, 0, 0.512551,0.0127806)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527512,-0.00582879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391076,0.00526233) , 
3, 0.185242, 1, 0, 0.463636,-0.00239623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736842,-0.0146175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426445,-0.0365402) , 
2, 0.0404214, 1, 0, 0.653995,-0.0690853) , 
1, 5.5841, 1, 0, 0.493346,-0.0128046)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543632,0.0211581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200833,-0.00485904) , 
2, 0.0313911, 1, 0, 0.379844,0.034536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519659,-0.000831474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688545,-0.0260491) , 
1, 5.44971, 1, 0, 0.552177,-0.0180624) , 
4, 0.353369, 1, 0, 0.497731,-0.0014446)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718394,0.0126194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3705,-0.0125442) , 
3, 0.339413, 1, 0, 0.66512,0.0289949) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440192,-0.00151398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447695,-0.0146489) , 
4, 0.846792, 1, 0, 0.4422,-0.0187758) , 
2, 0.0111007, 1, 0, 0.496873,-0.00705977)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75428,0.00984298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522182,-0.00176383) , 
3, 0.191353, 1, 0, 0.658328,0.0167832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30766,-0.000709545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177863,-0.0314041) , 
4, 0.470853, 1, 0, 0.285762,-0.0198817) , 
5, 9.59185, 1, 0, 0.511093,0.00229357)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5336,-0.026049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504591,-0.00093716) , 
3, 0.0162425, 1, 0, 0.506017,-0.00731825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359223,0.026025) , 
3, 0.438193, 1, 0, 0.49972,-0.00327567)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445714,0.00439667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0229321,-0.0483177) , 
5, 30.9052, 1, 0, 0.420905,0.0099788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465362,-0.0192079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680287,0.00196133) , 
1, 5.17022, 1, 0, 0.59191,-0.0246873) , 
1, 4.58414, 1, 0, 0.498432,-0.00573744)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.249681,-0.0272628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384704,0.0121751) , 
0, 779.056, 1, 0, 0.370187,0.0277567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722793,0.00409214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478362,-0.00971267) , 
2, 0.0147804, 1, 0, 0.56913,-0.0172019) , 
0, 1044.31, 1, 0, 0.499593,-0.00148734)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453959,0.00521446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583381,-0.00437785) , 
4, 0.609338, 1, 0, 0.515847,0.00182839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390648,0.0281784) , 
2, 0.105442, 1, 0, 0.508095,0.00741063)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466551,-0.000361628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201197,0.0382408) , 
5, 31.9725, 1, 0, 0.451451,0.00312648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790228,-0.00106437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399112,-0.030399) , 
5, 8.84512, 1, 0, 0.643996,-0.0458953) , 
1, 5.47217, 1, 0, 0.487344,-0.00601184)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405969,0.00164065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526051,0.0145079) , 
1, 4.39343, 1, 0, 0.431621,0.0160824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376634,-0.0335144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663165,-2.26298e-05) , 
0, 1259.48, 1, 0, 0.611838,-0.0227683) , 
1, 4.76958, 1, 0, 0.499106,0.00153404)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576878,-0.00182111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365477,0.00862268) , 
2, 0.0628166, 1, 0, 0.535289,0.000588352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.161109,-0.0396809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25825,-0.00524754) , 
3, 0.389322, 1, 0, 0.233482,-0.0494287) , 
3, 0.364172, 1, 0, 0.496928,-0.00576911)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525697,0.00152567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519423,0.0286113) , 
4, 1.16254, 1, 0, 0.525473,0.00894564) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332321,-0.0254667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172368,-0.002409) , 
5, 9.09561, 1, 0, 0.25889,-0.0602753) , 
2, 0.103592, 1, 0, 0.506954,0.00413718)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449212,0.000131414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603251,-0.0192779) , 
1, 5.49113, 1, 0, 0.4657,-0.00680937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826307,0.0276309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737811,-0.001887) , 
0, 3200.95, 1, 0, 0.796147,0.0535872) , 
0, 2395.3, 1, 0, 0.498885,-0.000744127)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0707767,-0.0371169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518783,0.000696608) , 
4, -0.0887266, 1, 0, 0.499321,-0.000847653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556436,-0.0244816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354426,0.000534702) , 
4, 1.06625, 1, 0, 0.46755,-0.0493561) , 
4, 0.925794, 1, 0, 0.49363,-0.00953744)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41307,0.0253749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660625,0.00463054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300889,-0.00398138) , 
5, 9.01476, 1, 0, 0.502486,0.00364063) , 
1, 2.48186, 1, 0, 0.498771,0.00746823)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27423,-0.0213978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455095,0.00933357) , 
0, 798.728, 1, 0, 0.436257,0.0228526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601406,-0.0304119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618046,-0.00417422) , 
3, 0.0493543, 1, 0, 0.615229,-0.0282999) , 
0, 1408.12, 1, 0, 0.507176,0.00258296)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513191,0.00387924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524927,-0.00874795) , 
4, 0.886766, 1, 0, 0.515829,0.00367812) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224804,0.00101284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173958,-0.0356883) , 
1, 3.7049, 1, 0, 0.193282,-0.0788224) , 
3, 0.401182, 1, 0, 0.48959,-0.00303327)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold6::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold6::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
