// Class: ReadBDT-0.3_fold2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold2
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.30/04       [400900]
Creator        : b78499db
Date           : Thu Mar 21 15:54:49 2024
Host           : Darwin Sonoma-arm64.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:43:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis
Training events: 35364
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.003479004,8696.23632812]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.00020766258,8.59782600403]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [1.25554126264e-18,0.149860098958]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [9.20502588997e-06,0.499961167574]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.39996659756]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000704350823071,129.481124878]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [84,1159527808]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold2Node

#ifndef BDT-0.3_fold2Node__def
#define BDT-0.3_fold2Node__def

class BDT-0.3_fold2Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold2Node ( BDT-0.3_fold2Node* left,BDT-0.3_fold2Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold2Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold2Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold2Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold2Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold2Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold2Node::~BDT-0.3_fold2Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold2Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold2Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold2 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold2( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold2" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold2Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold2Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold2Node*)current->GetRight();
         else current=(BDT-0.3_fold2Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold2::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540334,0.00806673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.787045,0.0574089) , 
0, 1526.16, 1, 0, 0.623554,0.123554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374804,-0.0250393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146649,-0.0706702) , 
2, 0.0277478, 1, 0, 0.252978,-0.247022) , 
5, 11.4774, 1, 0, 0.498432,-0.00156779)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710394,0.0392938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467099,-0.00864912) , 
2, 0.0314265, 1, 0, 0.618295,0.10557) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412705,-0.0151817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187255,-0.056513) , 
2, 0.0222015, 1, 0, 0.27489,-0.201456) , 
5, 11.0711, 1, 0, 0.505699,0.00490143)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513961,0.001207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.808633,0.056535) , 
0, 1927.23, 1, 0, 0.572867,0.0609248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12844,-0.0656527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411796,-0.00982186) , 
0, 1536.47, 1, 0, 0.201847,-0.253318) , 
5, 15.9859, 1, 0, 0.49145,-0.00803309)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697101,0.0336383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444843,-0.016081) , 
3, 0.296259, 1, 0, 0.64993,0.120935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.174655,-0.0546922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405879,-0.0122599) , 
0, 1140.09, 1, 0, 0.292603,-0.162391) , 
5, 9.59362, 1, 0, 0.504794,0.00585647)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703653,0.0344164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485449,-0.00740196) , 
3, 0.154328, 1, 0, 0.59359,0.0657724) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375542,-0.0146488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13633,-0.0553386) , 
2, 0.0221838, 1, 0, 0.229125,-0.19048) , 
5, 14.3435, 1, 0, 0.503927,0.0027311)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663118,0.0252262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356918,-0.0281639) , 
3, 0.296259, 1, 0, 0.596562,0.0668198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24606,-0.0312085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0725648,-0.0666469) , 
3, 0.240694, 1, 0, 0.184274,-0.20753) , 
5, 15.9859, 1, 0, 0.509579,0.00893835)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506785,-0.00631709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742652,0.0362122) , 
1, 4.19965, 1, 0, 0.647519,0.0928975) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389316,-0.00975836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174095,-0.0461657) , 
2, 0.044403, 1, 0, 0.308547,-0.110527) , 
5, 9.48899, 1, 0, 0.510642,0.0107548)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524504,-0.00343929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202875,-0.0401024) , 
5, 9.40759, 1, 0, 0.381726,-0.0924833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686163,0.0293842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420366,-0.0135273) , 
2, 0.0443522, 1, 0, 0.616892,0.0880342) , 
0, 1268.86, 1, 0, 0.494823,-0.00566864)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713931,0.0333933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449126,-0.00887427) , 
3, 0.234337, 1, 0, 0.631052,0.0967019) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469419,-0.00919065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0924455,-0.0524963) , 
5, 15.8152, 1, 0, 0.368914,-0.0936707) , 
2, 0.0259017, 1, 0, 0.503812,0.00429639)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547,0.0012227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233385,-0.0389182) , 
5, 5.69388, 1, 0, 0.352224,-0.110172) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752745,0.0375708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452285,-0.00681154) , 
2, 0.0258721, 1, 0, 0.626964,0.0904858) , 
0, 1161.33, 1, 0, 0.500126,-0.00215063)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650067,0.0205498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370537,-0.0156072) , 
2, 0.0443668, 1, 0, 0.566634,0.0466407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264551,-0.0342227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577243,0.0118762) , 
0, 1790.39, 1, 0, 0.310078,-0.129291) , 
3, 0.277746, 1, 0, 0.502346,0.00255554)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699387,0.0242826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301185,-0.0230557) , 
5, 14.2339, 1, 0, 0.616581,0.0684514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365107,-0.0136874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240822,-0.0530403) , 
4, 1.04441, 1, 0, 0.347034,-0.0916756) , 
2, 0.0314521, 1, 0, 0.501922,0.000337133)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712435,0.0266932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436378,-0.00591187) , 
2, 0.0221838, 1, 0, 0.573947,0.0482374) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317269,-0.0224393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154674,-0.06266) , 
4, 1.00463, 1, 0, 0.295255,-0.13141) , 
3, 0.29009, 1, 0, 0.507378,0.00532656)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461179,-0.00810557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693762,0.0249425) , 
1, 4.281, 1, 0, 0.590698,0.0475308) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223046,-0.0247374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111172,-0.049846) , 
5, 24.2297, 1, 0, 0.162993,-0.161837) , 
5, 17.3959, 1, 0, 0.505061,0.00561024)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65783,0.017589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391052,-0.0257473) , 
4, 1.04476, 1, 0, 0.627789,0.0595154) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414065,-0.00216348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145391,-0.0386802) , 
2, 0.0166321, 1, 0, 0.228237,-0.112991) , 
5, 12.7901, 1, 0, 0.512872,0.0099)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722122,0.0222597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434198,-0.0142011) , 
3, 0.277603, 1, 0, 0.655664,0.0629689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38483,-0.0101863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180582,-0.0628799) , 
4, 0.688583, 1, 0, 0.362365,-0.0730191) , 
5, 6.3948, 1, 0, 0.494849,-0.0115928)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508419,-0.00411305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132629,-0.0375338) , 
5, 14.3882, 1, 0, 0.4082,-0.0537702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720001,0.0250939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250996,-0.0252985) , 
5, 19.575, 1, 0, 0.660962,0.0850013) , 
0, 1408.14, 1, 0, 0.503994,-0.00117736)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508385,0.00379082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32046,-0.0220818) , 
3, 0.117275, 1, 0, 0.387143,-0.057917) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.835781,0.0410183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58627,0.0109768) , 
5, 2.74074, 1, 0, 0.638371,0.0769993) , 
0, 1244.74, 1, 0, 0.510515,0.00833686)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724903,0.0274961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567715,-0.00475344) , 
4, 0.693972, 1, 0, 0.622512,0.0298713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31283,-0.0103109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.112595,-0.0641348) , 
4, 0.530022, 1, 0, 0.286585,-0.0760531) , 
5, 9.5918, 1, 0, 0.486777,-0.0129288)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704754,0.0193281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416158,-0.0273367) , 
4, 1.04747, 1, 0, 0.665781,0.0584088) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382653,-0.00721819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132633,-0.0668958) , 
4, 0.708539, 1, 0, 0.358862,-0.0576422) , 
5, 6.3956, 1, 0, 0.492149,-0.0072443)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623308,0.014708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302152,-0.0249322) , 
2, 0.0776432, 1, 0, 0.578358,0.0410479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416877,-0.00812846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175769,-0.0397637) , 
2, 0.0314521, 1, 0, 0.304636,-0.0975861) , 
3, 0.265416, 1, 0, 0.502694,0.00272575)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387036,-0.0141167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153255,-0.0460879) , 
2, 0.0718488, 1, 0, 0.337627,-0.0906018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585167,0.0101356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30194,-0.022043) , 
3, 0.339393, 1, 0, 0.544392,0.0244522) , 
0, 914.533, 1, 0, 0.496094,-0.00242315)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392165,-0.0106367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209921,-0.0470348) , 
4, 1.04465, 1, 0, 0.376361,-0.0615116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65397,0.0178996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48257,-0.0203061) , 
4, 0.985081, 1, 0, 0.633871,0.0585466) , 
0, 1292.24, 1, 0, 0.488669,-0.00915065)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770362,0.0281112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585933,0.00247318) , 
3, 0.104935, 1, 0, 0.646514,0.0481263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308521,-0.0106587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101913,-0.0575524) , 
4, 0.590452, 1, 0, 0.287561,-0.0646883) , 
5, 9.49021, 1, 0, 0.500571,0.00225812)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555159,0.00153885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185508,-0.0238862) , 
5, 14.2339, 1, 0, 0.450941,-0.0203986) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66034,0.011046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.816145,0.0393845) , 
1, 5.56084, 1, 0, 0.755507,0.117503) , 
0, 2025.32, 1, 0, 0.498475,0.00112417)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330594,-0.0281358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593585,0.011062) , 
1, 3.24553, 1, 0, 0.559528,0.0257933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150038,-0.0317944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0250836,-0.062004) , 
5, 35.5396, 1, 0, 0.120312,-0.141536) , 
5, 21.515, 1, 0, 0.497024,0.0019809)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568017,0.00147515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868221,0.0427391) , 
0, 2316.65, 1, 0, 0.6156,0.0320996) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198875,-0.0380959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395912,-0.0102152) , 
1, 3.28504, 1, 0, 0.365527,-0.0614301) , 
2, 0.0221615, 1, 0, 0.483467,-0.0173196)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62529,0.0128842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155234,-0.0285977) , 
5, 20.9742, 1, 0, 0.567369,0.0369091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.152717,-0.0407885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322485,-0.0148753) , 
0, 907.031, 1, 0, 0.280778,-0.0891823) , 
3, 0.339462, 1, 0, 0.521487,0.0167226)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270758,-0.0109119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328314,-0.0312035) , 
4, 0.589103, 1, 0, 0.300631,-0.0950926) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597859,0.00935935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164439,-0.0240006) , 
5, 20.5595, 1, 0, 0.538915,0.0237914) , 
1, 3.36461, 1, 0, 0.500696,0.00472309)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661177,0.016891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367774,-0.0118904) , 
5, 2.87056, 1, 0, 0.421861,-0.0265091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728678,0.0210451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40647,-0.0237733) , 
3, 0.302426, 1, 0, 0.68208,0.0566938) , 
0, 1574.63, 1, 0, 0.500679,-0.00130755)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79444,0.0277668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51687,0.00159635) , 
5, 5.74048, 1, 0, 0.645252,0.0562195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371029,-0.00942422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210408,-0.0463522) , 
4, 1.04441, 1, 0, 0.347132,-0.063704) , 
2, 0.0259017, 1, 0, 0.504617,-0.000353366)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453722,0.00270096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257012,-0.0251847) , 
3, 0.0988331, 1, 0, 0.31109,-0.0713319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665735,0.0181416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502085,0.000407212) , 
3, 0.117275, 1, 0, 0.567489,0.0309468) , 
0, 914.913, 1, 0, 0.511001,0.00841352)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79437,0.0307619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617112,0.00229896) , 
4, 0.894055, 1, 0, 0.704113,0.0682138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432613,0.00128914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277897,-0.0428537) , 
4, 0.728397, 1, 0, 0.408342,-0.0240278) , 
5, 4.74485, 1, 0, 0.507689,0.00695525)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.834787,0.0335267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58473,0.000600558) , 
2, 0.0222183, 1, 0, 0.714394,0.0695012) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454067,-0.00159984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362842,-0.033333) , 
4, 0.807401, 1, 0, 0.439509,-0.0281962) , 
5, 2.86927, 1, 0, 0.499539,-0.006861)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54461,0.00896415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530615,-0.0104726) , 
4, 0.768143, 1, 0, 0.539312,0.00678407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285119,-0.0071481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0362009,-0.0497727) , 
2, 0.0188107, 1, 0, 0.118624,-0.105407) , 
5, 23.9796, 1, 0, 0.493109,-0.00553769)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30245,-0.0217759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58023,0.00950869) , 
1, 3.06858, 1, 0, 0.549388,0.0251712) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271509,-0.0181128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207605,-0.0457504) , 
4, 0.80743, 1, 0, 0.247823,-0.117852) , 
2, 0.0795436, 1, 0, 0.505491,0.0043522)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387349,-0.00976125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.631681,0.0101478) , 
0, 1044.31, 1, 0, 0.548163,0.0133262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273807,-0.0072412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286773,-0.02943) , 
4, 0.629824, 1, 0, 0.27962,-0.0733336) , 
3, 0.314805, 1, 0, 0.496969,-0.00319431)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735181,0.0180297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344543,-0.00484937) , 
5, 15.7778, 1, 0, 0.666334,0.0569467) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400309,-0.00923516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698186,0.017727) , 
1, 5.95644, 1, 0, 0.42834,-0.0275492) , 
2, 0.0129403, 1, 0, 0.496262,-0.00343477)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49691,0.0158696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560835,-0.00272409) , 
4, 0.373092, 1, 0, 0.544486,0.0082231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.164302,-0.0201243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0751301,-0.041835) , 
3, 0.166621, 1, 0, 0.114369,-0.098964) , 
5, 23.7223, 1, 0, 0.496774,-0.00366695)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705883,0.0149003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326022,-0.0220223) , 
3, 0.376489, 1, 0, 0.670775,0.0467811) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401509,0.000491227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0960117,-0.058252) , 
4, 0.748148, 1, 0, 0.376345,-0.016434) , 
5, 6.3956, 1, 0, 0.503211,0.0108046)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248811,-0.0418989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270775,-0.016179) , 
3, 0.185933, 1, 0, 0.26194,-0.110502) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656024,0.0164518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472383,-0.00459554) , 
3, 0.11729, 1, 0, 0.544091,0.014541) , 
1, 3.22199, 1, 0, 0.509442,-0.000814548)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650356,0.0280561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697411,0.00613087) , 
4, 0.512328, 1, 0, 0.676379,0.0659709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357477,-0.0136003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606885,0.00433044) , 
1, 4.85103, 1, 0, 0.440565,-0.0311311) , 
2, 0.00924323, 1, 0, 0.488005,-0.0115966)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711211,0.0130689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444253,-0.00611908) , 
2, 0.0184865, 1, 0, 0.551666,0.00544275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24904,-0.0134034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286341,-0.0278316) , 
4, 0.59019, 1, 0, 0.267029,-0.0848724) , 
3, 0.296277, 1, 0, 0.486453,-0.0152494)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646652,0.00742055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351536,-0.0101876) , 
5, 5.48178, 1, 0, 0.466584,-0.0124012) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678699,0.00619535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.859712,0.0402548) , 
1, 5.5177, 1, 0, 0.808899,0.109332) , 
0, 2313.1, 1, 0, 0.505888,0.00157608)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435845,-0.0132083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777764,0.0273511) , 
0, 1044.31, 1, 0, 0.67157,0.0533778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549799,0.00270494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153926,-0.0209316) , 
5, 13.4388, 1, 0, 0.425168,-0.0127063) , 
2, 0.014801, 1, 0, 0.508051,0.00952244)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768305,0.022003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579689,0.00204554) , 
3, 0.111101, 1, 0, 0.649654,0.0360549) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416502,-0.00437982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159499,-0.0294224) , 
3, 0.364149, 1, 0, 0.382094,-0.0292792) , 
2, 0.020323, 1, 0, 0.499139,-0.000698599)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680686,0.0168003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596654,-0.00175664) , 
4, 0.612258, 1, 0, 0.622234,0.0165018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258062,-0.0097057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139391,-0.0439439) , 
4, 0.490316, 1, 0, 0.243899,-0.0489963) , 
5, 11.187, 1, 0, 0.493753,-0.00574105)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579335,0.0113857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566845,-0.00515255) , 
4, 0.689413, 1, 0, 0.573033,0.0129856) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318952,-0.00250732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0549465,-0.0382052) , 
2, 0.0223136, 1, 0, 0.155461,-0.0615078) , 
5, 18.9786, 1, 0, 0.504063,0.000681741)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.141036,-0.036436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170905,-0.0168157) , 
3, 0.197497, 1, 0, 0.155731,-0.0818247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541236,0.00370806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23449,-0.0248541) , 
3, 0.425804, 1, 0, 0.524457,0.0086784) , 
4, -0.002393, 1, 0, 0.497054,0.00195252)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65407,0.00326945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.827322,0.0388912) , 
5, 0.692006, 1, 0, 0.757703,0.0964075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479321,0.00355788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50142,-0.0114623) , 
4, 0.827315, 1, 0, 0.484404,-0.000161473) , 
5, 1.4363, 1, 0, 0.509343,0.00865066)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189945,-0.027973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372566,-0.00396708) , 
1, 3.06761, 1, 0, 0.335809,-0.0328952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581422,0.00820952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396345,-0.0168504) , 
4, 1.04422, 1, 0, 0.567177,0.0242717) , 
0, 982.853, 1, 0, 0.493949,0.00617853)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673155,0.0267688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603107,0.00199624) , 
4, 0.354268, 1, 0, 0.613001,0.0231459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218579,-0.00778855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14781,-0.0377538) , 
4, 0.352505, 1, 0, 0.20741,-0.0422337) , 
5, 14.2339, 1, 0, 0.509818,0.00651315)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759958,0.0455066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774893,0.0126681) , 
0, 1161.62, 1, 0, 0.768377,0.116293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386735,-0.00777529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661281,0.00674699) , 
0, 1534.82, 1, 0, 0.471767,-0.0130676) , 
5, 1.3997, 1, 0, 0.498738,-0.00130462)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54523,0.00407363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.796371,0.027101) , 
0, 997.374, 1, 0, 0.723478,0.0777371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43268,0.00375161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35526,-0.0297364) , 
4, 0.64952, 1, 0, 0.416878,-0.0129841) , 
5, 4.74485, 1, 0, 0.521391,0.0179406)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580073,0.00134607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609704,0.0242933) , 
3, 0.184072, 1, 0, 0.58404,0.0174824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397604,-0.00468586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149783,-0.0357974) , 
2, 0.0980421, 1, 0, 0.373819,-0.0282969) , 
3, 0.216082, 1, 0, 0.501703,-0.000448064)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70125,0.0121847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215951,-0.014351) , 
5, 17.3995, 1, 0, 0.626982,0.0324305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730953,0.0216229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410326,-0.00755714) , 
5, 1.37156, 1, 0, 0.437383,-0.0189841) , 
3, 0.111109, 1, 0, 0.507037,-9.55667e-05)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693332,0.0107615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51345,-0.0105646) , 
4, 0.965819, 1, 0, 0.65114,0.0225102) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354621,-0.00432291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17402,-0.0453268) , 
4, 0.609607, 1, 0, 0.334464,-0.0321088) , 
5, 7.90761, 1, 0, 0.499622,-0.00362308)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210277,-0.0440114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21888,-0.0146074) , 
3, 0.271749, 1, 0, 0.213946,-0.120585) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698675,0.00935323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392976,-0.00744434) , 
5, 5.37664, 1, 0, 0.510161,-0.00350568) , 
1, 2.89623, 1, 0, 0.48922,-0.0117828)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515289,0.00104867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317327,-0.013754) , 
3, 0.160485, 1, 0, 0.406083,-0.0270553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477176,-0.0158231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736254,0.0153173) , 
1, 4.34934, 1, 0, 0.70605,0.0408462) , 
0, 1657.15, 1, 0, 0.486825,-0.00877826)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462233,0.00430629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612675,-0.00864636) , 
1, 4.72445, 1, 0, 0.520308,-0.00166549) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20179,-0.014846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24176,-0.0356163) , 
4, 0.587959, 1, 0, 0.220897,-0.0918701) , 
2, 0.0924926, 1, 0, 0.490683,-0.0105907)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0756591,-0.0425477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522465,0.00768524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557487,-0.00543001) , 
4, 0.812514, 1, 0, 0.533733,0.0134809) , 
4, -0.0419635, 1, 0, 0.508966,0.006955)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.117436,-0.0509451) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452945,0.00424443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593286,-0.00722761) , 
1, 4.6768, 1, 0, 0.513179,-0.00203377) , 
1, 2.4039, 1, 0, 0.501439,-0.0075615)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.802053,0.0262776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473653,0.00156218) , 
5, 2.85625, 1, 0, 0.501827,0.0139082) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778965,0.00850269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411392,-0.0194511) , 
2, 0.0148422, 1, 0, 0.526292,-0.044561) , 
4, 0.885223, 1, 0, 0.507438,0.000498177)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654587,-0.000670413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.772706,0.0288978) , 
5, 3.96783, 1, 0, 0.675877,0.0177733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404942,-0.00294196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298379,-0.0287518) , 
4, 0.689051, 1, 0, 0.385575,-0.0286024) , 
5, 4.79709, 1, 0, 0.48861,-0.0121424)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624858,0.0131086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567488,-0.00425578) , 
4, 0.649725, 1, 0, 0.592289,0.0138404) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381568,0.00702068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.110839,-0.0247335) , 
2, 0.00965871, 1, 0, 0.156763,-0.0492679) , 
5, 16.1259, 1, 0, 0.50187,0.000738542)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659602,0.00412211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390824,-0.0085244) , 
5, 3.19775, 1, 0, 0.454974,-0.0206346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.746817,0.0333874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744695,0.00936686) , 
1, 6.06348, 1, 0, 0.745393,0.0607797) , 
1, 5.71422, 1, 0, 0.491145,-0.0104945)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318704,0.00664439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668133,0.0331951) , 
1, 5.2604, 1, 0, 0.390384,0.0438347) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640205,0.00428497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357029,-0.0194768) , 
5, 8.23363, 1, 0, 0.574443,-0.0046486) , 
4, 0.353086, 1, 0, 0.515357,0.0109154)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551147,0.00732404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389911,-0.0129644) , 
4, 1.00491, 1, 0, 0.533828,0.0193294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235175,-0.00119642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199064,-0.0331042) , 
1, 3.80417, 1, 0, 0.214257,-0.073843) , 
3, 0.401182, 1, 0, 0.509109,0.0121225)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748922,0.0232105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62886,0.00228458) , 
4, 0.609562, 1, 0, 0.658878,0.0298298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304013,-0.00413411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138056,-0.0428731) , 
4, 0.530683, 1, 0, 0.278614,-0.0341665) , 
5, 9.59307, 1, 0, 0.509961,0.00476794)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293684,-0.0185482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692901,0.0113776) , 
4, 0.215143, 1, 0, 0.606845,0.0192665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356614,0.0119668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471559,-0.0116798) , 
4, 0.353436, 1, 0, 0.435055,-0.0191172) , 
3, 0.117282, 1, 0, 0.499644,-0.00468581)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399698,0.0104373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516443,-0.00297396) , 
1, 3.67941, 1, 0, 0.487673,0.00131101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653654,-0.0017408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298696,-0.0239299) , 
5, 2.20861, 1, 0, 0.493782,-0.0433766) , 
4, 0.886402, 1, 0, 0.488958,-0.00808463)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233766,-0.0317116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349833,-0.00549535) , 
0, 771.379, 1, 0, 0.338396,-0.0299586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55105,0.0079972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678624,-0.00750412) , 
1, 5.49759, 1, 0, 0.583845,0.0164836) , 
0, 997.368, 1, 0, 0.50477,0.0015216)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613078,0.0108174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547451,-0.00488469) , 
4, 0.827414, 1, 0, 0.590194,0.021911) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192951,0.00992377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173581,-0.0180661) , 
1, 3.66751, 1, 0, 0.17958,-0.0307873) , 
5, 17.3966, 1, 0, 0.509307,0.0115299)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.113521,-0.0257854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439206,0.0146169) , 
4, -0.0355492, 1, 0, 0.383634,0.0331855) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579775,-0.00234222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.106096,-0.0446162) , 
5, 14.4406, 1, 0, 0.553301,-0.0167945) , 
4, 0.353584, 1, 0, 0.498624,-0.000687842)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742514,-0.00209078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728088,0.022959) , 
3, 0.117248, 1, 0, 0.733078,0.0591746) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486993,-0.00229624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0836183,-0.0343966) , 
5, 31.2578, 1, 0, 0.46382,-0.0132188) , 
5, 1.58208, 1, 0, 0.493174,-0.00532656)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72175,0.0138748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478867,-0.00118377) , 
5, 3.38276, 1, 0, 0.539709,0.00972918) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0391018,-0.0354914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108828,-0.0361081) , 
0, 1234.41, 1, 0, 0.0703555,-0.0842468) , 
5, 27.4124, 1, 0, 0.507905,0.00336123)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234436,-0.0305072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48888,-0.000425082) , 
0, 793.545, 1, 0, 0.470334,-0.00961589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.820352,0.0488523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.783409,0.00818018) , 
1, 5.75573, 1, 0, 0.796949,0.0777663) , 
0, 2515.83, 1, 0, 0.497617,-0.00231662)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487352,0.00107282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.81012,0.0247781) , 
0, 2515.83, 1, 0, 0.516645,0.010984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212504,-0.0287025) , 
2, 0.112841, 1, 0, 0.501789,0.00568939)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725495,0.00690016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757739,0.0420039) , 
4, 1.02787, 1, 0, 0.732256,0.0570091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482702,0.0047064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26134,-0.0257453) , 
4, 0.885331, 1, 0, 0.461053,0.00682504) , 
5, 2.87009, 1, 0, 0.516201,0.0170298)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237016,0.0468289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379335,-0.0123997) , 
4, -0.0217539, 1, 0, 0.367037,-0.0362805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553887,0.0172131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696919,0.0011048) , 
4, 0.353456, 1, 0, 0.655632,0.0217221) , 
0, 1292.28, 1, 0, 0.494027,-0.0107576)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563805,-0.00166161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364335,0.0136763) , 
2, 0.0702475, 1, 0, 0.53171,0.00230123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267943,-0.0127706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.162099,-0.0375275) , 
3, 0.442135, 1, 0, 0.233845,-0.0734256) , 
3, 0.357978, 1, 0, 0.492363,-0.00770188)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.19268,-0.0129598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519336,0.00518024) , 
4, 0.116404, 1, 0, 0.46611,0.0111135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747328,-0.00022081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369377,-0.0297966) , 
2, 0.0405947, 1, 0, 0.643764,-0.0322935) , 
1, 5.39129, 1, 0, 0.502066,0.00232835)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488019,-0.000802068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362694,-0.0174036) , 
4, 0.985045, 1, 0, 0.472371,-0.0105706) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.856013,0.0323389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764528,-0.00075951) , 
0, 2833.04, 1, 0, 0.814918,0.0541324) , 
1, 6.0915, 1, 0, 0.499703,-0.00540791)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390242,-0.0167241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.703093,0.0102322) , 
1, 3.20418, 1, 0, 0.6715,0.0271118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352764,-0.00421069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32159,-0.0211187) , 
4, 0.47144, 1, 0, 0.344318,-0.0317133) , 
5, 7.17291, 1, 0, 0.507683,-0.00234148)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534506,0.011021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667924,1.30371e-05) , 
1, 4.70364, 1, 0, 0.593597,0.0239651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339729,-0.00407387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469708,-0.0335853) , 
1, 5.35745, 1, 0, 0.359595,-0.032813) , 
3, 0.216015, 1, 0, 0.504231,0.00228144)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428875,0.000489658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492109,-0.0104922) , 
4, 0.767867, 1, 0, 0.449742,-0.0123746) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786492,0.033058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728232,0.00250308) , 
1, 6.06379, 1, 0, 0.746117,0.0396849) , 
1, 5.747, 1, 0, 0.484043,-0.00634945)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384573,0.0103894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57065,0.0580299) , 
1, 3.35462, 1, 0, 0.434729,0.0834342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573565,0.00416729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226904,-0.0211241) , 
3, 0.41355, 1, 0, 0.55295,0.00975299) , 
1, 3.59039, 1, 0, 0.527045,0.0258984)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678646,-0.00336939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359795,-0.0218254) , 
2, 0.0313469, 1, 0, 0.550621,-0.041127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41804,-0.000540263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.879706,0.04762) , 
0, 2616.23, 1, 0, 0.445694,0.00786922) , 
3, 0.14197, 1, 0, 0.490651,-0.0131237)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546949,0.00445394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128797,-0.0169566) , 
5, 21.0006, 1, 0, 0.445217,0.00281534) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650531,-0.000715882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289572,-0.0272119) , 
5, 4.93863, 1, 0, 0.550085,-0.0287534) , 
4, 0.669107, 1, 0, 0.490335,-0.0107666)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168312,-0.0238017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667123,0.0126201) , 
4, 0.0378103, 1, 0, 0.619255,0.0355803) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489238,-0.0184076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417505,0.00417484) , 
3, 0.187992, 1, 0, 0.441412,-0.0130401) , 
3, 0.11111, 1, 0, 0.501817,0.0034739)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528087,0.00231733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263669,-0.0171981) , 
2, 0.0129275, 1, 0, 0.342333,-0.0398771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704163,0.00844142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316421,-0.00601021) , 
5, 10.4449, 1, 0, 0.57232,0.0128385) , 
1, 4.01869, 1, 0, 0.490413,-0.00593538)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679387,0.0158665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380387,-0.00479849) , 
5, 1.60026, 1, 0, 0.413802,-0.008407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701414,0.00160487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.650736,0.0172276) , 
3, 0.148144, 1, 0, 0.677085,0.033495) , 
0, 1492.1, 1, 0, 0.49834,0.00504743)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509726,0.00208688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219827,-0.0230143) , 
2, 0.114708, 1, 0, 0.49552,0.00369955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600347,-0.0386719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.721242,-0.0134679) , 
0, 3229.41, 1, 0, 0.658895,-0.080121) , 
0, 2712.04, 1, 0, 0.506177,-0.00176799)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442807,0.00200322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.703591,0.0247563) , 
4, 0.62297, 1, 0, 0.465248,0.0145773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627888,-0.00337059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227036,-0.0336336) , 
5, 5.38746, 1, 0, 0.542326,-0.0339799) , 
4, 0.688859, 1, 0, 0.496651,-0.00520574)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34231,-0.0200991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696681,0.00753009) , 
1, 3.18368, 1, 0, 0.662699,0.0167052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385187,-0.0107006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247492,0.00957078) , 
2, 0.0629301, 1, 0, 0.352954,-0.0245059) , 
5, 6.99152, 1, 0, 0.498268,-0.00517219)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7912,0.0142521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.782104,0.0413288) , 
3, 0.160711, 1, 0, 0.78678,0.108466) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373735,0.00598158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539738,-0.00600304) , 
4, 0.372626, 1, 0, 0.480232,-0.0073606) , 
5, 1.1544, 1, 0, 0.499055,-0.000248479)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319632,-0.0128313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575147,0.00100667) , 
1, 3.30344, 1, 0, 0.539573,-0.00375038) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198184,-0.0348698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263683,-0.00327169) , 
3, 0.39694, 1, 0, 0.233556,-0.0666442) , 
3, 0.339486, 1, 0, 0.488263,-0.0142958)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469324,0.00180639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603983,-0.0201945) , 
1, 5.48587, 1, 0, 0.486233,-0.00307049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822088,0.0275444) , 
1, 6.27939, 1, 0, 0.504237,0.00177609)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312736,-0.00633105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0575121,-0.0412472) , 
2, 0.0301053, 1, 0, 0.15293,-0.0622736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661366,0.00627698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379586,-0.00473878) , 
5, 7.17291, 1, 0, 0.531659,0.00468121) , 
4, 0.0376812, 1, 0, 0.49186,-0.00235482)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496901,0.00279065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.147721,-0.0301074) , 
3, 0.438213, 1, 0, 0.478535,0.00452661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544781,-0.0312817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50234,-0.00474066) , 
3, 0.0987391, 1, 0, 0.515679,-0.0457497) , 
4, 0.886, 1, 0, 0.486401,-0.0061193)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74014,0.0156874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286444,-0.00424461) , 
5, 9.77288, 1, 0, 0.425122,0.00804242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715175,0.0119658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510177,-0.0128587) , 
5, 1.10466, 1, 0, 0.535931,-0.0352776) , 
4, 0.62962, 1, 0, 0.476669,-0.0121095)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666879,0.00541985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366048,-0.00424435) , 
5, 4.79628, 1, 0, 0.463213,-0.00346498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770984,0.00285114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.834451,0.0329635) , 
3, 0.104377, 1, 0, 0.806278,0.0614133) , 
0, 2417.74, 1, 0, 0.497871,0.00308924)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453666,0.00699589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442633,0.0406058) , 
4, 1.14317, 1, 0, 0.452976,0.0314106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373656,0.0130396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627055,-0.00633785) , 
4, 0.15616, 1, 0, 0.584313,-0.0118506) , 
1, 4.54453, 1, 0, 0.511513,0.012129)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233175,-0.027487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486155,0.000139115) , 
0, 776.466, 1, 0, 0.476543,-0.00314095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652418,-0.0359287) , 
0, 2893.83, 1, 0, 0.487465,-0.00961451)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495253,0.0242461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.134707,-0.00633735) , 
5, 23.9584, 1, 0, 0.343267,0.0450138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543107,-0.00677659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440014,0.0288875) , 
2, 0.0979783, 1, 0, 0.537003,-0.0178712) , 
4, 0.214819, 1, 0, 0.495916,-0.0045348)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822916,0.0205604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547446,0.000481122) , 
5, 2.79956, 1, 0, 0.607189,0.0162267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431628,-0.0264673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39792,-0.00053078) , 
3, 0.188466, 1, 0, 0.403524,-0.0175432) , 
3, 0.154315, 1, 0, 0.499055,-0.00170311)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501071,0.0788144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0820077,-0.0219922) , 
2, 0.0371969, 1, 0, 0.245334,0.0672031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588119,0.00309813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18125,-0.0190868) , 
5, 15.3814, 1, 0, 0.520099,-0.000216744) , 
4, 0.0173581, 1, 0, 0.49674,0.00551481)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512097,0.0196239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643278,0.00176981) , 
4, 0.3314, 1, 0, 0.606688,0.0245909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305161,-0.00525734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394171,-0.0333079) , 
0, 2084.11, 1, 0, 0.314246,-0.029579) , 
2, 0.0388526, 1, 0, 0.506724,0.00607424)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393118,0.00282856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461395,-0.0107573) , 
1, 4.13585, 1, 0, 0.421244,-0.010034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.844048,0.0236378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523861,-0.00353347) , 
5, 6.24407, 1, 0, 0.67961,0.028625) , 
1, 4.93251, 1, 0, 0.500067,0.00176023)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536992,-0.00157619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369639,0.0177194) , 
2, 0.0462162, 1, 0, 0.490816,0.0120145) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592454,-0.0137792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36793,0.0114546) , 
4, 1.08179, 1, 0, 0.527367,-0.0262612) , 
4, 0.827289, 1, 0, 0.501127,0.00121743)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306826,0.00252571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.631212,0.028537) , 
1, 5.10373, 1, 0, 0.38137,0.0294714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591044,-0.00301708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219305,-0.0215323) , 
5, 10.8462, 1, 0, 0.537784,-0.0203629) , 
4, 0.353086, 1, 0, 0.489175,-0.00487573)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49455,0.00019473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543699,-0.0123126) , 
4, 0.827317, 1, 0, 0.507968,-0.0118653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403153,0.0341683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322368,0.01241) , 
2, 0.119625, 1, 0, 0.36238,0.073536) , 
2, 0.099892, 1, 0, 0.497754,-0.00587382)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611835,0.00330642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442178,-0.00707927) , 
3, 0.104926, 1, 0, 0.501451,-0.0129646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378919,0.0188247) , 
2, 0.107185, 1, 0, 0.493554,-0.00803706)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367426,0.0434886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567806,0.000433146) , 
4, -0.0223894, 1, 0, 0.558044,0.00748365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362676,-0.028859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259687,-0.00141515) , 
5, 4.03487, 1, 0, 0.286235,-0.0358272) , 
2, 0.0591952, 1, 0, 0.497638,-0.00214166)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510902,0.00255697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.863431,0.030592) , 
1, 6.17183, 1, 0, 0.534854,0.0147441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.104779,-0.0479005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345518,-0.00100116) , 
4, 0.372057, 1, 0, 0.251165,-0.0523399) , 
2, 0.0925062, 1, 0, 0.508242,0.00845111)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.146619,-0.0221462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530502,0.00437715) , 
4, -0.00203568, 1, 0, 0.493003,0.00918689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712619,0.00752497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363977,-0.0249217) , 
5, 1.47264, 1, 0, 0.478335,-0.0506796) , 
4, 0.866721, 1, 0, 0.489511,-0.00506557)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598112,-0.00903913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521091,0.00326283) , 
3, 0.0678966, 1, 0, 0.538632,0.00198897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207126,-0.0340456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27068,-0.000137399) , 
2, 0.0990317, 1, 0, 0.239467,-0.059101) , 
2, 0.0721549, 1, 0, 0.487517,-0.00844869)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510053,-0.0206705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507925,0.00314142) , 
3, 0.0255492, 1, 0, 0.508108,0.00446141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177399,-0.0405292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208668,0.00148418) , 
2, 0.0204627, 1, 0, 0.194114,-0.0702005) , 
3, 0.413528, 1, 0, 0.485571,-0.000897356)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758334,0.0136029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49124,0.000287088) , 
5, 1.58339, 1, 0, 0.522466,0.00665214) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202875,0.00130168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17067,-0.0367514) , 
4, 0.465601, 1, 0, 0.184703,-0.0713632) , 
3, 0.41355, 1, 0, 0.499733,0.00140146)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597348,-0.0016945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.867258,0.0334578) , 
1, 4.17363, 1, 0, 0.761404,0.0648207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673133,0.00955269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438287,-0.00265946) , 
2, 0.0073994, 1, 0, 0.474533,-0.0028399) , 
5, 1.59923, 1, 0, 0.504204,0.00415811)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148227,-0.0317677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.113667,-0.0185005) , 
3, 0.148935, 1, 0, 0.128406,-0.0588546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591333,-0.00021609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404007,0.0135905) , 
2, 0.0425189, 1, 0, 0.535258,0.014125) , 
4, -0.00241285, 1, 0, 0.505307,0.00875257)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716019,0.0129874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379493,0.00028302) , 
5, 6.99825, 1, 0, 0.512072,0.0195057) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557942,-0.00148457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0930182,-0.049962) , 
2, 0.0777101, 1, 0, 0.441662,-0.0410044) , 
4, 0.945658, 1, 0, 0.500756,0.00978064)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553715,-0.00551993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670719,0.0173573) , 
3, 0.0397707, 1, 0, 0.629393,0.0317812) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485181,-0.0179338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410652,0.00289342) , 
3, 0.19273, 1, 0, 0.434845,-0.0143128) , 
3, 0.111103, 1, 0, 0.504551,0.00220253)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699103,0.0112897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298057,-0.00261692) , 
5, 9.70144, 1, 0, 0.493501,0.0161614) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548303,-0.0158825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350192,0.0142263) , 
3, 0.320973, 1, 0, 0.513942,-0.0380243) , 
4, 0.866828, 1, 0, 0.498313,0.00340653)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417936,0.034764) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596474,-0.00330298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386976,0.00870193) , 
2, 0.0351524, 1, 0, 0.515489,0.00448791) , 
1, 2.64644, 1, 0, 0.511545,0.00916194)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold2::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold2::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
