// Class: ReadBDT-0.3_fold4
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold4
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.30/04       [400900]
Creator        : b78499db
Date           : Thu Mar 21 15:54:52 2024
Host           : Darwin Sonoma-arm64.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:43:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis
Training events: 35158
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.003479004,8696.23632812]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.00020766258,8.59782600403]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [1.25554126264e-18,0.149860098958]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [9.20502588997e-06,0.499961167574]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.39996659756]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000704350823071,129.481124878]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [84,1159527808]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold4Node

#ifndef BDT-0.3_fold4Node__def
#define BDT-0.3_fold4Node__def

class BDT-0.3_fold4Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold4Node ( BDT-0.3_fold4Node* left,BDT-0.3_fold4Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold4Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold4Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold4Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold4Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold4Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold4Node::~BDT-0.3_fold4Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold4Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold4Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold4 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold4( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold4" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold4() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold4Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold4::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold4Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold4Node*)current->GetRight();
         else current=(BDT-0.3_fold4Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold4::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471723,-0.00565535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.716301,0.0432603) , 
0, 1142.59, 1, 0, 0.611639,0.111639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386028,-0.0227943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142188,-0.0715624) , 
2, 0.0277478, 1, 0, 0.255795,-0.244205) , 
5, 11.0711, 1, 0, 0.490081,-0.00991886)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684144,0.0351449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436107,-0.0130235) , 
2, 0.029602, 1, 0, 0.582243,0.0767165) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289707,-0.0389556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0770888,-0.0778354) , 
2, 0.0371165, 1, 0, 0.192248,-0.282833) , 
5, 15.7787, 1, 0, 0.501193,0.00199302)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477448,-0.00551695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736674,0.0429248) , 
0, 1436.72, 1, 0, 0.576142,0.0643269) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332224,-0.0274926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103677,-0.0677738) , 
2, 0.0186255, 1, 0, 0.17491,-0.271937) , 
5, 17.2121, 1, 0, 0.502011,0.00219937)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679204,0.0306389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38957,-0.0263659) , 
3, 0.314763, 1, 0, 0.626411,0.100639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.164745,-0.0574203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413853,-0.0112831) , 
0, 1075.07, 1, 0, 0.302794,-0.156469) , 
5, 9.48899, 1, 0, 0.495458,-0.00340053)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682022,0.0284475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4151,-0.0202127) , 
3, 0.277635, 1, 0, 0.62033,0.0850349) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246177,-0.0383859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574281,0.0213216) , 
0, 2009.99, 1, 0, 0.293302,-0.144883) , 
5, 10.0427, 1, 0, 0.491406,-0.00560504)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653845,0.0226211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364294,-0.0261894) , 
3, 0.29626, 1, 0, 0.589053,0.0573778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.141328,-0.0522918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324076,-0.020923) , 
0, 1349.26, 1, 0, 0.204116,-0.197173) , 
5, 14.2341, 1, 0, 0.491932,-0.006846)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697554,0.0292587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469816,-0.0097113) , 
2, 0.0259017, 1, 0, 0.593806,0.0562074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374944,-0.00984348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.161762,-0.0454044) , 
2, 0.0129405, 1, 0, 0.20928,-0.174182) , 
5, 13.9831, 1, 0, 0.495878,-0.00246657)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35482,-0.0317778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655262,0.0219917) , 
1, 3.54969, 1, 0, 0.595535,0.0550569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.174793,-0.0397522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403632,-0.00311227) , 
0, 2009.99, 1, 0, 0.205892,-0.158322) , 
5, 14.3874, 1, 0, 0.496082,0.000593278)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786553,0.0413527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49931,0.00203377) , 
5, 5.59336, 1, 0, 0.62657,0.0936697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57335,0.00705528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283643,-0.0307791) , 
5, 4.79709, 1, 0, 0.369139,-0.0912613) , 
2, 0.0258979, 1, 0, 0.504598,0.00604863)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452316,-0.0082982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.679437,0.0266729) , 
0, 1046.84, 1, 0, 0.602561,0.070616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461311,-0.00875594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0879093,-0.05092) , 
5, 15.0342, 1, 0, 0.345766,-0.0958945) , 
2, 0.0351122, 1, 0, 0.508094,0.00936186)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699938,0.0240755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393566,-0.0252569) , 
2, 0.0702475, 1, 0, 0.657976,0.0824243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356404,-0.0121698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164566,-0.0665158) , 
4, 0.649558, 1, 0, 0.338169,-0.0811135) , 
5, 7.99508, 1, 0, 0.505471,0.00443906)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531075,0.00131661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289168,-0.0286942) , 
2, 0.0240233, 1, 0, 0.396417,-0.0707279) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726406,0.0301993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434435,-0.00632107) , 
2, 0.0386927, 1, 0, 0.645392,0.0938486) , 
0, 1490.39, 1, 0, 0.480881,-0.0148957)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489576,-0.00902112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717164,0.0244544) , 
1, 4.19941, 1, 0, 0.629871,0.0539977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304531,-0.0169049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0832282,-0.0686589) , 
4, 0.609851, 1, 0, 0.287918,-0.094139) , 
5, 9.59282, 1, 0, 0.489333,-0.00688429)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517754,0.00780259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331125,-0.0246149) , 
3, 0.166653, 1, 0, 0.416916,-0.0451381) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639589,0.0176424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.852108,0.0573117) , 
1, 6.23833, 1, 0, 0.676407,0.112511) , 
0, 1492.1, 1, 0, 0.504114,0.00783709)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432183,-0.0117228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713927,0.0271455) , 
0, 1044.31, 1, 0, 0.620772,0.0652182) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459827,0.00141095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2732,-0.0304088) , 
3, 0.141971, 1, 0, 0.354302,-0.0753186) , 
2, 0.0277201, 1, 0, 0.496801,-0.000164346)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593157,0.0155216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376857,-0.0341835) , 
4, 1.0428, 1, 0, 0.573464,0.0494054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398791,-0.014078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155066,-0.0467282) , 
2, 0.0480961, 1, 0, 0.325577,-0.108391) , 
3, 0.277744, 1, 0, 0.508526,0.008068)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771849,0.0332549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567785,0.000849631) , 
3, 0.117275, 1, 0, 0.646006,0.0611428) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22002,-0.0275365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48302,0.00608088) , 
0, 1417.06, 1, 0, 0.3077,-0.0694767) , 
5, 9.59263, 1, 0, 0.513675,0.01005)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394066,-0.0103292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633752,0.0175173) , 
0, 1044.31, 1, 0, 0.550975,0.0356407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315432,-0.0200912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164381,-0.0512751) , 
3, 0.425293, 1, 0, 0.2641,-0.138521) , 
3, 0.327142, 1, 0, 0.503421,0.00677076)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685071,0.0200337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480601,-0.0146093) , 
4, 1.00562, 1, 0, 0.650602,0.0651582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318984,-0.0100027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155806,-0.0527616) , 
4, 0.491283, 1, 0, 0.289502,-0.0784234) , 
5, 9.59263, 1, 0, 0.503837,0.00680133)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559377,0.00693414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320736,-0.0371943) , 
4, 1.04449, 1, 0, 0.534041,0.00963355) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0273809,-0.0624028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178372,-0.0328552) , 
4, 0.00959405, 1, 0, 0.10256,-0.186687) , 
5, 23.9796, 1, 0, 0.489582,-0.0105949)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504975,0.00361553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340946,-0.0194736) , 
3, 0.154304, 1, 0, 0.410947,-0.043251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852634,0.0392098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577952,0.00917513) , 
5, 5.48078, 1, 0, 0.693514,0.0938186) , 
0, 1534.82, 1, 0, 0.499462,-0.000313468)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324368,-0.0269932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58471,0.0110356) , 
1, 3.28374, 1, 0, 0.553915,0.0285863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.170865,-0.038999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363537,-0.0152797) , 
0, 969.509, 1, 0, 0.291256,-0.105264) , 
3, 0.302385, 1, 0, 0.495386,-0.00124016)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.812324,0.0356692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533738,0.00148342) , 
2, 0.0295135, 1, 0, 0.723135,0.107256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462393,-0.000905875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251732,-0.0501456) , 
4, 0.886465, 1, 0, 0.443438,-0.0240833) , 
5, 2.82459, 1, 0, 0.499361,0.00217665)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519403,0.00102258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278843,-0.0233916) , 
3, 0.296287, 1, 0, 0.459293,-0.0218653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.908179,0.0474536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577265,0.0168549) , 
5, 8.79782, 1, 0, 0.7821,0.145904) , 
1, 5.74716, 1, 0, 0.497588,-0.00196268)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453916,-0.00582088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702527,0.0183473) , 
0, 1325.86, 1, 0, 0.560495,0.0188565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0218438,-0.0604444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17658,-0.0291709) , 
4, -0.0661682, 1, 0, 0.144344,-0.13501) , 
5, 19.183, 1, 0, 0.491094,-0.00680345)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733939,0.0256627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452132,-0.00630025) , 
3, 0.259177, 1, 0, 0.65546,0.0716519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205505,-0.0360151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46496,-0.00180938) , 
1, 3.30077, 1, 0, 0.429606,-0.0274371) , 
2, 0.0147988, 1, 0, 0.501598,0.00414792)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693863,0.0238102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578696,-0.00219432) , 
4, 0.690097, 1, 0, 0.624716,0.0370491) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296443,-0.00830158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149058,-0.0489283) , 
4, 0.431373, 1, 0, 0.270471,-0.0646748) , 
5, 11.0711, 1, 0, 0.500085,0.00126039)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60852,0.0101354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319299,-0.0323354) , 
4, 1.04439, 1, 0, 0.576464,0.0235788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.159738,-0.025445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0797057,-0.0509054) , 
4, 0.183276, 1, 0, 0.140009,-0.116396) , 
5, 18.9773, 1, 0, 0.501615,-0.000426044)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394763,-0.0105185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642732,0.0134068) , 
0, 946.222, 1, 0, 0.578396,0.0309315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321431,-0.00379923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0667874,-0.0455319) , 
2, 0.0186199, 1, 0, 0.147901,-0.107656) , 
5, 18.6471, 1, 0, 0.505426,0.00744063)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570993,0.00308009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.847512,0.0364671) , 
0, 2123.43, 1, 0, 0.622072,0.037055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400253,-0.00629805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284385,-0.0335751) , 
4, 1.00491, 1, 0, 0.38146,-0.0465459) , 
2, 0.0222015, 1, 0, 0.496144,-0.00669885)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740459,0.0231263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469302,-0.00105014) , 
2, 0.0277132, 1, 0, 0.620622,0.0509156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290279,-0.0183243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556955,0.00323788) , 
0, 1279.66, 1, 0, 0.4087,-0.0364722) , 
3, 0.179004, 1, 0, 0.517335,0.00832449)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434195,-0.00515925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689081,0.0172897) , 
0, 1327.19, 1, 0, 0.553859,0.0214988) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257838,-0.0298477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273702,0.00288458) , 
2, 0.0610451, 1, 0, 0.262007,-0.0915544) , 
3, 0.33332, 1, 0, 0.501835,0.00134666)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740304,0.0188933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421357,-0.0127262) , 
3, 0.283912, 1, 0, 0.6702,0.0486715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408508,-0.00197027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24005,-0.0515544) , 
4, 0.688894, 1, 0, 0.384089,-0.0383574) , 
5, 5.59416, 1, 0, 0.49427,-0.0048426)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667849,0.0177147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464841,-0.00239467) , 
3, 0.160488, 1, 0, 0.563403,0.0311329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364085,0.00772548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0628253,-0.043308) , 
2, 0.0168761, 1, 0, 0.152039,-0.0829878) , 
5, 22.38, 1, 0, 0.512676,0.0170603)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.178626,-0.0306462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.677003,0.0170416) , 
4, 0.037617, 1, 0, 0.633225,0.0547684) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229573,-0.0263661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472596,-0.00192637) , 
0, 848.111, 1, 0, 0.435656,-0.0227448) , 
3, 0.123437, 1, 0, 0.510436,0.00659393)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63915,0.0121964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.160472,-0.0311371) , 
5, 24.385, 1, 0, 0.604107,0.0388166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337204,-0.00668129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277923,-0.0367662) , 
4, 0.846903, 1, 0, 0.320097,-0.0654108) , 
2, 0.0425529, 1, 0, 0.514175,0.00581312)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585879,0.0153907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574283,-0.00287549) , 
4, 0.55083, 1, 0, 0.578426,0.0164281) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368944,0.00360375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127216,-0.0272489) , 
2, 0.0112349, 1, 0, 0.169006,-0.0691022) , 
5, 17.5854, 1, 0, 0.498495,-0.000269954)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732002,0.0171309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462753,-0.00344126) , 
5, 3.1995, 1, 0, 0.527542,0.00612365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293796,0.0046315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139961,-0.0514086) , 
1, 3.62871, 1, 0, 0.19765,-0.129506) , 
3, 0.407293, 1, 0, 0.496641,-0.00658082)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698047,0.0156775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322605,-0.0306317) , 
2, 0.090537, 1, 0, 0.664216,0.0470647) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218081,-0.0171829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457927,0.00275974) , 
0, 1116.87, 1, 0, 0.345814,-0.0229714) , 
5, 7.99431, 1, 0, 0.511956,0.0135733)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320276,-0.0285284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23059,0.00655121) , 
5, 15.923, 1, 0, 0.297624,-0.0910132) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639511,0.0103549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19952,-0.0159589) , 
5, 15.8154, 1, 0, 0.542443,0.0217866) , 
1, 3.24382, 1, 0, 0.509432,0.00657707)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737867,0.0196484) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616425,7.86622e-05) , 
4, 0.807328, 1, 0, 0.666333,0.0333023) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378024,-0.00549371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200562,-0.0467293) , 
4, 0.688859, 1, 0, 0.357499,-0.0410909) , 
5, 6.3956, 1, 0, 0.493141,-0.0084168)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.875807,0.0405475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681569,0.014676) , 
2, 0.0166264, 1, 0, 0.7581,0.0957059) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456888,0.00269586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494243,-0.0174897) , 
4, 0.688548, 1, 0, 0.469465,-0.017314) , 
5, 1.59923, 1, 0, 0.500058,-0.00533478)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640016,0.0101363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526958,-0.0109308) , 
4, 0.88726, 1, 0, 0.607416,0.017657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.19653,-0.0141015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101495,-0.0484971) , 
4, 0.352522, 1, 0, 0.18212,-0.0665463) , 
5, 14.2331, 1, 0, 0.495578,-0.00448555)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623775,0.0161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298025,-0.0147378) , 
5, 2.68957, 1, 0, 0.347863,-0.0374655) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765837,0.023583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516492,0.00216543) , 
2, 0.0147988, 1, 0, 0.609536,0.0394281) , 
0, 1044.31, 1, 0, 0.511299,0.0105608)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272891,-0.027388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565551,0.00521149) , 
1, 2.86809, 1, 0, 0.547181,0.0125285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.214136,-0.0330196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282436,-0.011017) , 
3, 0.389621, 1, 0, 0.264108,-0.0668316) , 
3, 0.358, 1, 0, 0.508743,0.00175224)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614844,0.000990046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200535,-0.014953) , 
5, 14.3805, 1, 0, 0.505273,-0.0103501) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607828,-0.0020299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198466,-0.0432854) , 
5, 2.36097, 1, 0, 0.403212,-0.0931045) , 
4, 0.98516, 1, 0, 0.492617,-0.0206126)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784404,0.0312158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539264,-0.00244488) , 
5, 1.17201, 1, 0, 0.559069,0.000755931) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.064058,-0.0409141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188513,-0.0179711) , 
1, 4.5515, 1, 0, 0.112798,-0.0929257) , 
5, 18.9773, 1, 0, 0.48405,-0.014992)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614902,0.0231176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685986,0.00249814) , 
0, 1572.82, 1, 0, 0.64036,0.06327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620945,0.010256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390609,-0.00885359) , 
2, 0.0129509, 1, 0, 0.454975,-0.0132975) , 
3, 0.0864434, 1, 0, 0.504375,0.00710579)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622975,0.00848834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221179,-0.0324344) , 
3, 0.425866, 1, 0, 0.599696,0.0236494) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335242,-0.00262969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320133,-0.0258167) , 
4, 0.82707, 1, 0, 0.330705,-0.039998) , 
2, 0.0388526, 1, 0, 0.502431,0.000635119)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459628,-8.46116e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546595,-0.0380622) , 
0, 2113.98, 1, 0, 0.46364,-0.0068065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757887,0.00721645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.848034,0.0466968) , 
3, 0.141495, 1, 0, 0.799544,0.09254) , 
0, 2399.1, 1, 0, 0.498529,0.0035124)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232329,-0.0312782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480945,0.000946621) , 
0, 788.577, 1, 0, 0.465473,-0.0041632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791968,0.0374206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.806261,0.0140762) , 
4, 0.649243, 1, 0, 0.798589,0.0992654) , 
0, 2313.03, 1, 0, 0.501029,0.00687635)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527947,-0.00342739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.778904,0.0199043) , 
1, 4.19965, 1, 0, 0.685482,0.0407919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43192,0.000549117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325651,-0.0301477) , 
4, 0.708554, 1, 0, 0.414322,-0.0178842) , 
5, 4.79709, 1, 0, 0.509038,0.0026113)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438175,-0.00343411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539105,-0.0295121) , 
1, 5.55157, 1, 0, 0.446796,-0.0218044) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801868,0.0308398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761437,0.000121219) , 
4, 0.807523, 1, 0, 0.787883,0.074036) , 
0, 2230.77, 1, 0, 0.490501,-0.00952405)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436489,-0.0151943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.772722,0.020414) , 
1, 3.36696, 1, 0, 0.725124,0.0559817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458623,0.00179088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372855,-0.0232078) , 
4, 0.768001, 1, 0, 0.443471,-0.010433) , 
5, 3.19877, 1, 0, 0.505591,0.00421489)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211114,-0.0379255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33855,-0.0109877) , 
0, 774.369, 1, 0, 0.328571,-0.0508693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543689,0.00759769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619214,-0.00953122) , 
4, 0.629422, 1, 0, 0.578576,-0.000777625) , 
0, 1079.06, 1, 0, 0.479761,-0.0205764)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756852,0.0102953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598388,0.036551) , 
5, 11.3801, 1, 0, 0.711564,0.072308) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585941,0.0065825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388136,-0.011086) , 
3, 0.11111, 1, 0, 0.457941,-0.018867) , 
2, 0.00739447, 1, 0, 0.497001,-0.00482531)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512491,0.0100775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562657,-0.00365552) , 
4, 0.629829, 1, 0, 0.536651,0.013794) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0786979,-0.0415077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0985947,-0.0179185) , 
3, 0.234053, 1, 0, 0.086597,-0.0921406) , 
5, 27.1756, 1, 0, 0.502538,0.00576436)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74632,0.0187984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607649,-0.00078073) , 
4, 0.832897, 1, 0, 0.666775,0.0293627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384082,-0.00276313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206719,-0.038431) , 
4, 0.688788, 1, 0, 0.364134,-0.0253863) , 
5, 6.3948, 1, 0, 0.50014,-0.000782165)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536017,-0.00193869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777103,0.0190378) , 
1, 4.18098, 1, 0, 0.688086,0.0414286) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439076,0.00028855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289769,-0.0356733) , 
4, 0.768078, 1, 0, 0.419732,-0.0165342) , 
5, 4.30436, 1, 0, 0.505183,0.00192267)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609466,0.00454456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305611,-0.0133945) , 
3, 0.339446, 1, 0, 0.564392,0.00728197) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.133066,-0.00899263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121596,-0.0328333) , 
1, 4.2528, 1, 0, 0.127873,-0.0590255) , 
5, 20.7815, 1, 0, 0.500442,-0.00243205)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321538,-0.00637051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27676,-0.0300951) , 
1, 4.34217, 1, 0, 0.313781,-0.0398322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.126674,-0.0349197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595637,0.00465919) , 
4, -0.0419635, 1, 0, 0.568433,0.011121) , 
0, 946.207, 1, 0, 0.500811,-0.00240941)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794059,0.0222475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49085,-0.00493381) , 
5, 1.58292, 1, 0, 0.521549,-0.00892367) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.164073,-0.0323598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533924,0.0120255) , 
0, 1508.71, 1, 0, 0.234148,-0.08602) , 
3, 0.339485, 1, 0, 0.474544,-0.0215329)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375432,-0.00534011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151846,-0.0326214) , 
2, 0.0515563, 1, 0, 0.301634,-0.0504974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375066,0.017497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611022,0.000670866) , 
4, 0.155623, 1, 0, 0.569627,0.0126383) , 
0, 946.253, 1, 0, 0.498932,-0.00401665)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.746215,0.012599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45854,-0.00831544) , 
3, 0.253056, 1, 0, 0.669807,0.0251213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385936,0.000164092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319374,-0.0288596) , 
4, 0.590238, 1, 0, 0.370825,-0.0246381) , 
5, 5.73784, 1, 0, 0.493548,-0.00421345)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367619,-0.0204796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676179,0.00670491) , 
1, 3.30416, 1, 0, 0.635289,0.010673) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352974,-0.00466142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118738,-0.0490509) , 
4, 0.610045, 1, 0, 0.326295,-0.0333081) , 
5, 7.90761, 1, 0, 0.487157,-0.0104117)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.159489,-0.0359535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46037,-0.00276063) , 
1, 2.53981, 1, 0, 0.449123,-0.0149708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.785565,0.031778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.740739,-0.00357065) , 
4, 0.648611, 1, 0, 0.76553,0.058469) , 
0, 2319.64, 1, 0, 0.483703,-0.00694467)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.220564,-0.0325759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608212,0.00717588) , 
1, 2.63646, 1, 0, 0.592497,0.0219636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320409,-0.00359862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.073719,-0.0285617) , 
2, 0.0240974, 1, 0, 0.171286,-0.0457607) , 
5, 15.9869, 1, 0, 0.501882,0.00739398)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654555,0.0165777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582996,-0.00127695) , 
4, 0.590725, 1, 0, 0.608907,0.0216698) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393519,0.00930171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153182,-0.0179264) , 
2, 0.00942665, 1, 0, 0.194448,-0.0360498) , 
5, 13.9823, 1, 0, 0.4951,0.00582043)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80766,0.0470468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790987,0.0065066) , 
0, 1243.6, 1, 0, 0.797951,0.0947249) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456321,0.00127385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.817049,0.0273408) , 
0, 2515.9, 1, 0, 0.486521,0.01189) , 
5, 1.58394, 1, 0, 0.515853,0.0196916)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478432,0.00431568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57956,-0.0083146) , 
4, 0.819936, 1, 0, 0.505158,0.00326841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464798,0.0324521) , 
4, 1.20068, 1, 0, 0.5036,0.00739976)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432766,0.00309967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401034,0.0545517) , 
2, 0.0702218, 1, 0, 0.427591,0.0373121) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467553,-0.00720087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.70942,0.00700196) , 
0, 1737.22, 1, 0, 0.548293,-0.0102782) , 
1, 3.97266, 1, 0, 0.508194,0.00553195)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541439,0.0215324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148564,-0.010958) , 
5, 20.6774, 1, 0, 0.382018,0.0385753) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620459,-0.00367822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351478,-0.0185729) , 
5, 7.64566, 1, 0, 0.547437,-0.029802) , 
4, 0.372877, 1, 0, 0.492251,-0.00699066)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415437,-0.0285533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653139,0.00397379) , 
1, 4.56637, 1, 0, 0.548231,-0.0413403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528177,0.00656525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269502,-0.0146757) , 
2, 0.111007, 1, 0, 0.512046,0.019921) , 
3, 0.043219, 1, 0, 0.517133,0.0113102)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695957,0.00694116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448322,-0.00483624) , 
2, 0.0166378, 1, 0, 0.541899,-0.00213578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271753,-0.028188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22298,-0.00905687) , 
2, 0.018594, 1, 0, 0.240051,-0.0597276) , 
3, 0.339461, 1, 0, 0.494492,-0.0111809)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678574,0.0115432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446037,-0.00985971) , 
4, 0.965598, 1, 0, 0.634113,0.0290207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222726,0.00142947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28083,-0.0170535) , 
1, 4.29701, 1, 0, 0.250492,-0.0274583) , 
5, 11.0704, 1, 0, 0.502251,0.00960712)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68486,0.000385036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.705178,0.0174499) , 
5, 2.19107, 1, 0, 0.696169,0.0381507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437867,-0.00100648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156573,-0.0410059) , 
4, 0.807371, 1, 0, 0.416478,-0.013882) , 
5, 4.79628, 1, 0, 0.509362,0.00339786)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.817149,0.0238567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468883,0.000226309) , 
5, 2.73976, 1, 0, 0.504239,0.00908637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690232,0.00193486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273332,-0.0265106) , 
5, 1.79783, 1, 0, 0.466338,-0.0480002) , 
4, 0.925907, 1, 0, 0.497701,-0.000761224)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502868,0.00280263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.79508,0.0300563) , 
4, 0.9262, 1, 0, 0.51887,0.0157027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189421,-0.041196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504941,-0.00218465) , 
0, 963.445, 1, 0, 0.408097,-0.0480848) , 
4, 0.984746, 1, 0, 0.504267,0.00729377)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396915,0.00145618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61439,0.0165589) , 
0, 1309.72, 1, 0, 0.448935,0.0194372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629389,-0.00984506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506965,0.014098) , 
3, 0.289237, 1, 0, 0.611681,-0.0206772) , 
1, 4.72772, 1, 0, 0.510268,0.00431964)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540711,-0.00203072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391039,0.0120889) , 
2, 0.05936, 1, 0, 0.512066,0.00213716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164522,-0.0444417) , 
2, 0.120258, 1, 0, 0.499403,-0.0035807)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.110191,-0.0262565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349971,0.0183879) , 
4, -0.0903443, 1, 0, 0.299816,0.0334301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580886,-0.00158978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248643,-0.0221668) , 
3, 0.364125, 1, 0, 0.537621,-0.0164093) , 
4, 0.155476, 1, 0, 0.49463,-0.00739915)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580941,0.00880828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136885,-0.014805) , 
5, 22.2701, 1, 0, 0.508484,0.0224654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614169,-0.0036913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200403,-0.033212) , 
2, 0.0647008, 1, 0, 0.517666,-0.0375003) , 
4, 0.866665, 1, 0, 0.510699,0.00799666)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418518,-0.0026424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164756,-0.0321012) , 
2, 0.020414, 1, 0, 0.277579,-0.0653283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559726,0.00344368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207237,-0.0222756) , 
3, 0.401164, 1, 0, 0.535488,0.00660381) , 
1, 3.36424, 1, 0, 0.494491,-0.00483046)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565729,-0.00109199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0947127,-0.0369169) , 
5, 31.9718, 1, 0, 0.546326,-0.00840498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490764,0.0381229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323965,0.00109287) , 
2, 0.0725936, 1, 0, 0.358347,0.0302407) , 
2, 0.0628949, 1, 0, 0.510009,-0.000938607)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569038,0.0122539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72771,-0.00056617) , 
0, 1161.33, 1, 0, 0.657673,0.0219956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328182,0.00294354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344015,-0.0169968) , 
4, 0.372781, 1, 0, 0.333955,-0.0167387) , 
5, 7.99332, 1, 0, 0.499999,0.00312919)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581575,0.00718689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401873,-0.00695392) , 
3, 0.11111, 1, 0, 0.463033,-0.00793332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776101,0.00956874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.86674,0.0441704) , 
3, 0.141761, 1, 0, 0.817206,0.0811286) , 
0, 2316.65, 1, 0, 0.508181,0.00341965)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573756,-0.0176161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68035,0.0134487) , 
2, 0.00255436, 1, 0, 0.669163,0.0362781) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54259,0.0038487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36686,-0.0099221) , 
3, 0.09256, 1, 0, 0.421544,-0.0203473) , 
2, 0.0147835, 1, 0, 0.500708,-0.00224395)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565603,-0.00842338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370658,-0.0479737) , 
3, 0.129697, 1, 0, 0.550195,-0.0430736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231012,-0.0183356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465772,0.00253903) , 
0, 821.097, 1, 0, 0.440928,0.00162293) , 
3, 0.141984, 1, 0, 0.488101,-0.0176739)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35677,0.00189447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497811,0.0292333) , 
1, 3.41371, 1, 0, 0.385483,0.0286785) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308684,-0.0245823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544469,-0.00197689) , 
1, 3.7981, 1, 0, 0.522066,-0.0150054) , 
1, 3.5478, 1, 0, 0.493701,-0.00593307)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.829589,0.034308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396927,-0.00161179) , 
5, 7.77707, 1, 0, 0.647769,0.071809) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410625,0.00379287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540567,-0.00827799) , 
4, 0.51115, 1, 0, 0.484123,-0.0119939) , 
3, 0.0246964, 1, 0, 0.497173,-0.00531079)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.188166,-0.0295227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281587,-0.0173734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535014,0.00200772) , 
0, 832.715, 1, 0, 0.508405,-8.69678e-05) , 
1, 2.71584, 1, 0, 0.491991,-0.0052631)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58336,0.014611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734806,0.000519644) , 
0, 1162.55, 1, 0, 0.667263,0.0288755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372967,-0.00207208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148259,-0.0382529) , 
4, 0.668803, 1, 0, 0.349925,-0.0187269) , 
5, 7.05866, 1, 0, 0.501242,0.00397143)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585679,0.000723538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336724,-0.0108359) , 
3, 0.253039, 1, 0, 0.509442,-0.0103392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374175,0.0316993) , 
4, 1.12348, 1, 0, 0.500912,-0.00362726)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534293,-0.00144464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381139,0.01846) , 
2, 0.0849871, 1, 0, 0.518889,0.00161765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319519,-0.0359569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307328,-0.00120161) , 
4, 1.11737, 1, 0, 0.312238,-0.0630347) , 
4, 1.02452, 1, 0, 0.49912,-0.00456733)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505937,-0.000585166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44666,0.0272853) , 
4, 1.14327, 1, 0, 0.50307,0.00259917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197874,-0.0260967) , 
2, 0.112858, 1, 0, 0.487733,-0.00183385)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458519,0.000399262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572104,-0.0222659) , 
1, 5.49939, 1, 0, 0.46442,-0.00275973) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734424,0.0242864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.810883,0.00953028) , 
4, 0.590965, 1, 0, 0.77727,0.0525284) , 
1, 5.73054, 1, 0, 0.503638,0.00417095)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42496,0.0103124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575602,-0.00409846) , 
4, 0.412774, 1, 0, 0.523645,0.00240638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44689,0.0350589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188781,0.00417765) , 
2, 0.0406996, 1, 0, 0.348229,0.0839647) , 
3, 0.395005, 1, 0, 0.506792,0.0102419)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238357,-0.0119978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554309,0.00745917) , 
4, 0.129199, 1, 0, 0.482264,0.0138381) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768584,0.0079524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447005,-0.0136373) , 
2, 0.014801, 1, 0, 0.55266,-0.0261519) , 
4, 0.78764, 1, 0, 0.50572,0.000513229)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603109,0.00344147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338314,-0.00858647) , 
2, 0.0351243, 1, 0, 0.502494,-0.0039975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427204,0.0419723) , 
4, 1.163, 1, 0, 0.499786,0.000843264)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510448,-0.00338668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218767,0.0280328) , 
5, 31.9726, 1, 0, 0.495195,-0.00855025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357922,0.0290326) , 
2, 0.123958, 1, 0, 0.488748,-0.0037708)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392197,0.000698762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57952,0.0166562) , 
1, 4.17224, 1, 0, 0.431211,0.0147333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619181,-0.00487908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362089,-0.0251973) , 
3, 0.240255, 1, 0, 0.55053,-0.0387954) , 
1, 4.44377, 1, 0, 0.488479,-0.0109585)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298581,-0.0236895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577692,-0.00102772) , 
1, 3.20389, 1, 0, 0.549064,-0.0128175) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474017,0.0151358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0857806,-0.0230269) , 
5, 15.9876, 1, 0, 0.376891,0.0330168) , 
3, 0.25922, 1, 0, 0.50197,-0.000280447)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686685,0.0439723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651486,0.00887487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367791,-0.00597559) , 
2, 0.0222015, 1, 0, 0.505857,0.00472833) , 
3, 0.0123537, 1, 0, 0.513734,0.0107871)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.11361,-0.0331303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583821,0.00116509) , 
4, -0.00208336, 1, 0, 0.553012,-0.00168644) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273594,-0.00193614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308985,-0.0273872) , 
1, 4.50419, 1, 0, 0.285475,-0.0392891) , 
3, 0.296282, 1, 0, 0.489665,-0.01059)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640457,0.00372894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95824,0.0483039) , 
1, 5.857, 1, 0, 0.678837,0.0279849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368447,0.000385848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432065,-0.0135158) , 
4, 0.491339, 1, 0, 0.393962,-0.019446) , 
5, 4.74485, 1, 0, 0.493648,-0.00284865)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356854,-0.0175247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661676,0.00399023) , 
1, 3.63274, 1, 0, 0.59637,-0.00374838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0644196,-0.0321431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460037,0.0170706) , 
4, 0.0567934, 1, 0, 0.395304,0.044257) , 
2, 0.0351237, 1, 0, 0.515785,0.0154916)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399937,0.00219291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636916,0.0271148) , 
0, 1295.78, 1, 0, 0.421606,0.0168835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679283,-0.00259199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457248,-0.0195367) , 
3, 0.234548, 1, 0, 0.618905,-0.0272301) , 
0, 1390.71, 1, 0, 0.498145,-0.000229803)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427751,0.00179461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67203,0.0125816) , 
1, 4.85103, 1, 0, 0.50853,0.0191801) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669396,0.00505331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235356,-0.0293488) , 
5, 2.57736, 1, 0, 0.497682,-0.0275288) , 
4, 0.886109, 1, 0, 0.506273,0.00946126)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422031,-0.00156814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633316,0.0136003) , 
1, 4.88067, 1, 0, 0.474295,0.00773542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523572,-0.0399897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743801,-0.00351612) , 
1, 5.43092, 1, 0, 0.683184,-0.0468644) , 
0, 2148.52, 1, 0, 0.505386,-0.000391142)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396547,0.0026086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481694,-0.0126593) , 
0, 1186, 1, 0, 0.42101,-0.00697094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684937,0.0152579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670822,-0.0113526) , 
4, 0.824045, 1, 0, 0.680805,0.0275886) , 
0, 1534.82, 1, 0, 0.500874,0.00365302)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512516,0.00312594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539171,-0.00657625) , 
4, 0.689201, 1, 0, 0.524746,-0.00465739) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456001,0.0550759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0838713,-0.00134144) , 
2, 0.0243178, 1, 0, 0.230386,0.0749181) , 
5, 25.8178, 1, 0, 0.496674,0.00293147)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620177,0.00849295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296046,-0.0110909) , 
3, 0.425897, 1, 0, 0.600205,0.0265334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29902,-0.00274424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365341,-0.0262273) , 
1, 5.18336, 1, 0, 0.311558,-0.0264414) , 
2, 0.0462463, 1, 0, 0.512847,0.0105007)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567353,-0.00542088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444426,-0.0254554) , 
3, 0.158288, 1, 0, 0.548276,-0.0307797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25023,0.0570836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421341,0.000732976) , 
4, -0.022277, 1, 0, 0.407425,0.0117527) , 
3, 0.191367, 1, 0, 0.486556,-0.0121423)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486786,0.00846273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624969,-0.005047) , 
1, 4.24653, 1, 0, 0.56572,0.00412674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131547,-0.0144682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102073,-0.0385282) , 
4, 0.155216, 1, 0, 0.123271,-0.0571642) , 
5, 19.575, 1, 0, 0.498493,-0.00518603)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.127726,-0.0338771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.112455,-0.0177306) , 
3, 0.173482, 1, 0, 0.120029,-0.0638512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398627,0.015766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542128,-0.00143496) , 
4, 0.170834, 1, 0, 0.525042,0.00171458) , 
4, -0.00240873, 1, 0, 0.491789,-0.0036685)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.260576,-0.0313961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22559,-0.00425863) , 
2, 0.0166713, 1, 0, 0.239389,-0.0592753) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546522,0.00369785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186742,-0.025795) , 
3, 0.407377, 1, 0, 0.520729,0.00596475) , 
1, 3.02589, 1, 0, 0.494362,-0.000149533)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334467,0.00397511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603044,0.0482222) , 
1, 3.36142, 1, 0, 0.388766,0.0470879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562021,-0.00657768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347169,0.00694315) , 
3, 0.290109, 1, 0, 0.517809,-0.0134842) , 
1, 3.51115, 1, 0, 0.490987,-0.000893993)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703453,0.00476138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382544,-0.00726964) , 
5, 6.52877, 1, 0, 0.525247,-0.00703538) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333132,0.0870794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348241,0.00798726) , 
4, 0.156871, 1, 0, 0.345282,0.0609701) , 
3, 0.345636, 1, 0, 0.496998,0.0036395)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51269,0.034314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652593,0.00468977) , 
1, 2.89636, 1, 0, 0.639997,0.0281198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326362,-0.00331814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441886,-0.0273835) , 
0, 2009.98, 1, 0, 0.340438,-0.0235087) , 
2, 0.0277478, 1, 0, 0.502434,0.00441106)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451682,0.00404642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598238,-0.00715714) , 
1, 4.82857, 1, 0, 0.49975,0.00193347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.909383,0.0511439) , 
1, 6.49261, 1, 0, 0.517796,0.00842881)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727812,0.0119962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322899,-0.0104545) , 
3, 0.376304, 1, 0, 0.689425,0.0350111) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388098,-0.000919203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309285,-0.0252454) , 
4, 0.62946, 1, 0, 0.371502,-0.0216855) , 
5, 5.43577, 1, 0, 0.48949,-0.000644075)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512755,-0.000161582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513303,-0.0110077) , 
4, 0.925907, 1, 0, 0.512845,-0.00710378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45265,0.0260056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239373,0.00747752) , 
3, 0.191327, 1, 0, 0.350811,0.0583974) , 
2, 0.105457, 1, 0, 0.501445,-0.0024953)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305507,0.00516727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596227,0.0442527) , 
0, 1092.96, 1, 0, 0.398114,0.0698372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756017,0.0125858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455961,-0.0047955) , 
5, 2.79785, 1, 0, 0.51713,-0.00487514) , 
1, 2.99228, 1, 0, 0.505403,0.00248636)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731888,0.0130978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461585,-0.0058793) , 
3, 0.240716, 1, 0, 0.646077,0.0235586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448774,-0.0202512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365808,-0.000180272) , 
2, 0.0332295, 1, 0, 0.385331,-0.0182038) , 
2, 0.0221982, 1, 0, 0.506494,0.00120227)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643372,-0.00219905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450496,-0.0422278) , 
2, 0.0147964, 1, 0, 0.622139,-0.0239546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40906,0.0126774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528421,-0.00325812) , 
1, 4.99834, 1, 0, 0.442346,0.0290897) , 
2, 0.0166511, 1, 0, 0.508503,0.00957139)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold4::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold4::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
