// Class: ReadBDT-0.3_fold3
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold3
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.30/04       [400900]
Creator        : b78499db
Date           : Thu Mar 21 15:54:50 2024
Host           : Darwin Sonoma-arm64.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:43:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis
Training events: 32221
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.003479004,8696.23632812]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.00020766258,8.59782600403]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [1.25554126264e-18,0.149860098958]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [9.20502588997e-06,0.499961167574]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.39996659756]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000704350823071,129.481124878]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [84,1159527808]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold3Node

#ifndef BDT-0.3_fold3Node__def
#define BDT-0.3_fold3Node__def

class BDT-0.3_fold3Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold3Node ( BDT-0.3_fold3Node* left,BDT-0.3_fold3Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold3Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold3Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold3Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold3Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold3Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold3Node::~BDT-0.3_fold3Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold3Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold3Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold3 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold3( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold3" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold3() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold3Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold3::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold3Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold3Node*)current->GetRight();
         else current=(BDT-0.3_fold3Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold3::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702189,0.0404379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455832,-0.00883366) , 
3, 0.253045, 1, 0, 0.62616,0.12616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390218,-0.0219564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145768,-0.0708463) , 
2, 0.0240481, 1, 0, 0.24737,-0.25263) , 
5, 11.0711, 1, 0, 0.499266,-0.000733957)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638286,0.0254519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337815,-0.030923) , 
3, 0.296253, 1, 0, 0.568451,0.0616028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.129589,-0.0692138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395591,-0.0166214) , 
0, 1718.09, 1, 0, 0.189455,-0.285994) , 
5, 15.7792, 1, 0, 0.487779,-0.0123857)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460227,-0.00959634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736662,0.0444615) , 
0, 1369.7, 1, 0, 0.570684,0.0598264) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321699,-0.0282802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0947556,-0.0695448) , 
2, 0.0204722, 1, 0, 0.175449,-0.270322) , 
5, 17.2128, 1, 0, 0.494183,-0.00407658)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74117,0.0428654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498953,-0.00511156) , 
2, 0.0276496, 1, 0, 0.642566,0.115983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392044,-0.0170021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2046,-0.0488108) , 
2, 0.0221753, 1, 0, 0.279369,-0.177101) , 
5, 9.51208, 1, 0, 0.494786,-0.00326887)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676304,0.0266765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344295,-0.0295131) , 
3, 0.320939, 1, 0, 0.618983,0.0837847) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142926,-0.0566229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364676,-0.0155986) , 
0, 1120.63, 1, 0, 0.258199,-0.171021) , 
5, 11.0718, 1, 0, 0.493628,-0.00474796)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665431,0.0254158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423656,-0.017921) , 
2, 0.044403, 1, 0, 0.596998,0.0646201) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33172,-0.0203243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0933211,-0.0602131) , 
2, 0.024005, 1, 0, 0.188232,-0.208411) , 
5, 14.1167, 1, 0, 0.491164,-0.00607101)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469199,-0.0104369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685717,0.0276145) , 
1, 4.20137, 1, 0, 0.596822,0.0586495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147624,-0.0476559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372085,-0.00786696) , 
0, 1596.97, 1, 0, 0.202527,-0.175301) , 
5, 14.2345, 1, 0, 0.493283,-0.00278443)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752599,0.0360881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470474,-0.00135266) , 
5, 6.84197, 1, 0, 0.620793,0.0902317) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441758,-0.0116558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0678096,-0.0573604) , 
5, 18.8128, 1, 0, 0.363827,-0.0966653) , 
2, 0.0277519, 1, 0, 0.504203,0.00543333)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531197,0.0030245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296631,-0.0296375) , 
2, 0.0258979, 1, 0, 0.407115,-0.0667861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729116,0.0363158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460061,-0.00349674) , 
2, 0.0406003, 1, 0, 0.658974,0.124297) , 
0, 1417.06, 1, 0, 0.502498,0.00558032)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683385,0.0220729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334834,-0.0332418) , 
2, 0.0720543, 1, 0, 0.634049,0.0680323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.134073,-0.0495328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354983,-0.0136875) , 
0, 972.398, 1, 0, 0.281576,-0.115995) , 
5, 9.59161, 1, 0, 0.492384,-0.00593173)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421286,-0.00867493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234737,-0.0534063) , 
4, 1.06433, 1, 0, 0.405807,-0.0589457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83958,0.0470849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54113,0.00694231) , 
5, 5.48342, 1, 0, 0.672596,0.115269) , 
0, 1436.76, 1, 0, 0.50517,0.00593842)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651125,0.0204618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199284,-0.0290224) , 
5, 18.3509, 1, 0, 0.574742,0.060255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246363,-0.0374951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552582,0.007291) , 
0, 1617.01, 1, 0, 0.296978,-0.14072) , 
3, 0.283933, 1, 0, 0.506477,0.010862)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415699,-0.0108245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191708,-0.0421323) , 
3, 0.296237, 1, 0, 0.345428,-0.0949099) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668501,0.0231333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175394,-0.0372725) , 
5, 20.5603, 1, 0, 0.598968,0.0706251) , 
0, 1079.06, 1, 0, 0.497209,0.00418689)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705358,0.0233031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445495,-0.0132211) , 
3, 0.234555, 1, 0, 0.61611,0.0500275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373196,-0.00485269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151509,-0.0377443) , 
2, 0.0168392, 1, 0, 0.216128,-0.116933) , 
5, 12.6532, 1, 0, 0.499549,0.00137272)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458023,-0.00821958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218422,-0.0439345) , 
2, 0.0129361, 1, 0, 0.294289,-0.148089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639938,0.0161246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198247,-0.0233897) , 
5, 16.9394, 1, 0, 0.560409,0.0450717) , 
1, 3.45356, 1, 0, 0.51009,0.00854788)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466253,-0.00931389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702955,0.0212983) , 
0, 1079.84, 1, 0, 0.613382,0.0444541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.110876,-0.0438683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290572,-0.0119154) , 
1, 4.62955, 1, 0, 0.176303,-0.129885) , 
5, 14.2339, 1, 0, 0.501483,-0.000179161)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66755,0.0207839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308984,-0.0330629) , 
3, 0.382679, 1, 0, 0.628862,0.0674625) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383972,-0.0118474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291629,-0.0446556) , 
4, 1.04431, 1, 0, 0.372064,-0.0724949) , 
2, 0.0240516, 1, 0, 0.504035,-0.000569523)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.750004,0.0338547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46893,0.00246838) , 
2, 0.0314045, 1, 0, 0.632482,0.0920922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343097,-0.0205024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648031,0.0153366) , 
0, 1471.82, 1, 0, 0.442641,-0.0391359) , 
3, 0.104949, 1, 0, 0.504723,0.00377858)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590235,0.00528564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.828236,0.0375533) , 
1, 4.85243, 1, 0, 0.677885,0.0752024) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402729,-0.005175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22898,-0.0582818) , 
4, 0.708539, 1, 0, 0.382,-0.05245) , 
5, 5.48158, 1, 0, 0.501514,-0.000888604)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745415,0.0239329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39804,-0.0196953) , 
3, 0.29609, 1, 0, 0.677401,0.06737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390219,-0.00476046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19721,-0.0605121) , 
4, 0.688665, 1, 0, 0.369947,-0.0478469) , 
5, 6.32793, 1, 0, 0.502044,0.00165596)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684324,0.0198922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395582,-0.0113089) , 
3, 0.271534, 1, 0, 0.610051,0.0516727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501256,-0.00323697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188014,-0.0307956) , 
5, 9.01562, 1, 0, 0.346528,-0.0679556) , 
2, 0.0314265, 1, 0, 0.494554,-0.000757863)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316411,-0.0302207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622902,0.0123732) , 
1, 3.13189, 1, 0, 0.586216,0.0313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359742,-0.00541626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278685,-0.0402475) , 
4, 0.886405, 1, 0, 0.339141,-0.0646385) , 
2, 0.0407027, 1, 0, 0.500248,-0.00208105)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776419,0.0264268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45909,-0.00850116) , 
3, 0.271445, 1, 0, 0.698446,0.0756151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420717,-0.0052023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18087,-0.0597344) , 
4, 0.827291, 1, 0, 0.399314,-0.0441019) , 
5, 4.23501, 1, 0, 0.489554,-0.00798646)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368901,-0.0161861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626017,0.0129078) , 
0, 996.797, 1, 0, 0.552989,0.0197269) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209103,-0.0309233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500577,-0.00494125) , 
0, 1594.03, 1, 0, 0.268027,-0.108774) , 
3, 0.296259, 1, 0, 0.481487,-0.0125164)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639894,0.0093974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349727,-0.012741) , 
5, 5.64724, 1, 0, 0.459374,-0.0178145) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.866542,0.0452763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619966,0.0147329) , 
2, 0.0221426, 1, 0, 0.764433,0.134295) , 
0, 2221.68, 1, 0, 0.494679,-0.000210557)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492658,-0.00705142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165059,-0.0332136) , 
5, 7.18885, 1, 0, 0.327348,-0.0798931) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617689,0.0109099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183853,-0.0217739) , 
5, 20.5587, 1, 0, 0.556798,0.0299349) , 
0, 914.913, 1, 0, 0.505623,0.00543943)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587029,0.00184191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301979,-0.0170666) , 
5, 5.73784, 1, 0, 0.40949,-0.0409848) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709202,0.0236316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614112,-0.0164224) , 
4, 0.945164, 1, 0, 0.692051,0.0700496) , 
0, 1681.38, 1, 0, 0.484829,-0.0113798)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684687,0.0143523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339362,-0.00999424) , 
5, 7.90761, 1, 0, 0.50889,0.00954884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541228,-0.0131174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216865,-0.0448387) , 
5, 3.04285, 1, 0, 0.343883,-0.141262) , 
4, 1.0444, 1, 0, 0.493397,-0.00461064)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625642,0.0217623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593503,-0.000565204) , 
4, 0.591504, 1, 0, 0.60522,0.0343467) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30922,-0.00567394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0937324,-0.032814) , 
2, 0.0222295, 1, 0, 0.180099,-0.0697896) , 
5, 15.8152, 1, 0, 0.509402,0.0108753)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583443,0.00784795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280488,-0.026277) , 
2, 0.0795554, 1, 0, 0.54205,0.0135237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20771,-0.00996521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218361,-0.0400635) , 
4, 0.373104, 1, 0, 0.214804,-0.131621) , 
3, 0.364129, 1, 0, 0.501606,-0.00441427)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455012,-0.00441754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717846,0.0213063) , 
0, 997.655, 1, 0, 0.644942,0.0585271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401293,-0.000356896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282178,-0.0364947) , 
4, 0.98516, 1, 0, 0.380002,-0.0300774) , 
2, 0.0240516, 1, 0, 0.512074,0.0140918)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692289,0.0111348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363787,-0.00925091) , 
5, 7.9084, 1, 0, 0.544295,0.00851416) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243858,-0.0132518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212057,-0.0382635) , 
1, 3.93273, 1, 0, 0.22693,-0.112311) , 
3, 0.364174, 1, 0, 0.503322,-0.00708493)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408805,-0.0206178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73543,0.0182701) , 
1, 3.06236, 1, 0, 0.704899,0.0596418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419926,0.00035569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276911,-0.0392917) , 
4, 0.6887, 1, 0, 0.397484,-0.0247075) , 
5, 5.15115, 1, 0, 0.509546,0.00604014)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520213,0.00774021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354457,-0.0103239) , 
3, 0.117278, 1, 0, 0.408882,-0.0182393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67704,0.0186936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535766,-0.0132941) , 
4, 1.00295, 1, 0, 0.663363,0.0636373) , 
0, 1325.87, 1, 0, 0.51231,0.0150378)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697806,0.0135339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217564,-0.0191775) , 
5, 14.2354, 1, 0, 0.579419,0.0251309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699663,0.0266662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385537,-0.0120247) , 
5, 1.37227, 1, 0, 0.410771,-0.0361356) , 
3, 0.154323, 1, 0, 0.48943,-0.00756053)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626508,0.0127236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415944,-0.0266442) , 
4, 1.04459, 1, 0, 0.607141,0.0364499) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374861,-0.0132929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794625,0.0319561) , 
1, 5.7761, 1, 0, 0.412018,-0.0387356) , 
3, 0.160471, 1, 0, 0.506007,-0.0025195)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498329,-0.000609095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733137,0.0216039) , 
0, 1492.27, 1, 0, 0.583989,0.0285271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500661,-0.00046816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23072,-0.0219574) , 
5, 6.72084, 1, 0, 0.348385,-0.0484961) , 
3, 0.23453, 1, 0, 0.498668,0.000634009)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440094,-0.0061696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.709686,0.0158955) , 
0, 1044.31, 1, 0, 0.619562,0.0328608) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361908,-0.00579935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33078,-0.0244186) , 
4, 0.905946, 1, 0, 0.354264,-0.0430439) , 
2, 0.029602, 1, 0, 0.501158,-0.00101599)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267964,-0.0175593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.070409,-0.0424073) , 
5, 24.6219, 1, 0, 0.157802,-0.099381) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302544,-0.0201652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580099,0.00953867) , 
1, 3.22216, 1, 0, 0.545841,0.0241043) , 
4, 0.0370463, 1, 0, 0.505965,0.0114146)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740225,0.0151877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368719,-0.00443013) , 
5, 11.186, 1, 0, 0.627949,0.036131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630413,0.0185821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31191,-0.014497) , 
5, 2.05579, 1, 0, 0.348143,-0.0408705) , 
2, 0.029602, 1, 0, 0.505574,0.00245383)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695728,0.0162609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198893,-0.0191117) , 
5, 18.9841, 1, 0, 0.621635,0.0459354) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408266,-0.00783284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795934,0.0238035) , 
0, 2363, 1, 0, 0.442192,-0.0211134) , 
3, 0.104946, 1, 0, 0.503579,0.0018237)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372978,-0.0210877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654124,0.0132578) , 
1, 3.38798, 1, 0, 0.614332,0.0318656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62498,0.0250638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346535,-0.014915) , 
2, 0.0074005, 1, 0, 0.384433,-0.0368918) , 
3, 0.185172, 1, 0, 0.505507,-0.000681431)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48815,0.00198156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.875061,0.0441721) , 
0, 3104.44, 1, 0, 0.504603,0.0144664) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71871,0.000780231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338533,-0.0314645) , 
2, 0.0222959, 1, 0, 0.501874,-0.0747834) , 
4, 0.886319, 1, 0, 0.504033,-0.00416359)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561162,0.00572024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0777013,-0.0453193) , 
5, 33.2103, 1, 0, 0.540681,0.0158434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25277,0.000822318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194398,-0.0310329) , 
1, 3.6327, 1, 0, 0.21375,-0.0795356) , 
3, 0.376468, 1, 0, 0.501521,0.00441896)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.835615,0.0327184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53613,0.00191834) , 
5, 1.58394, 1, 0, 0.568397,0.0203396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308876,-0.00349779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228187,-0.0390596) , 
4, 0.8658, 1, 0, 0.289033,-0.0495677) , 
3, 0.29628, 1, 0, 0.505431,0.00458323)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697617,0.012516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478739,-0.0102553) , 
4, 1.00775, 1, 0, 0.658921,0.0337979) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316848,-0.00489095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243695,-0.0410508) , 
4, 0.511078, 1, 0, 0.303839,-0.0448234) , 
5, 8.6064, 1, 0, 0.502264,-0.000888748)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.812604,0.0201019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532363,0.000852009) , 
5, 4.54931, 1, 0, 0.636678,0.0280755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373265,-0.00180499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474594,-0.0164271) , 
4, 0.64949, 1, 0, 0.416896,-0.0322383) , 
2, 0.014801, 1, 0, 0.488801,-0.0125057)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611325,0.0103499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425123,-0.0092192) , 
4, 0.985277, 1, 0, 0.581033,0.0293506) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370492,0.00783536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121163,-0.0236072) , 
2, 0.0130428, 1, 0, 0.176084,-0.0454248) , 
5, 18.9789, 1, 0, 0.511716,0.0165509)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44056,-0.000223883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.721025,0.0212296) , 
1, 5.23507, 1, 0, 0.499721,0.0157204) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599835,-0.00749757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0992541,-0.0511462) , 
5, 4.41723, 1, 0, 0.483729,-0.0650184) , 
4, 0.886428, 1, 0, 0.496332,-0.00139139)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721473,0.020209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312207,-0.00375388) , 
5, 9.59859, 1, 0, 0.448881,0.0180343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654239,0.000830678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345932,-0.0272958) , 
5, 4.9379, 1, 0, 0.561534,-0.0302127) , 
4, 0.669282, 1, 0, 0.497416,-0.00275213)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.754609,0.0248343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350182,2.07562e-05) , 
5, 8.5789, 1, 0, 0.490519,0.0345268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618847,-0.00248753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18859,-0.0388129) , 
5, 5.38808, 1, 0, 0.544075,-0.0319811) , 
4, 0.768335, 1, 0, 0.508966,0.0116185)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614663,0.00965553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790417,0.0474741) , 
3, 0.0822905, 1, 0, 0.634916,0.052535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631786,0.00996918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373567,-0.0110155) , 
2, 0.0129356, 1, 0, 0.448523,-0.0181993) , 
3, 0.0925922, 1, 0, 0.50452,0.00305095)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253225,-0.0361973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240888,-0.00668881) , 
2, 0.0367058, 1, 0, 0.248656,-0.0996295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684109,0.00940244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439946,-0.00556697) , 
2, 0.0147889, 1, 0, 0.517257,-0.0034631) , 
1, 2.97768, 1, 0, 0.492174,-0.0124435)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614895,0.00940463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423522,-0.00504798) , 
3, 0.111137, 1, 0, 0.489826,-0.000444584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.835263,0.0338855) , 
1, 6.26073, 1, 0, 0.508725,0.00578312)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527062,0.00143067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.924792,0.0544548) , 
0, 3266.88, 1, 0, 0.540368,0.0114698) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0977138,-0.0210397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0822573,-0.0458514) , 
0, 1195.19, 1, 0, 0.0901798,-0.0999549) , 
5, 27.2521, 1, 0, 0.503349,0.00230741)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743001,0.0200132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380266,-0.00126663) , 
5, 7.16637, 1, 0, 0.485706,0.0191941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718925,0.0152698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47623,-0.0183254) , 
5, 1.64188, 1, 0, 0.546671,-0.0320814) , 
4, 0.787824, 1, 0, 0.505215,0.00278594)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505298,-0.00209209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.767885,0.0218153) , 
0, 1048.6, 1, 0, 0.685079,0.0507491) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455201,6.62432e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467273,-0.0141011) , 
4, 0.82707, 1, 0, 0.458814,-0.0163805) , 
2, 0.00925062, 1, 0, 0.502956,-0.00328438)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.846716,0.0348902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.679731,0.00752152) , 
4, 0.868434, 1, 0, 0.726669,0.0552776) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455841,-0.001881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327907,-0.0276799) , 
4, 0.846792, 1, 0, 0.440549,-0.0188906) , 
5, 2.87101, 1, 0, 0.501422,-0.0031112)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677961,0.0185279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34807,-0.0107539) , 
5, 1.43675, 1, 0, 0.378165,-0.02984) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564674,0.0174909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69337,-0.000231709) , 
4, 0.49179, 1, 0, 0.64086,0.0273492) , 
0, 1240.51, 1, 0, 0.500695,-0.00316492)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676103,0.00934219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320201,-0.00401404) , 
5, 9.48899, 1, 0, 0.526698,0.0146197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21056,-0.0312458) , 
2, 0.116558, 1, 0, 0.5139,0.00946074)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628559,0.0145869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587418,-0.00296024) , 
4, 0.590496, 1, 0, 0.603028,0.0156831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196099,-0.00747557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125654,-0.0368476) , 
4, 0.313009, 1, 0, 0.183262,-0.0407883) , 
5, 15.5265, 1, 0, 0.509257,0.00306801)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727443,0.00762573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233081,-0.0122387) , 
5, 14.2398, 1, 0, 0.597877,0.00894325) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713996,0.0172573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419479,-0.01051) , 
5, 1.37072, 1, 0, 0.447097,-0.0294611) , 
3, 0.0925829, 1, 0, 0.490371,-0.0184392)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309449,-0.0261263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273428,0.00187103) , 
3, 0.259268, 1, 0, 0.296087,-0.0626125) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721701,0.0105613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420981,-0.0033177) , 
5, 5.43747, 1, 0, 0.534964,0.00698317) , 
1, 3.3038, 1, 0, 0.501641,-0.00272544)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487518,-0.00465141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737019,0.0131399) , 
1, 3.77827, 1, 0, 0.669736,0.0296217) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363874,0.00148059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317094,-0.0304198) , 
4, 0.491584, 1, 0, 0.35163,-0.0265899) , 
5, 7.17212, 1, 0, 0.506826,0.000834376)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565148,0.00446288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260827,-0.0154484) , 
3, 0.29629, 1, 0, 0.494634,-0.000435271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488386,-0.0313766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401255,0.00581504) , 
3, 0.228463, 1, 0, 0.459651,-0.0701859) , 
4, 0.926012, 1, 0, 0.488273,-0.0131188)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760891,0.0120368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475141,-0.00194187) , 
5, 4.23652, 1, 0, 0.560911,0.0078654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.301588,0.0150546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268082,-0.0186224) , 
1, 3.46064, 1, 0, 0.275984,-0.0409428) , 
3, 0.296277, 1, 0, 0.495253,-0.00338171)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706352,0.0130003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317771,-0.0243165) , 
2, 0.0868242, 1, 0, 0.670451,0.0350112) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343392,0.00143121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343456,-0.0246588) , 
4, 0.451834, 1, 0, 0.343412,-0.0256341) , 
5, 7.05787, 1, 0, 0.501048,0.00359754)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618735,0.0067178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168578,-0.0129868) , 
5, 17.3974, 1, 0, 0.524768,0.0127809) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540418,-0.00724863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0525818,-0.0506391) , 
5, 4.51677, 1, 0, 0.363097,-0.0677689) , 
4, 1.00482, 1, 0, 0.507494,0.00417461)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493101,-0.00454235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366242,0.0201614) , 
2, 0.0573539, 1, 0, 0.463146,0.00273153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488403,-0.0406216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.709406,-0.00433635) , 
0, 1985.86, 1, 0, 0.613422,-0.0725619) , 
1, 5.36325, 1, 0, 0.494452,-0.0129538)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352124,-0.0352763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268613,-0.00893547) , 
5, 4.56364, 1, 0, 0.295032,-0.0717605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558585,0.00332915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209733,-0.0204584) , 
3, 0.382707, 1, 0, 0.519105,0.0026298) , 
1, 3.21167, 1, 0, 0.491002,-0.00670012)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.162953,-0.0306864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603791,0.00632415) , 
4, -0.0415104, 1, 0, 0.581249,0.0178675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320027,0.00324874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31315,-0.0278443) , 
4, 0.668803, 1, 0, 0.317068,-0.0411438) , 
3, 0.253062, 1, 0, 0.497532,-0.000832667)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361477,0.0109974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536794,-0.00454146) , 
4, 0.373181, 1, 0, 0.479235,0.000495218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774635,0.0127423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.816763,0.0402168) , 
3, 0.141833, 1, 0, 0.794255,0.0866122) , 
0, 2313.04, 1, 0, 0.516184,0.010596)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66218,0.0152482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238212,-0.00581859) , 
5, 13.8709, 1, 0, 0.48995,0.0284336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655573,0.0022612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273313,-0.0332278) , 
5, 5.30117, 1, 0, 0.571587,-0.0196002) , 
4, 0.688878, 1, 0, 0.52421,0.0082756)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555583,0.00138042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459168,0.0244063) , 
2, 0.0638286, 1, 0, 0.54874,0.0111647) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270198,-0.00242772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250326,-0.025166) , 
4, 0.609413, 1, 0, 0.261365,-0.0452635) , 
2, 0.0795436, 1, 0, 0.510263,0.00360946)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702023,-0.00367469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666459,0.0230295) , 
3, 0.12393, 1, 0, 0.679937,0.0512209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235232,-0.0186708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495516,-0.000777454) , 
1, 3.28411, 1, 0, 0.45836,-0.0118921) , 
2, 0.0074005, 1, 0, 0.492244,-0.00224097)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41389,-0.0212751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653953,0.0012274) , 
1, 4.22676, 1, 0, 0.561018,-0.0286652) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333058,0.0290092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484751,0.0006005) , 
4, 0.174877, 1, 0, 0.453289,0.0195971) , 
3, 0.13579, 1, 0, 0.498062,-0.000461046)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601604,-0.00219188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454925,0.00869138) , 
3, 0.172832, 1, 0, 0.530192,0.0119839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0904869,-0.0335334) , 
5, 31.6289, 1, 0, 0.507793,0.00668984)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575255,-0.0204883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5035,-0.000860761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0791494,-0.0321002) , 
5, 31.0534, 1, 0, 0.480207,-0.00744937) , 
2, 0.0036997, 1, 0, 0.485294,-0.0109743)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321547,-0.001779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289953,-0.0297344) , 
1, 3.81925, 1, 0, 0.306839,-0.0548897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481332,0.00565709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620841,-0.00488765) , 
4, 0.570725, 1, 0, 0.553349,0.00101128) , 
0, 914.538, 1, 0, 0.496875,-0.0117955)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527463,0.0119965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656873,-0.00180161) , 
4, 0.590416, 1, 0, 0.594083,0.0183468) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24802,0.0381495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325026,-0.0136912) , 
4, 0.076593, 1, 0, 0.314698,-0.0329406) , 
3, 0.253054, 1, 0, 0.508635,0.00266083)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720294,-0.0143103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.780189,0.0378505) , 
3, 0.172502, 1, 0, 0.748871,0.04649) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356429,-0.00952273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624894,0.0035394) , 
0, 1338.61, 1, 0, 0.462912,-0.0162984) , 
5, 1.43499, 1, 0, 0.492415,-0.00982034)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530602,-0.0280923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522171,-0.000385706) , 
3, 0.0123524, 1, 0, 0.522524,-0.00559872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155436,-0.0138302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48213,0.0344807) , 
4, 0.273853, 1, 0, 0.382095,0.0773007) , 
2, 0.0850931, 1, 0, 0.505449,0.00448117)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689886,0.0127495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415999,0.00232008) , 
2, 0.0240324, 1, 0, 0.549609,0.0267006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.204262,0.00548881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250286,-0.0255399) , 
0, 1078.39, 1, 0, 0.225018,-0.0366635) , 
3, 0.413507, 1, 0, 0.526848,0.0222575)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322757,-0.0144559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576437,0.00495374) , 
0, 832.268, 1, 0, 0.545703,0.00958722) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0190512,-0.0524021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189117,-0.00725007) , 
4, -0.0224144, 1, 0, 0.124528,-0.0585951) , 
5, 25.3028, 1, 0, 0.504627,0.00293751)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576998,0.0353517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406624,0.00171726) , 
3, 0.0247931, 1, 0, 0.419348,0.0159258) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716394,0.00326005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377022,-0.0189165) , 
2, 0.0313378, 1, 0, 0.573621,-0.0241611) , 
1, 4.46512, 1, 0, 0.493065,-0.00322915)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687662,-0.00393409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519295,0.015) , 
2, 0.0425182, 1, 0, 0.646283,0.00461352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336206,-0.00171835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292584,-0.028847) , 
4, 0.451606, 1, 0, 0.324371,-0.033693) , 
5, 7.90761, 1, 0, 0.494187,-0.0134855)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447165,-0.00411194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.679728,0.00925827) , 
4, 0.761666, 1, 0, 0.496742,-0.00463477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463783,-0.023916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330347,0.00795557) , 
3, 0.308588, 1, 0, 0.435915,-0.060308) , 
4, 0.94566, 1, 0, 0.487271,-0.013303)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448551,-0.00305639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.7422,0.0150844) , 
0, 1945.04, 1, 0, 0.487057,-0.00314614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656377,-0.0305907) , 
0, 2810.14, 1, 0, 0.497301,-0.00862648)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.777247,0.00831793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484892,-0.00844487) , 
5, 2.71906, 1, 0, 0.543876,-0.0191202) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331818,0.0127672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420809,-0.0119437) , 
1, 4.84761, 1, 0, 0.35284,0.0222703) , 
3, 0.271588, 1, 0, 0.489487,-0.00733611)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45896,-0.00492704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725477,0.00799121) , 
0, 1243.64, 1, 0, 0.589848,0.0035333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194614,-0.00169608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0624792,-0.0483078) , 
4, 0.274084, 1, 0, 0.163748,-0.03523) , 
5, 15.8152, 1, 0, 0.495593,-0.0050413)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504984,0.0151655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661166,-0.000453027) , 
4, 0.489478, 1, 0, 0.598553,0.0206587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452098,-0.0242804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418526,-0.00331937) , 
3, 0.149539, 1, 0, 0.42362,-0.024076) , 
3, 0.111107, 1, 0, 0.482448,-0.00903223)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478502,-0.0117477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.781567,0.0118646) , 
1, 5.09563, 1, 0, 0.561846,-0.0227918) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0664426,-0.0390465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447462,0.0108871) , 
4, 0.0370413, 1, 0, 0.395143,0.0243302) , 
2, 0.0333022, 1, 0, 0.494114,-0.00364581)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.134407,-0.0109598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173925,-0.0287835) , 
1, 3.92319, 1, 0, 0.161852,-0.0675662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566957,0.00403489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420907,0.0322403) , 
2, 0.105457, 1, 0, 0.558807,0.0202372) , 
4, 0.037415, 1, 0, 0.518997,0.0114316)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307525,-0.0217528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289934,0.0139852) , 
3, 0.29015, 1, 0, 0.301747,-0.0416508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613349,0.00613356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337417,-0.00531064) , 
2, 0.0517621, 1, 0, 0.544435,0.012151) , 
1, 3.38525, 1, 0, 0.505836,0.00359392)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517594,0.00174176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388372,-0.0404953) , 
4, 1.02313, 1, 0, 0.512625,-0.000385362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667472,0.0374271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242762,0.0186169) , 
2, 0.0576397, 1, 0, 0.472167,0.0991858) , 
4, 1.10363, 1, 0, 0.509845,0.00645662)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468224,0.0172522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62959,-0.00405913) , 
4, 0.353606, 1, 0, 0.580647,0.00889696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328235,-0.0179328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302677,-0.00299536) , 
2, 0.0622202, 1, 0, 0.312988,-0.0333596) , 
2, 0.0406702, 1, 0, 0.490495,-0.0053357)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451845,0.00115087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592016,-0.0191623) , 
1, 5.39083, 1, 0, 0.4765,-0.00797831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.871367,0.0319899) , 
0, 3306.12, 1, 0, 0.491103,-0.00422846)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45596,0.0108659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157912,-0.0203501) , 
3, 0.425895, 1, 0, 0.429999,0.0319205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726592,0.00422547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358247,-0.0122254) , 
5, 9.13957, 1, 0, 0.579641,-0.00973013) , 
1, 4.26095, 1, 0, 0.513885,0.00857222)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633546,0.0293988) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645217,0.00478491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282152,-0.00697101) , 
5, 9.48899, 1, 0, 0.504449,0.00190803) , 
3, 0.0185206, 1, 0, 0.512736,0.00810147)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.766187,0.0299308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708428,0.00470961) , 
5, 0.654897, 1, 0, 0.733195,0.0590348) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319069,-0.0113544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549049,-0.00113372) , 
1, 4.06758, 1, 0, 0.462365,-0.017985) , 
5, 1.43499, 1, 0, 0.487961,-0.0107057)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632324,0.0423923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341536,0.00784832) , 
2, 0.00750805, 1, 0, 0.394792,0.0539386) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6525,-0.000447195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244898,-0.0128322) , 
5, 11.2939, 1, 0, 0.522235,-0.01484) , 
1, 3.54795, 1, 0, 0.495494,-0.000408138)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745036,0.0341425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793032,0.0120192) , 
0, 1120.95, 1, 0, 0.776858,0.076137) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432485,0.00494702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542723,-0.00455715) , 
4, 0.590139, 1, 0, 0.481963,0.00192287) , 
5, 1.37261, 1, 0, 0.510321,0.0090593)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630813,0.0276144) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37925,0.0117418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553693,-0.00579556) , 
4, 0.353126, 1, 0, 0.499889,-0.00293178) , 
3, 0.0185334, 1, 0, 0.507987,0.00291637)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522773,0.0105944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638878,-0.0136481) , 
4, 0.302449, 1, 0, 0.607678,-0.0234113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498482,0.0102729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296478,-0.00647044) , 
2, 0.0590025, 1, 0, 0.420422,0.0147427) , 
2, 0.0184865, 1, 0, 0.496907,-0.000841374)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351382,0.00772649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551034,-0.00547494) , 
4, 0.254323, 1, 0, 0.502083,-0.0090623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384491,0.0323168) , 
2, 0.118312, 1, 0, 0.496844,-0.00414941)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618481,0.000482079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395141,-0.00986471) , 
3, 0.15435, 1, 0, 0.499159,-0.0184678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366843,0.0206872) , 
4, 1.1234, 1, 0, 0.492109,-0.0140758)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709028,0.00897716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454812,-0.00272882) , 
5, 2.82439, 1, 0, 0.507069,-0.00113143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403337,0.0308683) , 
4, 1.12331, 1, 0, 0.500721,0.00466742)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523325,0.00152262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412079,0.0263629) , 
2, 0.0758439, 1, 0, 0.508805,0.015994) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702735,0.00473574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372349,-0.0258067) , 
5, 1.31288, 1, 0, 0.491488,-0.0522372) , 
4, 0.886626, 1, 0, 0.50528,0.00210703)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473425,0.00589425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111619,-0.0226482) , 
5, 27.4017, 1, 0, 0.4242,0.0112207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566046,-0.0413482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545164,-0.00555736) , 
3, 0.0370427, 1, 0, 0.547783,-0.0359074) , 
4, 0.590139, 1, 0, 0.484448,-0.0117545)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510344,0.00455162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525838,-0.0106455) , 
4, 0.84585, 1, 0, 0.51445,0.00188993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14364,-0.0316713) , 
3, 0.444411, 1, 0, 0.497443,-0.00298423)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549972,0.00685359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0856454,-0.02672) , 
5, 27.3951, 1, 0, 0.501566,0.0168799) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616847,0.00106128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29861,-0.021734) , 
3, 0.265425, 1, 0, 0.518806,-0.0230062) , 
4, 0.846897, 1, 0, 0.506125,0.00633196)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.129599,-0.0283184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541569,0.0049083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518104,-0.00627586) , 
4, 0.901636, 1, 0, 0.536378,0.00931527) , 
4, -0.0419635, 1, 0, 0.51477,0.00519855)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322188,0.00512034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539872,-0.00683201) , 
4, 0.214777, 1, 0, 0.492692,-0.0167639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361086,0.0260946) , 
3, 0.432066, 1, 0, 0.486456,-0.0118254)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370348,-0.017295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718225,0.0146269) , 
1, 3.16791, 1, 0, 0.67672,0.0369774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348714,0.00215151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491397,-0.0113194) , 
0, 1137.33, 1, 0, 0.424651,-0.0189783) , 
2, 0.012949, 1, 0, 0.494804,-0.00340533)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693379,0.00570087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392645,0.0271939) , 
5, 20.5267, 1, 0, 0.655816,0.0307753) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237051,-0.0197087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423821,0.000222045) , 
0, 877.937, 1, 0, 0.385977,-0.0127453) , 
2, 0.0221838, 1, 0, 0.512308,0.00762977)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15857,-0.0376913) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499188,0.00407912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661879,-0.0243494) , 
1, 6.15678, 1, 0, 0.511162,0.00822017) , 
1, 2.55255, 1, 0, 0.497935,0.00300857)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112712,-0.0305785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532213,-0.00232404) , 
4, -0.00346308, 1, 0, 0.494335,-0.014344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371861,0.0224024) , 
4, 1.12352, 1, 0, 0.487104,-0.00933322)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535554,0.000147322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.866392,0.0296848) , 
1, 5.90993, 1, 0, 0.570342,0.00966151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303653,-0.0145127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248974,0.0127059) , 
4, 1.0826, 1, 0, 0.295835,-0.0388668) , 
2, 0.0481032, 1, 0, 0.489714,-0.0045921)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635753,0.00300962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215308,-0.0133329) , 
5, 14.3443, 1, 0, 0.538319,-0.00161832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383084,0.0456019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343465,0.00523867) , 
1, 3.57905, 1, 0, 0.352193,0.0450074) , 
2, 0.0684546, 1, 0, 0.505472,0.00661009)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571436,-0.0016315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395311,-0.0331799) , 
3, 0.231612, 1, 0, 0.562669,-0.0118572) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448175,-0.00368825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329546,0.0232073) , 
2, 0.0258979, 1, 0, 0.388055,0.0299228) , 
3, 0.246899, 1, 0, 0.509013,0.000981177)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720965,0.0111608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450426,-0.00188211) , 
5, 2.71824, 1, 0, 0.503895,0.00245161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215951,-0.0245541) , 
2, 0.112841, 1, 0, 0.48744,-0.0023626)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556553,0.000833421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330624,0.0258735) , 
4, 1.18256, 1, 0, 0.54717,0.0060461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315384,-0.0211455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199798,-0.000850832) , 
5, 7.12701, 1, 0, 0.250837,-0.0419781) , 
3, 0.339447, 1, 0, 0.499041,-0.00175372)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671349,0.0029847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621846,0.0378003) , 
4, 1.11863, 1, 0, 0.66678,0.0237068) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343579,-0.00437324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45232,-0.0397673) , 
1, 5.95551, 1, 0, 0.352862,-0.0271308) , 
5, 6.99231, 1, 0, 0.50335,-0.00275992)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480899,0.00598226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615731,-0.0331521) , 
1, 6.42083, 1, 0, 0.487891,0.01483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241526,-0.0331239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600221,-0.00075623) , 
1, 3.45379, 1, 0, 0.538291,-0.023985) , 
4, 0.827149, 1, 0, 0.502504,0.00357548)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313438,-0.0126662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482599,0.00995071) , 
0, 819.974, 1, 0, 0.458137,0.0247403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503477,0.00913317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645457,-0.0139458) , 
4, 0.352859, 1, 0, 0.603685,-0.0238717) , 
1, 4.84066, 1, 0, 0.50837,0.007963)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold3::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold3::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
