// Class: ReadBDT-0.3_fold8
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold8
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.30/04       [400900]
Creator        : b78499db
Date           : Thu Mar 21 15:54:56 2024
Host           : Darwin Sonoma-arm64.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:43:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis
Training events: 35228
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.003479004,8696.23632812]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.00020766258,8.59782600403]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [1.25554126264e-18,0.149860098958]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [9.20502588997e-06,0.499961167574]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.39996659756]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000704350823071,129.481124878]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [84,1159527808]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold8Node

#ifndef BDT-0.3_fold8Node__def
#define BDT-0.3_fold8Node__def

class BDT-0.3_fold8Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold8Node ( BDT-0.3_fold8Node* left,BDT-0.3_fold8Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold8Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold8Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold8Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold8Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold8Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold8Node::~BDT-0.3_fold8Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold8Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold8Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold8 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold8( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold8" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold8() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold8Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold8::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold8Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold8Node*)current->GetRight();
         else current=(BDT-0.3_fold8Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold8::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503435,0.000687046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742076,0.0484151) , 
0, 1447.18, 1, 0, 0.596582,0.096582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.163468,-0.0673064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447598,-0.0104804) , 
0, 1657.46, 1, 0, 0.227999,-0.272001) , 
5, 12.9106, 1, 0, 0.492977,-0.00702321)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685662,0.0351396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426449,-0.0161059) , 
3, 0.290087, 1, 0, 0.626866,0.117461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189438,-0.0574712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406889,-0.0166686) , 
0, 1140.1, 1, 0, 0.3046,-0.178778) , 
5, 9.48996, 1, 0, 0.500138,0.00096744)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485409,-0.00275624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753082,0.0447095) , 
0, 1447.16, 1, 0, 0.588033,0.0767997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35059,-0.0215025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.113484,-0.0681783) , 
2, 0.0241155, 1, 0, 0.21592,-0.237519) , 
5, 15.8145, 1, 0, 0.507867,0.0090845)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695741,0.0332896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502896,-0.00403833) , 
2, 0.0314028, 1, 0, 0.620444,0.0929212) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386189,-0.0148748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171708,-0.0550275) , 
2, 0.0221151, 1, 0, 0.260984,-0.188056) , 
5, 10.8716, 1, 0, 0.493899,-0.00599426)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704009,0.0321548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432059,-0.0177404) , 
3, 0.253003, 1, 0, 0.625099,0.0872437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211773,-0.042771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474236,0.000995957) , 
0, 1417.05, 1, 0, 0.298189,-0.137388) , 
5, 10.0415, 1, 0, 0.496905,-0.000842845)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665925,0.0250643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362514,-0.0260301) , 
3, 0.296259, 1, 0, 0.595778,0.0648572) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.172914,-0.0462771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505009,0.00945432) , 
0, 2008.45, 1, 0, 0.211636,-0.188611) , 
5, 14.2341, 1, 0, 0.494475,-0.00198543)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413717,-0.0148059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69018,0.0314719) , 
1, 3.7922, 1, 0, 0.618266,0.0946815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473026,-0.00968726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136855,-0.0481445) , 
5, 15.4532, 1, 0, 0.38268,-0.0940639) , 
2, 0.0277297, 1, 0, 0.509834,0.00780811)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516207,-0.00306248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.770605,0.0383439) , 
0, 1256.43, 1, 0, 0.640316,0.0824523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356541,-0.0160327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141233,-0.0487736) , 
5, 21.435, 1, 0, 0.276872,-0.131205) , 
5, 9.59185, 1, 0, 0.500264,0.000120313)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469657,-0.000201444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266955,-0.0373868) , 
3, 0.111095, 1, 0, 0.326595,-0.126268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7462,0.0390967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480835,-0.00331068) , 
2, 0.0203484, 1, 0, 0.606606,0.0805767) , 
0, 1060.46, 1, 0, 0.501864,0.00320372)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460766,-0.00874208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697043,0.0260683) , 
1, 4.18047, 1, 0, 0.601826,0.0573788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.117316,-0.0486878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401947,-0.00471126) , 
0, 1565.36, 1, 0, 0.185876,-0.167861) , 
5, 15.8145, 1, 0, 0.509463,0.00736349)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703917,0.0268455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314547,-0.0158078) , 
5, 15.9231, 1, 0, 0.64029,0.0946908) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435918,-0.00770619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18909,-0.0480611) , 
3, 0.314779, 1, 0, 0.38459,-0.0755713) , 
2, 0.0240481, 1, 0, 0.511702,0.00906838)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652825,0.0202477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207769,-0.0525713) , 
3, 0.41967, 1, 0, 0.624157,0.0727914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315916,-0.0269629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66615,0.0262791) , 
1, 5.87647, 1, 0, 0.345889,-0.103921) , 
2, 0.0258811, 1, 0, 0.490445,-0.0121213)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692554,0.0255754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397004,-0.0122336) , 
2, 0.031427, 1, 0, 0.571057,0.0465773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521219,-0.0012943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260669,-0.0344845) , 
5, 4.79728, 1, 0, 0.339028,-0.112721) , 
3, 0.23456, 1, 0, 0.490329,-0.00884587)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529074,0.000881525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292413,-0.0258503) , 
2, 0.0241013, 1, 0, 0.402746,-0.0612715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764993,0.0323585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327128,-0.015528) , 
5, 14.2348, 1, 0, 0.68192,0.107019) , 
1, 4.93251, 1, 0, 0.491815,-0.00757957)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712542,0.023774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430532,-0.00556657) , 
5, 7.05967, 1, 0, 0.574256,0.0437866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341869,-0.0119886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232272,-0.0515901) , 
4, 0.924654, 1, 0, 0.314212,-0.102637) , 
2, 0.0517443, 1, 0, 0.506766,0.00578521)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671647,0.0166732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407055,-0.0268454) , 
4, 1.04476, 1, 0, 0.635956,0.049635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291701,-0.0173412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148562,-0.0578086) , 
4, 0.530886, 1, 0, 0.273755,-0.100268) , 
5, 9.59185, 1, 0, 0.491271,-0.010245)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676035,0.0167983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409699,-0.0242319) , 
4, 1.0446, 1, 0, 0.642152,0.0530625) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3054,-0.013468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14198,-0.0537428) , 
4, 0.569523, 1, 0, 0.28605,-0.0807937) , 
5, 9.59185, 1, 0, 0.50441,0.00128631)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359135,-0.0163124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174792,-0.055615) , 
4, 1.00502, 1, 0, 0.337302,-0.096171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749465,0.0282206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487325,0.00225373) , 
5, 4.74665, 1, 0, 0.58334,0.0532174) , 
1, 3.85721, 1, 0, 0.511627,0.0096748)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581971,0.00479643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262839,-0.021604) , 
5, 7.99585, 1, 0, 0.421966,-0.0351427) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773956,0.0313157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289819,-0.0209908) , 
5, 17.811, 1, 0, 0.704827,0.104473) , 
0, 1657.01, 1, 0, 0.499185,0.00297165)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752705,0.0288565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565927,-0.000974548) , 
3, 0.10493, 1, 0, 0.630661,0.0421592) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206996,-0.0264285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540638,0.0147212) , 
0, 2245.3, 1, 0, 0.242445,-0.0903468) , 
5, 11.1916, 1, 0, 0.4946,-0.00428133)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806907,0.0373038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614339,0.00401719) , 
4, 0.890294, 1, 0, 0.711083,0.0918439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427337,-0.00093142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248163,-0.05386) , 
4, 0.747216, 1, 0, 0.403506,-0.0364863) , 
5, 4.74485, 1, 0, 0.506432,0.00645757)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664833,0.0179898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401527,-0.00731586) , 
2, 0.0295779, 1, 0, 0.546166,0.0288418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.259958,-0.0182613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295296,-0.0354811) , 
4, 0.609947, 1, 0, 0.276166,-0.11743) , 
3, 0.327142, 1, 0, 0.496733,0.00206138)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392042,-0.0115768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644753,0.018521) , 
0, 997.547, 1, 0, 0.5723,0.0422655) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328054,-0.00993445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349125,-0.0340092) , 
4, 0.689051, 1, 0, 0.336351,-0.0879449) , 
3, 0.240701, 1, 0, 0.489969,-0.00316962)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511829,-0.000529442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256878,-0.0289088) , 
3, 0.296198, 1, 0, 0.448756,-0.0329153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922479,0.0549601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676606,0.0180979) , 
2, 0.0184521, 1, 0, 0.780505,0.136692) , 
1, 5.74709, 1, 0, 0.491334,-0.0111473)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714082,0.0238393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385774,-0.0142222) , 
3, 0.339401, 1, 0, 0.664448,0.0770119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636745,0.00875688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327144,-0.0164447) , 
5, 4.79709, 1, 0, 0.421273,-0.0365493) , 
2, 0.0129509, 1, 0, 0.492972,-0.00306659)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588971,0.0103515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335226,-0.0328476) , 
4, 1.04464, 1, 0, 0.564769,0.0269987) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332309,-0.00530536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102458,-0.0393353) , 
2, 0.0150884, 1, 0, 0.157048,-0.112534) , 
5, 21.515, 1, 0, 0.508714,0.00781532)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317377,-0.0107834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33863,-0.0298862) , 
4, 0.728686, 1, 0, 0.324722,-0.0768389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667911,0.0122869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234363,-0.0166039) , 
5, 15.8165, 1, 0, 0.579169,0.0289508) , 
1, 4.01869, 1, 0, 0.485406,-0.0100322)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694798,0.0210333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510958,-0.00223577) , 
3, 0.117281, 1, 0, 0.580143,0.0278289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0927767,-0.040601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280511,-0.00817174) , 
1, 4.62431, 1, 0, 0.158297,-0.103737) , 
5, 18.6471, 1, 0, 0.509026,0.00564885)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597441,0.00902298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337979,-0.0142331) , 
5, 2.87009, 1, 0, 0.385286,-0.0413971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725902,0.0216151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42038,-0.0083463) , 
2, 0.0461367, 1, 0, 0.658115,0.0608189) , 
0, 1327.36, 1, 0, 0.503435,0.00286763)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299431,-0.0373148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175514,-0.0199082) , 
5, 11.1986, 1, 0, 0.248849,-0.132941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564651,0.00623478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247063,-0.0273837) , 
3, 0.364139, 1, 0, 0.526855,0.00945903) , 
1, 3.13061, 1, 0, 0.496232,-0.00622648)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595159,0.0126796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523775,-0.0122565) , 
4, 0.847025, 1, 0, 0.573021,0.0218164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.042312,-0.0512249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171522,-0.02383) , 
4, -0.0466078, 1, 0, 0.141483,-0.104413) , 
5, 18.9782, 1, 0, 0.503105,0.00136519)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405285,-0.00622644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243359,-0.0347522) , 
4, 1.04429, 1, 0, 0.389676,-0.0386743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675457,0.0167667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499977,-0.0191301) , 
4, 1.02295, 1, 0, 0.660493,0.0562288) , 
0, 1409.65, 1, 0, 0.49699,-0.00106785)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720614,0.0171715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421877,-0.00546794) , 
5, 5.48228, 1, 0, 0.542295,0.015558) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243781,-0.0172079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229517,-0.0412229) , 
4, 0.767199, 1, 0, 0.239386,-0.102775) , 
3, 0.339462, 1, 0, 0.496017,-0.00252051)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566846,0.00663794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938301,0.0583494) , 
1, 6.36015, 1, 0, 0.588634,0.0389635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343157,-0.00867163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247168,-0.0326596) , 
4, 0.965409, 1, 0, 0.322916,-0.0574839) , 
2, 0.0425529, 1, 0, 0.500259,0.00688637)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280482,-0.0114571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297745,-0.0349867) , 
4, 0.688761, 1, 0, 0.28737,-0.0900907) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225639,-0.0226057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594086,0.00667603) , 
4, 0.116024, 1, 0, 0.545406,0.0132189) , 
0, 905.238, 1, 0, 0.494191,-0.00728619)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.214502,-0.0300605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383741,-0.00470306) , 
1, 3.11859, 1, 0, 0.349631,-0.039793) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667205,0.0121893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200743,-0.0214156) , 
5, 20.0807, 1, 0, 0.604016,0.0329168) , 
0, 1060.46, 1, 0, 0.510697,0.00624389)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71288,0.016616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428501,-0.00370614) , 
2, 0.0258807, 1, 0, 0.579073,0.0275491) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31038,0.00326787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332855,-0.0216046) , 
1, 3.53345, 1, 0, 0.326991,-0.0631752) , 
3, 0.240727, 1, 0, 0.494055,-0.00304915)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797977,0.0264316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532147,-0.00499636) , 
3, 0.209513, 1, 0, 0.711762,0.0630496) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458819,0.000782462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274246,-0.0431272) , 
4, 0.84706, 1, 0, 0.437715,-0.0177864) , 
5, 3.19928, 1, 0, 0.501064,0.000899652)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429074,-0.0031848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693407,0.0154904) , 
0, 1079.83, 1, 0, 0.596419,0.0339138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0297162,-0.05514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370889,-0.00410575) , 
4, -0.0419794, 1, 0, 0.336602,-0.031118) , 
2, 0.0406389, 1, 0, 0.50965,0.0121956)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574182,0.00731706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.129885,-0.0292955) , 
5, 27.2934, 1, 0, 0.538715,0.0199612) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.220355,-0.0131996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17263,-0.04362) , 
4, 0.767941, 1, 0, 0.204191,-0.0942144) , 
3, 0.382691, 1, 0, 0.508282,0.00957402)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825697,0.0295008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607776,0.00340794) , 
2, 0.0147786, 1, 0, 0.687007,0.0487706) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410912,-0.000868504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336866,-0.0305669) , 
4, 0.688859, 1, 0, 0.398551,-0.0240831) , 
5, 4.79709, 1, 0, 0.498221,0.00109007)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281876,-0.022073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495374,0.000229202) , 
1, 3.19932, 1, 0, 0.466037,-0.0115723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.894174,0.0411734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584092,-0.00140204) , 
2, 0.0240181, 1, 0, 0.799324,0.0950245) , 
0, 2316.65, 1, 0, 0.51121,0.00287574)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768951,0.0207882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32202,-0.00593909) , 
5, 11.2986, 1, 0, 0.633892,0.0489589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423841,0.00195046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492644,-0.0144779) , 
4, 0.688894, 1, 0, 0.45239,-0.020554) , 
3, 0.0925993, 1, 0, 0.505927,-5.00857e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273886,-0.0142067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678675,0.0164508) , 
4, 0.0959497, 1, 0, 0.631065,0.0512834) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238526,-0.0206375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494747,0.0019069) , 
0, 899.307, 1, 0, 0.439647,-0.0109812) , 
3, 0.104944, 1, 0, 0.505027,0.0102857)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562849,0.00081635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562858,0.0381626) , 
3, 0.263309, 1, 0, 0.562849,0.0147644) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272301,-0.00853346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331537,-0.0282873) , 
1, 4.68109, 1, 0, 0.290406,-0.0598008) , 
3, 0.296259, 1, 0, 0.500397,-0.00232823)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454478,-0.00358807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102956,-0.0309068) , 
5, 12.427, 1, 0, 0.331583,-0.0430533) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591565,0.00725307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432425,-0.019632) , 
4, 1.02466, 1, 0, 0.576108,0.0177251) , 
0, 982.853, 1, 0, 0.502356,-0.000606537)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683597,0.00796006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338365,-0.0273324) , 
2, 0.0924309, 1, 0, 0.655796,0.0189593) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362435,-0.00829151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244326,-0.0362696) , 
4, 0.669351, 1, 0, 0.346036,-0.0475422) , 
5, 6.32703, 1, 0, 0.477499,-0.0193189)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577633,0.0227813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715344,0.00895896) , 
4, 0.379901, 1, 0, 0.667049,0.055163) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578961,0.0211625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411128,-0.00703039) , 
3, 0.0247041, 1, 0, 0.426975,-0.0171515) , 
2, 0.0129509, 1, 0, 0.492007,0.00243732)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651242,0.0194983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247358,-0.00257077) , 
5, 14.4676, 1, 0, 0.476041,0.0431704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661092,0.00574014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32804,-0.0361839) , 
5, 5.1537, 1, 0, 0.558219,-0.0295575) , 
4, 0.609907, 1, 0, 0.515191,0.00852218)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722996,0.0213659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308104,-0.00124902) , 
5, 10.17, 1, 0, 0.470434,0.0317192) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638103,0.00250847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30141,-0.0286822) , 
5, 5.38674, 1, 0, 0.560326,-0.0187843) , 
4, 0.68907, 1, 0, 0.507703,0.0107803)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525467,0.0124362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573573,-0.00178948) , 
4, 0.590255, 1, 0, 0.551368,0.0195427) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.124258,-0.0208467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10083,-0.0391128) , 
4, 0.0739119, 1, 0, 0.116494,-0.0811755) , 
5, 23.9951, 1, 0, 0.504297,0.00864095)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234084,-0.0282497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326442,-0.00811427) , 
0, 805.444, 1, 0, 0.290565,-0.0612815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636787,0.00923593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170105,-0.0185415) , 
5, 19.7608, 1, 0, 0.568415,0.0224342) , 
0, 904.928, 1, 0, 0.511401,0.00525593)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34618,-0.0178649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.632719,0.00673462) , 
1, 3.30344, 1, 0, 0.599545,0.0141139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350406,0.0068305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396368,-0.0160498) , 
1, 3.60278, 1, 0, 0.38463,-0.0407897) , 
3, 0.166648, 1, 0, 0.489552,-0.0139855)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593002,0.00495399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.936937,0.0475874) , 
1, 6.2937, 1, 0, 0.610918,0.0269822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183477,-0.0108377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10157,-0.0432606) , 
4, 0.294148, 1, 0, 0.170926,-0.0506025) , 
5, 15.9867, 1, 0, 0.516099,0.0102626)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843913,0.0362488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516857,-0.00498857) , 
2, 0.0295135, 1, 0, 0.727621,0.0771483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461494,-0.000216061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436368,-0.0223793) , 
4, 0.846875, 1, 0, 0.456665,-0.0174671) , 
5, 1.59923, 1, 0, 0.48389,-0.00796044)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352909,-0.0147121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667787,0.0166265) , 
1, 3.29598, 1, 0, 0.635676,0.0492161) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647942,0.0143153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38792,-0.00989162) , 
2, 0.00737826, 1, 0, 0.424539,-0.024967) , 
3, 0.11112, 1, 0, 0.498534,0.00103108)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395868,-0.00380517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715968,0.0143766) , 
0, 1492.18, 1, 0, 0.508342,0.00860009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487744,-0.0147084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117322,-0.0520928) , 
2, 0.0796632, 1, 0, 0.410336,-0.0866286) , 
4, 0.945682, 1, 0, 0.492427,-0.0068637)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719622,0.0142086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473913,-0.0092889) , 
4, 0.986367, 1, 0, 0.666998,0.0348203) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330412,0.000123468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337479,-0.0219393) , 
4, 0.372781, 1, 0, 0.332919,-0.0305141) , 
5, 7.99332, 1, 0, 0.508037,0.00373297)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695406,0.0261908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241962,-0.00528396) , 
5, 12.9139, 1, 0, 0.37708,0.0199092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681387,0.006377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478519,-0.0135169) , 
5, 2.94064, 1, 0, 0.538708,-0.0307786) , 
4, 0.373058, 1, 0, 0.486163,-0.0143001)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539901,0.0051229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55193,-0.00763555) , 
4, 0.768335, 1, 0, 0.544392,0.001623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.134414,-0.00789128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0936456,-0.0346276) , 
1, 3.6982, 1, 0, 0.105599,-0.0769525) , 
5, 23.9786, 1, 0, 0.4975,-0.00677409)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696666,0.00965842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490693,-0.00928468) , 
4, 0.96572, 1, 0, 0.648645,0.0201433) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337415,-0.000220072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244937,-0.0329551) , 
4, 0.491269, 1, 0, 0.318928,-0.025748) , 
5, 8.46931, 1, 0, 0.495814,-0.0011283)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459532,0.00486635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193669,-0.0279918) , 
2, 0.012928, 1, 0, 0.27341,-0.0662676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579243,0.00398067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322187,-0.0117609) , 
3, 0.29628, 1, 0, 0.524215,0.00212807) , 
1, 3.28391, 1, 0, 0.489448,-0.00735291)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75306,0.016898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415796,-0.01388) , 
2, 0.0608031, 1, 0, 0.691473,0.0388332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437849,-0.000634997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405422,-0.0178746) , 
4, 0.787434, 1, 0, 0.43202,-0.0141789) , 
5, 3.19877, 1, 0, 0.493057,-0.00170781)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370927,-0.0149848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671034,0.00544062) , 
1, 3.29204, 1, 0, 0.630605,0.0091319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278799,-0.00270777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244796,-0.0254739) , 
4, 0.353679, 1, 0, 0.268051,-0.0362442) , 
5, 10.0415, 1, 0, 0.493621,-0.00801255)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516793,0.00644651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.129391,-0.0168816) , 
5, 16.9388, 1, 0, 0.429037,0.0104394) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5251,-0.0149729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757489,0.0104772) , 
0, 2328.66, 1, 0, 0.5776,-0.0356534) , 
1, 4.68834, 1, 0, 0.487302,-0.00763774)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620225,0.00754706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319106,-0.0135089) , 
2, 0.077642, 1, 0, 0.580179,0.01772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341361,-0.00289694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500785,-0.0260283) , 
1, 5.35745, 1, 0, 0.365431,-0.02479) , 
3, 0.216015, 1, 0, 0.497111,0.00127632)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445257,-0.000809541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553637,-0.0254052) , 
1, 5.48509, 1, 0, 0.457475,-0.013377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76884,0.00384501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.842044,0.0417762) , 
3, 0.148174, 1, 0, 0.796138,0.063361) , 
0, 2302.3, 1, 0, 0.496976,-0.00442653)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664182,0.0234533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230198,-0.000277081) , 
5, 14.2427, 1, 0, 0.400247,0.0372335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632911,0.00306213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233509,-0.0324932) , 
5, 8.82232, 1, 0, 0.564637,-0.0106078) , 
4, 0.451816, 1, 0, 0.5005,0.00805742)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.172314,-0.0341209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773917,0.024614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49129,0.00158398) , 
5, 1.58364, 1, 0, 0.516799,0.0137192) , 
1, 2.46655, 1, 0, 0.50594,0.00938172)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.13353,-0.0308197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415887,-0.00111181) , 
4, 0.255088, 1, 0, 0.334683,-0.029579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528005,0.0109171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644386,-0.00637148) , 
4, 0.569844, 1, 0, 0.590855,0.00648278) , 
0, 1060.46, 1, 0, 0.493992,-0.00715276)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666657,0.01363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376835,0.000791633) , 
5, 4.74485, 1, 0, 0.47211,0.0200028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813676,0.00945752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563079,-0.0253961) , 
2, 0.0147804, 1, 0, 0.66336,-0.0454481) , 
0, 2066.86, 1, 0, 0.50372,0.00918512)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322306,0.00384537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634988,0.0302838) , 
1, 5.0292, 1, 0, 0.411531,0.0422429) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634641,-0.000943826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351739,-0.0198364) , 
5, 7.05656, 1, 0, 0.546405,-0.0263544) , 
4, 0.37282, 1, 0, 0.501689,-0.00361155)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445568,0.00794365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660007,-0.0216578) , 
1, 6.11482, 1, 0, 0.461325,0.0218811) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642402,5.13512e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247427,-0.0332982) , 
5, 5.83558, 1, 0, 0.570575,-0.0208807) , 
4, 0.669125, 1, 0, 0.50838,0.00346316)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.781851,0.0149762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493556,-0.00486812) , 
2, 0.0497477, 1, 0, 0.724558,0.0365513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467044,-0.00129045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291093,-0.0346087) , 
4, 0.846864, 1, 0, 0.445243,-0.0201648) , 
5, 2.79785, 1, 0, 0.500246,-0.00899636)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118607,-0.0303806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430232,0.0146437) , 
4, -0.093837, 1, 0, 0.40047,0.0404869) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62369,0.00177213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22628,-0.0234935) , 
5, 9.99733, 1, 0, 0.561164,-0.00727867) , 
4, 0.372877, 1, 0, 0.505193,0.00935853)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749938,0.0153168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59789,-0.000308792) , 
4, 0.867172, 1, 0, 0.677929,0.0289966) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401126,0.00144356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192189,-0.0359605) , 
4, 0.668158, 1, 0, 0.375167,-0.0102912) , 
5, 6.39629, 1, 0, 0.508262,0.00697977)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0277601,-0.0522011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208897,-0.0163082) , 
0, 1080.39, 1, 0, 0.132533,-0.0785135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498051,0.00957244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580727,-0.00202123) , 
4, 0.603737, 1, 0, 0.540787,0.0136161) , 
4, -0.00246276, 1, 0, 0.511456,0.00699699)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229981,-0.0156354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483447,0.0116024) , 
1, 3.24673, 1, 0, 0.453316,0.0312234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669105,0.00368811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307279,-0.0249238) , 
5, 5.38674, 1, 0, 0.55708,-0.0186032) , 
4, 0.590156, 1, 0, 0.50425,0.00676532)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626706,0.00559909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205933,-0.0108489) , 
5, 14.4473, 1, 0, 0.493555,0.00416712) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393317,-0.0185359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700351,-0.00169737) , 
0, 1409.65, 1, 0, 0.516446,-0.0453737) , 
4, 0.866878, 1, 0, 0.499153,-0.00794937)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.816006,0.0224181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438914,-0.0055688) , 
5, 6.32879, 1, 0, 0.616164,0.0240237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550183,-0.0134305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343044,0.00488477) , 
5, 7.99411, 1, 0, 0.44973,-0.0191549) , 
3, 0.0802484, 1, 0, 0.49337,-0.00783332)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662282,-0.022399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646366,0.00712837) , 
2, 0.00369724, 1, 0, 0.647462,0.0204868) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28655,-0.00353841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256022,-0.0212842) , 
4, 0.372826, 1, 0, 0.277427,-0.0318248) , 
5, 9.48996, 1, 0, 0.49881,-0.000527922)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598137,0.000905765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433743,0.0251715) , 
5, 13.3536, 1, 0, 0.575918,0.015794) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.165893,-0.000962593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108886,-0.0337682) , 
4, 0.0768123, 1, 0, 0.139037,-0.0492784) , 
5, 18.9773, 1, 0, 0.502103,0.0047994)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572091,-0.00649308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514989,0.0050839) , 
3, 0.0683467, 1, 0, 0.528515,0.0088444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.144601,-0.0199985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210425,-0.0322185) , 
0, 1078.39, 1, 0, 0.177709,-0.0914195) , 
3, 0.425848, 1, 0, 0.506835,0.00264806)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633032,-0.000272387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517584,0.0187083) , 
2, 0.0629042, 1, 0, 0.611656,0.0134365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.204719,-0.00133465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.162378,-0.0283139) , 
4, 0.175276, 1, 0, 0.187721,-0.040083) , 
5, 14.3874, 1, 0, 0.506861,0.00020666)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68722,0.00754812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403335,-0.0150237) , 
2, 0.0865979, 1, 0, 0.661054,0.0198378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245825,0.00643427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345997,-0.0118336) , 
1, 3.52053, 1, 0, 0.324164,-0.0298648) , 
5, 7.99332, 1, 0, 0.50019,-0.00389505)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575217,0.00228272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156381,-0.0171076) , 
5, 14.3874, 1, 0, 0.471231,-0.0056604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701476,0.0357529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.816603,0.0175794) , 
4, 0.357223, 1, 0, 0.786191,0.0731409) , 
0, 2302.3, 1, 0, 0.509373,0.00388241)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.750589,-0.000497631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546959,0.0248625) , 
5, 9.10775, 1, 0, 0.678234,0.0340488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465103,-0.00142153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159172,-0.0274678) , 
3, 0.382691, 1, 0, 0.432818,-0.0142706) , 
2, 0.0129313, 1, 0, 0.503883,-0.000278795)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572262,-0.00489379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472489,-0.0246188) , 
3, 0.12096, 1, 0, 0.56025,-0.0263554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211361,-0.0226403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492036,0.0082642) , 
0, 824.747, 1, 0, 0.458307,0.017606) , 
3, 0.142017, 1, 0, 0.502137,-0.0012951)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554569,0.0033113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132139,-0.0146997) , 
5, 23.9794, 1, 0, 0.512151,0.00738936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220515,-0.0272988) , 
2, 0.11839, 1, 0, 0.499811,0.00318846)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796651,0.0295334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691297,0.00275646) , 
5, 0.85422, 1, 0, 0.753024,0.0692881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376149,-0.00857419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664277,0.00790595) , 
0, 1483.72, 1, 0, 0.475336,-0.0112478) , 
5, 1.41214, 1, 0, 0.503839,-0.00298142)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530461,0.00459143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348504,-0.0120414) , 
3, 0.123531, 1, 0, 0.413793,-0.0225292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749386,-0.0014058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640036,0.0279667) , 
2, 0.0332558, 1, 0, 0.719272,0.026686) , 
0, 1720.44, 1, 0, 0.48773,-0.0106173)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64342,-0.0279444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6324,0.0053522) , 
2, 0.00369509, 1, 0, 0.633111,0.0132599) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448925,0.0116833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207664,-0.01307) , 
2, 0.0110991, 1, 0, 0.25415,-0.023472) , 
5, 11.0704, 1, 0, 0.501571,0.000509973)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705227,0.00954645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321827,-0.0111766) , 
3, 0.333239, 1, 0, 0.643584,0.0210656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403288,-0.00239251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590486,-0.0297002) , 
0, 2752.88, 1, 0, 0.414852,-0.0145709) , 
2, 0.0184865, 1, 0, 0.505484,-0.000450424)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177763,-0.0352793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473205,0.000947499) , 
1, 2.69222, 1, 0, 0.456732,-0.00358437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664036,0.00200307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612114,-0.0427645) , 
4, 0.688738, 1, 0, 0.640696,-0.057253) , 
1, 5.50274, 1, 0, 0.491165,-0.0136295)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630052,0.00641127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445711,-0.00348328) , 
3, 0.11728, 1, 0, 0.509118,-0.00089865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0646671,-0.0360241) , 
5, 32.4646, 1, 0, 0.489906,-0.00451422)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566541,0.00036891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306569,-0.0116088) , 
2, 0.0536108, 1, 0, 0.505137,-0.00877734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391561,0.028888) , 
4, 1.1234, 1, 0, 0.498538,-0.00311082)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284708,-0.00632371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533554,0.00756399) , 
0, 905.279, 1, 0, 0.483416,0.017463) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476672,0.00486572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590458,-0.020558) , 
0, 1162.82, 1, 0, 0.541728,-0.0322626) , 
4, 0.807678, 1, 0, 0.501255,0.00225035)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411008,0.00987493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592043,-0.00251269) , 
4, 0.393015, 1, 0, 0.531146,0.00509442) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158097,-0.0126471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484071,0.0257491) , 
4, 0.293818, 1, 0, 0.374452,0.0554807) , 
2, 0.0776432, 1, 0, 0.509208,0.0121489)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12568,-0.0394544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141821,-0.0155586) , 
3, 0.216019, 1, 0, 0.131923,-0.0819199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386737,0.0304141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546215,0.000493444) , 
4, 0.101776, 1, 0, 0.536459,0.00783157) , 
4, -0.0020792, 1, 0, 0.505002,0.000852488)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759586,-0.00209469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742015,0.0413527) , 
3, 0.172782, 1, 0, 0.751158,0.0780498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658098,0.0269462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470158,-0.00339272) , 
3, 0.0185321, 1, 0, 0.482071,-0.00547947) , 
5, 1.59923, 1, 0, 0.507864,0.00252688)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379396,-0.00942201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626623,0.00530453) , 
0, 914.929, 1, 0, 0.576051,0.00777456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322518,-0.0305085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26797,-0.00662807) , 
3, 0.307951, 1, 0, 0.278901,-0.0417415) , 
3, 0.27776, 1, 0, 0.497326,-0.00534401)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412229,-0.000197655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343553,0.0271986) , 
2, 0.0906427, 1, 0, 0.404612,0.00867954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708414,-0.000378417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385507,-0.0146904) , 
2, 0.0295607, 1, 0, 0.576409,-0.0236977) , 
1, 4.44627, 1, 0, 0.487077,-0.00686214)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669751,0.0284834) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310251,-0.0103383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589864,0.00153361) , 
0, 1048.61, 1, 0, 0.483195,-0.010724) , 
3, 0.018543, 1, 0, 0.495213,-0.00407776)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437964,0.00367412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618741,-0.00720168) , 
1, 4.66461, 1, 0, 0.511018,-0.00200157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0278923,-0.0487864) , 
5, 35.1688, 1, 0, 0.493553,-0.00558174)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395499,-0.00307297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448725,-0.0196692) , 
1, 4.53224, 1, 0, 0.410258,-0.0279613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686655,0.0253691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698625,-0.00579793) , 
1, 5.5557, 1, 0, 0.694197,0.0208858) , 
1, 5.15632, 1, 0, 0.480529,-0.0158723)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429316,0.0154702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328123,0.0414887) , 
3, 0.296344, 1, 0, 0.39425,0.0793115) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391703,0.0092513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571117,-0.00473164) , 
4, 0.353086, 1, 0, 0.512414,-0.0018577) , 
1, 2.96913, 1, 0, 0.501544,0.00560888)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298823,0.0113552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431788,0.0240105) , 
0, 914.77, 1, 0, 0.368619,0.0651076) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27102,-0.0201441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527187,0.00194216) , 
1, 3.23398, 1, 0, 0.507389,0.000659783) , 
1, 2.80778, 1, 0, 0.497926,0.00505447)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551629,0.00126754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470611,0.0274087) , 
3, 0.293333, 1, 0, 0.545017,0.0127452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240682,-0.0184367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248994,0.00250252) , 
3, 0.452373, 1, 0, 0.242258,-0.0508213) , 
3, 0.339449, 1, 0, 0.495641,0.00237838)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452614,0.00622391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640954,-0.0215054) , 
1, 5.88177, 1, 0, 0.473334,0.011808) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683266,0.00472894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373713,-0.02534) , 
5, 3.14352, 1, 0, 0.549645,-0.0303308) , 
4, 0.728194, 1, 0, 0.502559,-0.0043298)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593196,0.00228861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616738,0.0250258) , 
3, 0.140923, 1, 0, 0.595059,0.014706) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430083,-0.00951396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.160101,0.0137035) , 
5, 22.3813, 1, 0, 0.39543,-0.0284424) , 
3, 0.154299, 1, 0, 0.487035,-0.00864265)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518052,0.000107104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395479,0.0171269) , 
2, 0.0647448, 1, 0, 0.496523,0.0106844) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379177,-0.0212289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684007,0.00296709) , 
0, 1409.65, 1, 0, 0.502545,-0.0434808) , 
4, 0.866543, 1, 0, 0.497957,-0.00221886)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636763,0.00885501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469271,-0.0383892) , 
3, 0.0109736, 1, 0, 0.538056,-0.0662135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634755,0.00940617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434778,-0.00165975) , 
3, 0.13032, 1, 0, 0.504891,0.00765325) , 
3, 0.0246982, 1, 0, 0.507438,0.00197954)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559055,-0.000271203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302979,0.0452995) , 
5, 33.5763, 1, 0, 0.548619,0.00400168) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234997,-0.0258179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317233,-0.00402669) , 
2, 0.0850504, 1, 0, 0.287202,-0.0416085) , 
2, 0.0665513, 1, 0, 0.498374,-0.00476481)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67654,0.00696796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372622,-0.0148119) , 
2, 0.0831396, 1, 0, 0.641525,0.0156963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554632,0.0175944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234635,-0.0121258) , 
2, 0.00554955, 1, 0, 0.262921,-0.028962) , 
5, 10.444, 1, 0, 0.504279,-0.00049262)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0792153,-0.0358228) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355314,0.0136169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543224,-0.00160653) , 
4, 0.189497, 1, 0, 0.513702,0.00196313) , 
4, -0.041911, 1, 0, 0.489609,-0.00233522)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280982,-0.0244934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196363,0.00312061) , 
2, 0.0461117, 1, 0, 0.25743,-0.0661397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573878,0.00484768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401308,0.0225865) , 
2, 0.0758439, 1, 0, 0.549175,0.0256831) , 
1, 3.11334, 1, 0, 0.516869,0.015515)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34417,0.00417603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564764,0.0470926) , 
1, 3.40187, 1, 0, 0.38492,0.0436953) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707471,0.00483439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405377,-0.00686878) , 
5, 5.43958, 1, 0, 0.523225,-0.00823569) , 
1, 3.53453, 1, 0, 0.493178,0.00304637)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358387,-0.0172725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696719,0.0066982) , 
1, 3.14054, 1, 0, 0.664451,0.015071) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389345,-0.00283582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168539,-0.0287156) , 
4, 0.688081, 1, 0, 0.364403,-0.0186495) , 
5, 6.3948, 1, 0, 0.493692,-0.00411946)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436686,0.00488175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563568,-0.00987285) , 
1, 4.78856, 1, 0, 0.472634,0.00278487) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.91217,0.0354803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554637,0.000696548) , 
2, 0.0275601, 1, 0, 0.774868,0.0564339) , 
1, 5.82846, 1, 0, 0.508165,0.00909202)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6308,0.00334861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388781,-0.00545868) , 
2, 0.0221982, 1, 0, 0.505475,-0.00449587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391633,0.0287889) , 
4, 1.16297, 1, 0, 0.50065,-0.000507245)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63921,0.00476731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257679,-0.00690748) , 
5, 11.1877, 1, 0, 0.504675,0.00384935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.176791,-0.0284024) , 
3, 0.450556, 1, 0, 0.491447,-8.86562e-05)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53226,0.00807743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111903,-0.0175889) , 
5, 16.9386, 1, 0, 0.438649,0.01565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667201,-0.00371709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31574,-0.0319232) , 
2, 0.0665117, 1, 0, 0.60985,-0.0307912) , 
1, 4.85129, 1, 0, 0.498048,-0.000463091)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385156,0.0212314) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558199,0.00224288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1105,-0.017534) , 
5, 23.4975, 1, 0, 0.509536,0.00298864) , 
1, 2.56181, 1, 0, 0.503944,0.00629849)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494571,0.00689294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696513,-0.010801) , 
1, 5.79498, 1, 0, 0.518035,0.0179714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674504,0.00342724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197709,-0.0342126) , 
2, 0.0389874, 1, 0, 0.467812,-0.0446345) , 
4, 0.945759, 1, 0, 0.509714,0.00759888)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34244,-0.0100105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60237,0.000806828) , 
0, 970.101, 1, 0, 0.532476,-0.00771689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0772769,-0.0304938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45806,0.0200247) , 
4, 0.116908, 1, 0, 0.375969,0.0476862) , 
2, 0.062853, 1, 0, 0.501178,0.0033624)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold8::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold8::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
