// Class: ReadBDT-0.3_fold9
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT-0.3_fold9
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.30/04       [400900]
Creator        : b78499db
Date           : Thu Mar 21 15:54:57 2024
Host           : Darwin Sonoma-arm64.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:43:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_VMAPPLE arm64
Dir            : /Users/user/Documents/HEP/MVA-Analysis
Training events: 32084
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "125" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "3%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "80" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "sdivsqrtsplusb" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
mjj                           mjj                           mjj                           m_{jj}                        GeV                               'D'    [750.003479004,8696.23632812]
deltaRapidity                 deltaRapidity                 deltaRapidity                 #Delta y_{jj}                                                   'D'    [2.00020766258,8.59782600403]
ptBalance                     ptBalance                     ptBalance                     pT_{balance}                                                    'D'    [1.25554126264e-18,0.149860098958]
zCentrality                   zCentrality                   zCentrality                   #xi(Z)                                                          'D'    [9.20502588997e-06,0.499961167574]
omega                         omega                         omega                         #Omega                                                          'D'    [-0.199983268976,1.39996659756]
transverseRecoMassVariable    transverseRecoMassVariable    transverseRecoMassVariable    m_{T}(l)/f(m_{reco})          GeV                               'D'    [0.000704350823071,129.481124878]
NSpec 1
eventNumber                   eventNumber                   eventNumber                   I                                                               'F'    [84,1159527808]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT-0.3_fold9Node

#ifndef BDT-0.3_fold9Node__def
#define BDT-0.3_fold9Node__def

class BDT-0.3_fold9Node {

public:

   // constructor of an essentially "empty" node floating in space
   BDT-0.3_fold9Node ( BDT-0.3_fold9Node* left,BDT-0.3_fold9Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT-0.3_fold9Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold9Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT-0.3_fold9Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT-0.3_fold9Node*   fLeft;     // pointer to the left daughter node
   BDT-0.3_fold9Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT-0.3_fold9Node::~BDT-0.3_fold9Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT-0.3_fold9Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT-0.3_fold9Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT-0.3_fold9 : public IClassifierReader {

 public:

   // constructor
   ReadBDT-0.3_fold9( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT-0.3_fold9" ),
        fNvars( 6 )
   {
      // the training input variables
      const char* inputVars[] = { "mjj", "deltaRapidity", "ptBalance", "zCentrality", "omega", "transverseRecoMassVariable" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT-0.3_fold9() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT-0.3_fold9Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT-0.3_fold9::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT-0.3_fold9Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT-0.3_fold9Node*)current->GetRight();
         else current=(BDT-0.3_fold9Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadBDT-0.3_fold9::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688759,0.0377518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465571,-0.00688575) , 
2, 0.0240516, 1, 0, 0.582337,0.0823368) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.120336,-0.0759328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418075,-0.0163849) , 
0, 1708.31, 1, 0, 0.181869,-0.318131) , 
5, 15.7792, 1, 0, 0.499946,-5.35756e-05)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687917,0.0359024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419143,-0.0177044) , 
3, 0.277748, 1, 0, 0.622198,0.113883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.188087,-0.0588939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418165,-0.0145193) , 
0, 1140.08, 1, 0, 0.309382,-0.176926) , 
5, 9.48996, 1, 0, 0.500381,0.000635443)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542977,0.00493772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283075,-0.0377337) , 
5, 7.1731, 1, 0, 0.399842,-0.0920037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761281,0.0486836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373059,-0.0209974) , 
5, 14.247, 1, 0, 0.683611,0.173276) , 
0, 1436.71, 1, 0, 0.502862,0.00430403)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514161,-0.000888412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707426,0.0344995) , 
1, 4.14719, 1, 0, 0.635495,0.105916) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.154604,-0.0567433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393356,-0.0169659) , 
0, 1126.21, 1, 0, 0.28271,-0.17404) , 
5, 9.51351, 1, 0, 0.490869,-0.0088534)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739619,0.0394164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515306,-0.00265561) , 
3, 0.154278, 1, 0, 0.624221,0.0878565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413489,-0.00713321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191599,-0.0487058) , 
2, 0.0240516, 1, 0, 0.286084,-0.151131) , 
5, 10.0431, 1, 0, 0.493769,-0.00434336)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536824,0.000720388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227555,-0.0387313) , 
5, 8.47028, 1, 0, 0.390973,-0.0859511) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734881,0.0375797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304814,-0.02778) , 
5, 18.9796, 1, 0, 0.669412,0.135543) , 
0, 1436.72, 1, 0, 0.487841,-0.00889424)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457714,-0.00479529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723709,0.0359455) , 
0, 1142.42, 1, 0, 0.622712,0.0998394) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464073,-0.00926927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142782,-0.0494536) , 
5, 15.4532, 1, 0, 0.381232,-0.0932127) , 
2, 0.0277293, 1, 0, 0.512756,0.0119344)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483249,-0.00394795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743783,0.0348581) , 
0, 1269.49, 1, 0, 0.608931,0.0712636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288351,-0.0223628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139933,-0.0497723) , 
5, 22.9196, 1, 0, 0.214012,-0.167668) , 
5, 14.3886, 1, 0, 0.51337,0.0134478)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684592,0.029393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391443,-0.019487) , 
3, 0.2901, 1, 0, 0.617694,0.0873282) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46049,-0.00241181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270977,-0.0362272) , 
3, 0.154368, 1, 0, 0.354807,-0.10135) , 
2, 0.0295976, 1, 0, 0.504593,0.00615432)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461914,-0.00830474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715763,0.0291032) , 
1, 4.18047, 1, 0, 0.611695,0.0654884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.161163,-0.0416942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450891,0.00315313) , 
0, 1565.36, 1, 0, 0.230137,-0.139245) , 
5, 14.2341, 1, 0, 0.51378,0.0129498)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639412,0.016885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373387,-0.0241912) , 
3, 0.314779, 1, 0, 0.58815,0.0424479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.14473,-0.0424763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419885,-0.00186885) , 
0, 1861.75, 1, 0, 0.189991,-0.156771) , 
5, 15.9882, 1, 0, 0.506477,0.00158282)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375404,-0.0203627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666315,0.0216992) , 
1, 3.22216, 1, 0, 0.626552,0.0745287) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342498,-0.0226599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704487,0.0325185) , 
1, 5.80193, 1, 0, 0.373993,-0.0830429) , 
2, 0.0240233, 1, 0, 0.500796,-0.00393044)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409118,-0.0107175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231792,-0.0380284) , 
3, 0.216017, 1, 0, 0.329535,-0.106457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729058,0.0256003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362025,-0.0147446) , 
5, 9.48996, 1, 0, 0.58426,0.0452157) , 
0, 1044.31, 1, 0, 0.489799,-0.01103)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576466,0.0136302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364225,-0.0198915) , 
3, 0.111118, 1, 0, 0.433751,-0.0414798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.816761,0.0426343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525194,-0.000669061) , 
2, 0.0404978, 1, 0, 0.743469,0.143306) , 
1, 5.25847, 1, 0, 0.502776,-0.000297742)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451719,-0.00431313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715511,0.0263064) , 
0, 1044.31, 1, 0, 0.633781,0.0766222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513001,0.00475206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316157,-0.0247204) , 
3, 0.135859, 1, 0, 0.396341,-0.0579757) , 
2, 0.0221761, 1, 0, 0.509887,0.00639033)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648897,0.0152833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397992,-0.0316832) , 
4, 1.04469, 1, 0, 0.616947,0.0430993) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256706,-0.0223621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116144,-0.061721) , 
4, 0.526628, 1, 0, 0.242652,-0.115591) , 
5, 11.1913, 1, 0, 0.490119,-0.0106721)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732232,0.0239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386529,-0.00771197) , 
5, 9.88328, 1, 0, 0.613932,0.0591535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410607,-0.00856865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18963,-0.0404467) , 
3, 0.296327, 1, 0, 0.359548,-0.0713004) , 
2, 0.029602, 1, 0, 0.504351,0.00295764)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775817,0.0335181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521545,0.00443214) , 
5, 3.165, 1, 0, 0.577894,0.0494007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329335,-0.0130669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31083,-0.0369212) , 
4, 0.708611, 1, 0, 0.322472,-0.100986) , 
3, 0.28392, 1, 0, 0.513973,0.0117656)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472524,-0.00516607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133586,-0.0365817) , 
5, 12.7913, 1, 0, 0.362291,-0.063505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687018,0.0196491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198195,-0.0346624) , 
5, 24.6686, 1, 0, 0.644825,0.0672612) , 
0, 1244.74, 1, 0, 0.495861,-0.00168456)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682887,0.0146216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330229,-0.0116386) , 
5, 10.2638, 1, 0, 0.556888,0.0241692) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326453,-0.0170212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191123,-0.059428) , 
4, 1.00477, 1, 0, 0.302464,-0.111366) , 
2, 0.0517958, 1, 0, 0.4928,-0.00997139)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638135,0.0149188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354157,-0.0166514) , 
3, 0.308626, 1, 0, 0.582727,0.0385484) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535353,0.00432952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229577,-0.0319945) , 
5, 5.15241, 1, 0, 0.315311,-0.0923771) , 
2, 0.0407027, 1, 0, 0.491,-0.00636032)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698267,0.0208416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442244,-0.00483374) , 
2, 0.0184862, 1, 0, 0.543125,0.0226698) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253151,-0.00826438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29594,-0.0295918) , 
4, 0.373119, 1, 0, 0.281091,-0.100982) , 
3, 0.327142, 1, 0, 0.497954,0.00135381)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639457,0.0131672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165852,-0.0325451) , 
5, 19.7619, 1, 0, 0.566587,0.029486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528187,0.00305091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263791,-0.0274104) , 
2, 0.012949, 1, 0, 0.337248,-0.0809255) , 
3, 0.240711, 1, 0, 0.486662,-0.00899239)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541807,-0.00130745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180355,-0.0269996) , 
5, 14.3888, 1, 0, 0.448198,-0.0315388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755806,0.0390889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.788874,0.0195041) , 
4, 0.60786, 1, 0, 0.773224,0.121644) , 
1, 5.74709, 1, 0, 0.488801,-0.0124027)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476971,-0.000463211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73862,0.0254065) , 
0, 1060.47, 1, 0, 0.6574,0.0735405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412159,-0.00666527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209131,-0.0505138) , 
4, 1.18276, 1, 0, 0.401274,-0.0393358) , 
2, 0.0166511, 1, 0, 0.496477,0.00262096)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589329,0.0105813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15762,-0.026491) , 
5, 21.516, 1, 0, 0.525205,0.0254876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492724,-0.0145534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122567,-0.0656893) , 
5, 4.52534, 1, 0, 0.331383,-0.167704) , 
4, 1.04455, 1, 0, 0.509549,0.00988198)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506028,0.000998462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308296,-0.0207654) , 
3, 0.154359, 1, 0, 0.391996,-0.0494438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759399,0.022305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27279,-0.0169912) , 
5, 15.835, 1, 0, 0.677527,0.0653723) , 
1, 4.90682, 1, 0, 0.481968,-0.0132649)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504478,-0.00109567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202872,-0.0293913) , 
5, 7.17465, 1, 0, 0.330604,-0.0696513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666869,0.019997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484845,-0.00326559) , 
3, 0.117262, 1, 0, 0.557577,0.0253256) , 
1, 3.60463, 1, 0, 0.506638,0.00400989)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277045,-0.0163638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28996,-0.039449) , 
4, 0.729556, 1, 0, 0.281756,-0.108892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609171,0.0100798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195366,-0.0213972) , 
5, 17.3968, 1, 0, 0.533573,0.021523) , 
1, 3.19284, 1, 0, 0.501755,0.00504493)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55666,0.00631637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330875,-0.0329924) , 
4, 1.06404, 1, 0, 0.538503,0.0124559) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244416,-0.0160263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22223,-0.0463678) , 
4, 0.748221, 1, 0, 0.236422,-0.116124) , 
3, 0.351796, 1, 0, 0.496201,-0.00554966)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708467,0.0194068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438069,-0.00559666) , 
2, 0.0368162, 1, 0, 0.614288,0.0433292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519785,-0.000440228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279864,-0.0177829) , 
2, 0.0240241, 1, 0, 0.401036,-0.0370813) , 
3, 0.166658, 1, 0, 0.503642,0.00160807)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53871,0.00462241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393217,-0.0252705) , 
4, 1.00447, 1, 0, 0.522898,0.00518775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257332,-0.00657743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172555,-0.0432556) , 
1, 3.48921, 1, 0, 0.198922,-0.130794) , 
3, 0.382655, 1, 0, 0.488858,-0.00909992)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.810282,0.0382032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625074,0.00549555) , 
4, 0.815565, 1, 0, 0.690398,0.0726324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413992,-0.00164813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200387,-0.0614447) , 
4, 0.708554, 1, 0, 0.386118,-0.0399453) , 
5, 5.48248, 1, 0, 0.505116,0.00408175)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544687,0.0092095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340581,-0.0113185) , 
3, 0.104985, 1, 0, 0.401564,-0.0212179) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727835,0.0187437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235189,-0.0238469) , 
5, 20.561, 1, 0, 0.673033,0.0570672) , 
0, 1436.71, 1, 0, 0.496774,0.00623848)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61478,0.00551887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354872,-0.0215169) , 
4, 1.04459, 1, 0, 0.585155,0.0101186) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377133,0.00357075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156312,-0.0252324) , 
2, 0.00931142, 1, 0, 0.194815,-0.0685962) , 
5, 15.0725, 1, 0, 0.49549,-0.00796309)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63366,0.0212346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34338,-0.010675) , 
5, 1.60078, 1, 0, 0.371636,-0.0301025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701336,0.0180382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40534,-0.00982577) , 
2, 0.049946, 1, 0, 0.629395,0.0444969) , 
0, 1161.33, 1, 0, 0.51144,0.0103588)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310553,-0.0227253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590001,0.0088165) , 
1, 3.22295, 1, 0, 0.558611,0.0210313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498391,0.00935246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235022,-0.0265784) , 
2, 0.00745061, 1, 0, 0.271313,-0.083612) , 
3, 0.296282, 1, 0, 0.492782,-0.00294593)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797867,0.0376002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.677759,0.00643775) , 
5, 1.26523, 1, 0, 0.719485,0.07188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451477,-0.00063252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318083,-0.0371313) , 
4, 0.807657, 1, 0, 0.433066,-0.0236289) , 
5, 3.19928, 1, 0, 0.497673,-0.00208518)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645655,0.0146376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440179,-0.00388869) , 
2, 0.0073889, 1, 0, 0.469622,-0.0048862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.817477,0.036395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.759737,0.0170397) , 
0, 2758.71, 1, 0, 0.783818,0.0964041) , 
0, 2316.65, 1, 0, 0.50475,0.00643819)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560076,0.0155092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564157,-0.00506796) , 
4, 0.590416, 1, 0, 0.562367,0.016669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119054,-0.0181006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155928,-0.033546) , 
0, 1153.55, 1, 0, 0.136853,-0.0882984) , 
5, 21.6655, 1, 0, 0.502016,0.00178138)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352635,-0.00608216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262455,-0.0301847) , 
0, 845.68, 1, 0, 0.316471,-0.0642622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590198,0.00821352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0941255,-0.037845) , 
5, 28.2314, 1, 0, 0.555432,0.0230659) , 
0, 914.913, 1, 0, 0.50053,0.00300205)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44038,-0.0143758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.735993,0.0164705) , 
1, 3.46662, 1, 0, 0.692577,0.0465535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432275,0.00171408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335686,-0.0347168) , 
4, 0.688665, 1, 0, 0.413741,-0.0218221) , 
5, 4.79728, 1, 0, 0.507086,0.00106786)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433931,0.0026261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159892,-0.0367792) , 
2, 0.0225143, 1, 0, 0.289757,-0.0676094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650005,0.00949022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260256,-0.00889524) , 
5, 12.7045, 1, 0, 0.539562,0.018929) , 
1, 3.10478, 1, 0, 0.510549,0.0088785)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465701,-0.000241624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.765945,0.0215665) , 
1, 5.17707, 1, 0, 0.534877,0.0177823) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.18941,-0.0478873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309806,-0.00720539) , 
2, 0.0899856, 1, 0, 0.280648,-0.0674967) , 
2, 0.0795436, 1, 0, 0.495845,0.00468908)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741488,0.00213793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760254,0.0343074) , 
3, 0.148298, 1, 0, 0.752588,0.0900984) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438024,0.00505984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528279,-0.0122329) , 
4, 0.590139, 1, 0, 0.476936,-0.0105381) , 
5, 1.43602, 1, 0, 0.502686,-0.00113722)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.254128,-0.0317975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272429,-0.00555638) , 
3, 0.25941, 1, 0, 0.261593,-0.0871446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626761,0.00481204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224665,-0.0117714) , 
5, 14.2341, 1, 0, 0.528151,0.00494803) , 
1, 3.13073, 1, 0, 0.499097,-0.00508951)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651949,0.00635786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295489,-0.0348772) , 
2, 0.105371, 1, 0, 0.627754,0.0134959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307306,-0.00616332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227372,-0.0362485) , 
4, 0.491969, 1, 0, 0.290149,-0.0487609) , 
5, 9.49021, 1, 0, 0.485757,-0.0126893)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682359,0.011048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3941,-0.00679088) , 
2, 0.0314265, 1, 0, 0.554078,0.011479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305286,-0.00494712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296535,-0.0309323) , 
4, 0.767529, 1, 0, 0.302345,-0.0556528) , 
3, 0.277752, 1, 0, 0.485378,-0.00684182)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.116159,-0.0356559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539064,0.00546804) , 
4, -0.0828723, 1, 0, 0.52287,0.0167794) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554423,-0.0050886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0799172,-0.0545962) , 
5, 4.72152, 1, 0, 0.407225,-0.0752639) , 
4, 0.985185, 1, 0, 0.508895,0.0056567)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449779,0.00722966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521757,-0.00811506) , 
4, 0.708932, 1, 0, 0.476699,0.00501006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.923486,0.0565838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750496,0.0144871) , 
0, 2849.52, 1, 0, 0.811656,0.103136) , 
0, 2454.36, 1, 0, 0.512323,0.0154463)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566095,0.00590634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260114,-0.0152634) , 
3, 0.401209, 1, 0, 0.541502,0.0172854) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253381,-0.00640483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0262144,-0.0484347) , 
2, 0.0260608, 1, 0, 0.109628,-0.0832209) , 
5, 26.8193, 1, 0, 0.505899,0.00899977)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0485608,-0.0496266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345662,-0.012775) , 
4, 0.0968974, 1, 0, 0.303947,-0.0647801) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727588,0.01497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407025,-0.005379) , 
5, 7.05886, 1, 0, 0.559818,0.0166375) , 
0, 914.533, 1, 0, 0.503619,-0.00124494)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7269,0.0135718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44734,-0.00612224) , 
5, 3.16449, 1, 0, 0.498315,-0.00987317) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338979,-0.0113162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417963,-0.0355145) , 
1, 4.62422, 1, 0, 0.36744,-0.081171) , 
4, 1.00497, 1, 0, 0.483429,-0.0179824)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689997,0.0294425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60128,0.0015813) , 
4, 0.359748, 1, 0, 0.615745,0.025553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184397,-0.00301266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200231,-0.022776) , 
1, 4.22493, 1, 0, 0.192454,-0.0457142) , 
5, 14.3883, 1, 0, 0.509011,0.00758277)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620997,0.0201433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201636,-0.00631739) , 
5, 15.9954, 1, 0, 0.404534,0.0306226) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638854,0.00391149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293434,-0.034421) , 
5, 7.28262, 1, 0, 0.560647,-0.0186144) , 
4, 0.471601, 1, 0, 0.496114,0.00173879)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664944,0.0488218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753969,0.0134391) , 
4, 0.282302, 1, 0, 0.73458,0.0818037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613202,0.0116766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382651,-0.00957968) , 
3, 0.11112, 1, 0, 0.463155,-0.00809116) , 
2, 0.00739447, 1, 0, 0.504163,0.00549042)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638753,0.00823319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184735,-0.017704) , 
5, 14.397, 1, 0, 0.503917,0.00634595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457507,-0.0304647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377629,0.00435922) , 
4, 1.14761, 1, 0, 0.431323,-0.0787275) , 
4, 0.945682, 1, 0, 0.49166,-0.00801754)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791568,0.0196035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54868,-0.000686488) , 
2, 0.0221348, 1, 0, 0.678238,0.0365199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37702,-0.00474562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174919,-0.0460194) , 
4, 0.70852, 1, 0, 0.355625,-0.0333737) , 
5, 6.3958, 1, 0, 0.498262,-0.00247157)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.755701,0.00143385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642739,0.0163839) , 
3, 0.160582, 1, 0, 0.699565,0.0372182) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410059,-0.000619595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469348,-0.0149398) , 
4, 0.590373, 1, 0, 0.43253,-0.023968) , 
5, 3.16449, 1, 0, 0.488256,-0.0111994)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552169,0.00518147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542986,-0.00971881) , 
4, 0.847289, 1, 0, 0.549467,0.00337661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155625,-0.00224945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0815499,-0.0355798) , 
1, 3.6562, 1, 0, 0.102838,-0.0723089) , 
5, 23.9801, 1, 0, 0.501729,-0.004713)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586149,0.0018005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.840282,0.0241258) , 
1, 5.14904, 1, 0, 0.655348,0.0272005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342729,0.000232376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258585,-0.030493) , 
4, 0.491269, 1, 0, 0.325395,-0.0235039) , 
5, 8.47053, 1, 0, 0.50258,0.00372438)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278571,-0.0354521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277227,-0.00748404) , 
3, 0.142024, 1, 0, 0.277655,-0.0650194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543043,0.000650199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219963,-0.0286737) , 
3, 0.419724, 1, 0, 0.526283,-0.00330191) , 
1, 3.44435, 1, 0, 0.480971,-0.0145498)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724221,0.0128534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403579,-0.0184398) , 
2, 0.0702478, 1, 0, 0.678044,0.0297839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396248,0.000506002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392357,-0.0204002) , 
4, 0.609826, 1, 0, 0.395261,-0.0187188) , 
5, 4.79728, 1, 0, 0.495747,-0.00148353)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607243,0.00200197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24506,-0.0129639) , 
5, 10.0416, 1, 0, 0.464739,-0.0125732) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.866257,0.0463838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.751961,-0.00589966) , 
4, 0.550081, 1, 0, 0.800411,0.0589005) , 
0, 2477.56, 1, 0, 0.495565,-0.00600952)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255352,-0.0238731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447194,0.00445613) , 
0, 802.288, 1, 0, 0.424463,0.00447659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517592,-0.0164016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.781159,0.0141845) , 
1, 5.90433, 1, 0, 0.584799,-0.0333828) , 
1, 4.76978, 1, 0, 0.483449,-0.00945148)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461915,-0.00241454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194027,-0.0245311) , 
2, 0.0128801, 1, 0, 0.27916,-0.0629457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.754744,0.0227768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502934,0.00293933) , 
2, 0.0074005, 1, 0, 0.539389,0.0215363) , 
1, 3.18368, 1, 0, 0.510092,0.0120252)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192057,-0.0390111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347455,-0.00654594) , 
0, 771.813, 1, 0, 0.333086,-0.0365976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591914,0.00847356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617875,-0.00500623) , 
4, 0.845175, 1, 0, 0.599215,0.0175325) , 
0, 1044.32, 1, 0, 0.500787,-0.00248755)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782571,0.0247618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392441,0.00277704) , 
5, 6.33649, 1, 0, 0.449936,0.022112) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618681,0.000285342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142685,-0.049526) , 
5, 7.18417, 1, 0, 0.554821,-0.0215011) , 
4, 0.649307, 1, 0, 0.495045,0.00335492)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.78056,0.0450407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728965,-0.00674984) , 
0, 1245.01, 1, 0, 0.750843,0.070074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481645,-0.00174457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384444,0.0209275) , 
2, 0.107307, 1, 0, 0.474764,-0.000979073) , 
5, 1.58385, 1, 0, 0.500523,0.00565049)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576572,-0.00244887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51043,0.0119349) , 
3, 0.176008, 1, 0, 0.550641,0.0123849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331027,-0.0238864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213652,-0.00518687) , 
5, 6.3958, 1, 0, 0.262572,-0.0529279) , 
3, 0.339486, 1, 0, 0.506637,0.00240795)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79808,0.0260021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644668,0.00567751) , 
4, 0.827753, 1, 0, 0.695589,0.0463747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36707,0.00506869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444328,-0.0104275) , 
4, 0.412197, 1, 0, 0.403241,-0.00959746) , 
5, 4.74586, 1, 0, 0.501409,0.00919747)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351035,0.00485813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734734,0.0348824) , 
1, 5.41672, 1, 0, 0.418109,0.0372161) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639606,0.000326394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342814,-0.0232502) , 
5, 7.05769, 1, 0, 0.551733,-0.0255071) , 
4, 0.392569, 1, 0, 0.506891,-0.004458)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55159,0.000777104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401908,0.0181752) , 
2, 0.0638067, 1, 0, 0.526806,0.013309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190211,-0.0354103) , 
2, 0.120258, 1, 0, 0.512748,0.00745003)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693581,0.0352757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742839,0.00911089) , 
0, 905.109, 1, 0, 0.734881,0.0523664) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460286,-0.00325585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328433,-0.0287535) , 
4, 0.847176, 1, 0, 0.443144,-0.0245602) , 
5, 2.71926, 1, 0, 0.498058,-0.0100803)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731362,0.0190119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319938,-0.000497486) , 
5, 9.71015, 1, 0, 0.476538,0.0266092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63623,-0.000338305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255966,-0.0264433) , 
5, 5.24346, 1, 0, 0.558244,-0.0191005) , 
4, 0.708645, 1, 0, 0.507764,0.00914003)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757819,0.00283351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293709,-0.0319751) , 
5, 6.87577, 1, 0, 0.517112,-0.0604086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697098,0.0311409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49613,0.00125786) , 
3, 0.0424775, 1, 0, 0.504613,0.00940644) , 
3, 0.0308808, 1, 0, 0.50584,0.00255528)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491409,0.00380192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610401,-0.0120349) , 
4, 0.590425, 1, 0, 0.550448,-0.0152588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0569523,-0.0415871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438021,0.0148765) , 
4, 0.0567934, 1, 0, 0.372464,0.0307733) , 
2, 0.0480465, 1, 0, 0.501157,-0.00251075)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607042,0.0166878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332558,0.00176113) , 
2, 0.0240481, 1, 0, 0.461685,0.0334731) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636816,0.00184842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172637,-0.0359297) , 
5, 7.18293, 1, 0, 0.560334,-0.0126545) , 
4, 0.609907, 1, 0, 0.508074,0.0117816)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769401,0.0187241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445014,-0.000846057) , 
5, 4.41754, 1, 0, 0.494688,0.00784759) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693219,0.00696709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456059,-0.0194549) , 
3, 0.086411, 1, 0, 0.513487,-0.0494385) , 
4, 0.866878, 1, 0, 0.499172,-0.0058165)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343168,-0.00117364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665167,0.0179261) , 
0, 1491.25, 1, 0, 0.4361,0.0161713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707472,0.0075083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49234,-0.0142286) , 
3, 0.0864363, 1, 0, 0.553861,-0.0322081) , 
4, 0.590496, 1, 0, 0.493195,-0.00728489)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696036,0.00765127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352099,-0.0106792) , 
3, 0.33951, 1, 0, 0.643949,0.0178983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263925,-0.0051709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444565,-0.0311258) , 
1, 5.55657, 1, 0, 0.286932,-0.0313513) , 
5, 9.48996, 1, 0, 0.499147,-0.00207678)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588244,0.00394313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410597,0.0382573) , 
5, 16.1679, 1, 0, 0.579299,0.0214167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.171449,0.000563079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136183,-0.0265046) , 
4, 0.0768123, 1, 0, 0.154134,-0.0400471) , 
5, 18.9796, 1, 0, 0.508407,0.0111682)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.777832,0.0216458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625024,-0.00186076) , 
4, 0.830163, 1, 0, 0.692818,0.0308289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392715,-0.0011181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119129,-0.0285946) , 
3, 0.40734, 1, 0, 0.364164,-0.0121821) , 
5, 6.39606, 1, 0, 0.511872,0.00714842)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455008,-0.00420604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154233,-0.0335829) , 
3, 0.419727, 1, 0, 0.435072,-0.0223528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725168,-0.00493494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75619,0.0238551) , 
3, 0.141473, 1, 0, 0.740775,0.0342146) , 
0, 1927.23, 1, 0, 0.492276,-0.0117677)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710466,0.00795345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421443,-0.0175589) , 
2, 0.0700457, 1, 0, 0.670828,0.0147454) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27,0.00807567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384741,-0.0111165) , 
1, 3.52053, 1, 0, 0.359506,-0.0266407) , 
5, 6.3958, 1, 0, 0.497195,-0.00833675)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0951126,-0.0322796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495992,0.000292887) , 
4, -0.0419669, 1, 0, 0.47624,-0.00286872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749793,0.0386884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.805908,0.01192) , 
4, 0.396865, 1, 0, 0.78978,0.0640931) , 
0, 2319.63, 1, 0, 0.511935,0.00475462)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60562,-0.0135051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698279,0.0149196) , 
2, 0.00255059, 1, 0, 0.687096,0.0404065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490515,-0.00100598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244681,-0.0152982) , 
3, 0.283937, 1, 0, 0.42555,-0.0168291) , 
2, 0.0129306, 1, 0, 0.501314,-0.000249163)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67529,-0.00456274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270822,-0.0192487) , 
5, 12.302, 1, 0, 0.556823,-0.0327107) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436685,0.00508908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.88029,0.0445215) , 
0, 2614.06, 1, 0, 0.465016,0.0271364) , 
3, 0.142017, 1, 0, 0.504326,0.00151117)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619728,0.00925812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425057,-0.0209756) , 
4, 1.00018, 1, 0, 0.597821,0.0208618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363972,-0.00240689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54983,-0.0324839) , 
1, 5.51032, 1, 0, 0.388984,-0.0230908) , 
3, 0.166662, 1, 0, 0.493668,-0.00105869)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654681,0.022315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45055,-0.00483552) , 
3, 0.0185353, 1, 0, 0.461918,-0.0125702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.804397,0.00439216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733346,0.0350117) , 
2, 0.0295607, 1, 0, 0.785908,0.0451273) , 
0, 2123.43, 1, 0, 0.506934,-0.00455364)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.144856,-0.0406252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744296,0.0150062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469785,-0.00461783) , 
5, 1.41317, 1, 0, 0.491949,-0.010842) , 
1, 2.45911, 1, 0, 0.480888,-0.0150312)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575092,-0.0209709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483097,0.000448408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640002,-0.0274997) , 
1, 6.56152, 1, 0, 0.489645,-0.00218322) , 
2, 0.0036997, 1, 0, 0.494587,-0.00643604)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650448,0.00841487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425212,-0.00530635) , 
2, 0.0184794, 1, 0, 0.518163,0.00081549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361232,0.0479917) , 
4, 1.20253, 1, 0, 0.512259,0.00562672)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.030893,-0.0561618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467229,-0.000774168) , 
4, -0.0814685, 1, 0, 0.45078,-0.00729323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666024,-0.000333963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628417,-0.0377554) , 
4, 0.688738, 1, 0, 0.648526,-0.057288) , 
1, 5.50274, 1, 0, 0.486195,-0.0162468)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592412,0.00464591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503226,-0.00792306) , 
4, 0.886766, 1, 0, 0.567955,0.00504687) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179508,-0.00393321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137309,-0.0323203) , 
4, 0.175419, 1, 0, 0.164196,-0.0447927) , 
5, 16.939, 1, 0, 0.48787,-0.00483863)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319299,-0.019376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166827,0.0040866) , 
5, 13.7088, 1, 0, 0.273434,-0.0525933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532779,0.000274461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414269,0.0293877) , 
4, 1.14169, 1, 0, 0.527136,0.00544245) , 
1, 3.20352, 1, 0, 0.496794,-0.00149827)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401006,0.0103837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589082,-0.000152371) , 
4, 0.373333, 1, 0, 0.528819,0.0108001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239666,-0.00054133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231397,-0.0365101) , 
1, 4.3501, 1, 0, 0.235588,-0.0654327) , 
2, 0.0962065, 1, 0, 0.504557,0.00449277)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41852,-0.00253551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37451,0.0311773) , 
2, 0.108961, 1, 0, 0.415312,-0.00156939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714931,0.00484698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683808,0.0233029) , 
3, 0.135803, 1, 0, 0.699122,0.050777) , 
0, 1490.39, 1, 0, 0.50923,0.0157531)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487769,-0.00203178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.874105,0.0312728) , 
1, 6.27939, 1, 0, 0.508414,-0.00198574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437757,0.0437724) , 
4, 1.1828, 1, 0, 0.505695,0.00339709)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524278,-0.00110697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241344,0.0373009) , 
5, 31.9724, 1, 0, 0.50966,0.000750599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426628,0.0450405) , 
4, 1.20244, 1, 0, 0.506888,0.00535643)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286296,-0.0129535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698922,0.0125511) , 
4, 0.17584, 1, 0, 0.622983,0.0288726) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433199,-0.00680667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335025,0.0204925) , 
4, 1.08393, 1, 0, 0.425143,-0.0178242) , 
3, 0.1173, 1, 0, 0.499465,-0.000281533)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279017,-0.0114279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462436,0.00942896) , 
1, 3.14783, 1, 0, 0.42163,0.0181153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457632,0.00378474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63154,-0.0124615) , 
4, 0.373333, 1, 0, 0.576792,-0.0259839) , 
1, 4.44627, 1, 0, 0.496826,-0.00325643)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687462,0.0461681) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364927,0.00541371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541445,-0.00673937) , 
4, 0.353138, 1, 0, 0.485211,-0.0116679) , 
3, 0.0123714, 1, 0, 0.493836,-0.00472784)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427758,0.00228449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600162,-0.00637264) , 
1, 4.50313, 1, 0, 0.508145,-0.0059575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.028309,-0.0521423) , 
5, 35.1694, 1, 0, 0.491339,-0.0101197)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588357,0.00392352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.866108,0.0329776) , 
1, 4.22955, 1, 0, 0.741567,0.0683199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470846,-0.00949243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317913,0.0108083) , 
2, 0.0850364, 1, 0, 0.452445,-0.0264242) , 
5, 1.43602, 1, 0, 0.479888,-0.0174312)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25587,-0.00390066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444618,0.029825) , 
1, 2.43109, 1, 0, 0.381083,0.0684333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385985,0.00929134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568543,-0.00549249) , 
4, 0.353086, 1, 0, 0.510251,-0.00432802) , 
1, 2.96966, 1, 0, 0.498481,0.00230201)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335811,0.00247605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385592,-0.0154476) , 
4, 0.669056, 1, 0, 0.35587,-0.0195575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764159,0.0146119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4368,-0.00235572) , 
5, 6.32722, 1, 0, 0.586999,0.0187601) , 
1, 4.01883, 1, 0, 0.500015,0.00433948)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561615,0.00285044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483132,0.0286942) , 
3, 0.284953, 1, 0, 0.553811,0.0203382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190481,-0.0213198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507679,0.0219604) , 
1, 4.67754, 1, 0, 0.257714,-0.0366152) , 
3, 0.33945, 1, 0, 0.506925,0.0113198)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.287114,-0.0161994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488902,0.00391237) , 
0, 812.14, 1, 0, 0.468647,0.00713073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758167,-0.00207778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425576,-0.0334833) , 
2, 0.0367803, 1, 0, 0.661285,-0.0439579) , 
1, 5.50265, 1, 0, 0.503359,-0.00207509)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.353918,0.023881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493885,-0.00175121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454865,-0.0153807) , 
4, 0.945858, 1, 0, 0.487306,-0.0147435) , 
1, 2.48153, 1, 0, 0.482264,-0.0110551)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348445,0.00468576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580278,0.022493) , 
4, 0.29888, 1, 0, 0.399661,0.0307345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580261,-0.00731832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415907,0.00986642) , 
2, 0.062853, 1, 0, 0.548743,-0.0150498) , 
4, 0.412269, 1, 0, 0.496922,0.000864854)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803288,0.0174308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565707,0.00139138) , 
2, 0.0240403, 1, 0, 0.705088,0.0354582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398716,0.000763068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609354,-0.0293518) , 
1, 6.00236, 1, 0, 0.415467,-0.00559906) , 
5, 4.79728, 1, 0, 0.515877,0.00863535)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552849,-0.000668146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297918,0.0398665) , 
5, 33.5763, 1, 0, 0.542568,0.00218875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295728,-0.0062515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258455,-0.0251935) , 
4, 0.846875, 1, 0, 0.284642,-0.0433237) , 
2, 0.0702244, 1, 0, 0.49584,-0.00605678)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658953,0.00549833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258404,-0.00921926) , 
5, 11.7582, 1, 0, 0.515459,0.00220367) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539771,-0.00510078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0861307,-0.0541055) , 
2, 0.0779172, 1, 0, 0.427841,-0.0594997) , 
4, 0.965317, 1, 0, 0.50278,-0.00672512)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.132767,-0.0254348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534198,0.00170748) , 
4, -0.00241285, 1, 0, 0.505795,0.00127564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177164,-0.0313258) , 
2, 0.118312, 1, 0, 0.491684,-0.00321399)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280547,-0.0219627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21308,0.0137449) , 
2, 0.0479385, 1, 0, 0.26148,-0.0527882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641734,0.0116394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449674,-0.000689474) , 
3, 0.154306, 1, 0, 0.542747,0.0189132) , 
1, 3.11334, 1, 0, 0.51111,0.0108482)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371941,0.00811044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589607,0.0515922) , 
1, 3.4208, 1, 0, 0.404408,0.0538583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388628,0.00550478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575961,-0.00749868) , 
4, 0.333834, 1, 0, 0.519796,-0.014028) , 
1, 3.53453, 1, 0, 0.494211,0.00102441)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57855,-0.00458656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427138,0.00521155) , 
3, 0.191344, 1, 0, 0.510564,-0.000741504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727139,0.0459428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103992,-0.0204633) , 
5, 5.44597, 1, 0, 0.451763,0.0848161) , 
4, 1.10381, 1, 0, 0.506338,0.00540711)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528425,0.000601108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375704,0.0322605) , 
3, 0.37774, 1, 0, 0.523404,0.00578196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.178613,0.00078445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213982,-0.0337005) , 
0, 1031.61, 1, 0, 0.196619,-0.062122) , 
3, 0.413526, 1, 0, 0.501931,0.00131989)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640432,0.00435093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281249,-0.00670671) , 
5, 11.0716, 1, 0, 0.516154,0.00304233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213218,-0.0282105) , 
2, 0.12024, 1, 0, 0.504164,-0.000983452)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541628,0.00269093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104838,-0.0273314) , 
5, 33.9712, 1, 0, 0.523517,0.00644167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247683,-0.0220197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170741,-0.00903543) , 
2, 0.0187326, 1, 0, 0.204088,-0.0502829) , 
3, 0.407355, 1, 0, 0.497977,0.00190626)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440545,0.000785787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378839,0.037073) , 
2, 0.101768, 1, 0, 0.435689,0.0118246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422823,-0.0287807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664482,-0.00307195) , 
1, 5.12888, 1, 0, 0.609534,-0.0321794) , 
1, 4.85129, 1, 0, 0.495271,-0.00325686)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675378,0.00474644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521854,0.0199925) , 
2, 0.064678, 1, 0, 0.651542,0.027874) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517022,0.0235156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230741,-0.0116892) , 
2, 0.00924005, 1, 0, 0.279887,-0.0147408) , 
5, 10.4445, 1, 0, 0.510702,0.011725)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339209,-0.00848375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585325,0.00791791) , 
1, 3.85754, 1, 0, 0.509257,0.00967184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690057,0.00468551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217948,-0.0342533) , 
2, 0.0354556, 1, 0, 0.477236,-0.0462422) , 
4, 0.945834, 1, 0, 0.503963,0.00042737)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589429,-0.000141399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239117,-0.0185928) , 
3, 0.364161, 1, 0, 0.546062,-0.00870046) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0786491,-0.0354155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470695,0.0210248) , 
4, 0.116621, 1, 0, 0.387922,0.0479764) , 
2, 0.0499127, 1, 0, 0.504892,0.00605446)    );
   return;
};

// Clean up
inline void ReadBDT-0.3_fold9::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT-0.3_fold9::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
